# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'akun.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProfilDonor(object):
    def setupUi(self, ProfilDonor):
        ProfilDonor.setObjectName("ProfilDonor")
        ProfilDonor.resize(1200, 800)
        ProfilDonor.setStyleSheet("\n"
"QMainWindow {\n"
"    background-color: #f5f5f5;\n"
"}\n"
"QPushButton {\n"
"    border: none;\n"
"    padding: 10px 20px;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    opacity: 0.8;\n"
"}\n"
"QFrame {\n"
"    border-radius: 10px;\n"
"}\n"
"QLabel {\n"
"    color: #333333;\n"
"}\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(ProfilDonor)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.navbar = QtWidgets.QFrame(self.centralwidget)
        self.navbar.setMinimumSize(QtCore.QSize(0, 70))
        self.navbar.setMaximumSize(QtCore.QSize(16777215, 70))
        self.navbar.setStyleSheet("\n"
"QFrame#navbar {\n"
"    background-color: #750003;\n"
"}\n"
"QPushButton {\n"
"    color: white;\n"
"    background-color: transparent;\n"
"    text-align: left;\n"
"    padding: 15px 25px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.1);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 0.2);\n"
"}\n"
"       ")
        self.navbar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.navbar.setObjectName("navbar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.navbar)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logoLabel = QtWidgets.QLabel(self.navbar)
        self.logoLabel.setMinimumSize(QtCore.QSize(200, 0))
        self.logoLabel.setStyleSheet("color: white; font-size: 18px; font-weight: bold; padding-left: 20px;")
        self.logoLabel.setObjectName("logoLabel")
        self.horizontalLayout.addWidget(self.logoLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnDashboard = QtWidgets.QPushButton(self.navbar)
        self.btnDashboard.setMinimumSize(QtCore.QSize(120, 0))
        self.btnDashboard.setObjectName("btnDashboard")
        self.horizontalLayout.addWidget(self.btnDashboard)
        self.btnPendaftaran = QtWidgets.QPushButton(self.navbar)
        self.btnPendaftaran.setMinimumSize(QtCore.QSize(170, 0))
        self.btnPendaftaran.setObjectName("btnPendaftaran")
        self.horizontalLayout.addWidget(self.btnPendaftaran)
        self.btnJadwal = QtWidgets.QPushButton(self.navbar)
        self.btnJadwal.setMinimumSize(QtCore.QSize(130, 0))
        self.btnJadwal.setObjectName("btnJadwal")
        self.horizontalLayout.addWidget(self.btnJadwal)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btnProfil = QtWidgets.QPushButton(self.navbar)
        self.btnProfil.setMinimumSize(QtCore.QSize(50, 50))
        self.btnProfil.setMaximumSize(QtCore.QSize(50, 50))
        self.btnProfil.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: white;\n"
"    border-radius: 25px;\n"
"    min-width: 50px;\n"
"    max-width: 50px;\n"
"    min-height: 50px;\n"
"    max-height: 50px;\n"
"    padding: 0px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.9);\n"
"}\n"
"          ")
        self.btnProfil.setObjectName("btnProfil")
        self.horizontalLayout.addWidget(self.btnProfil)
        self.verticalLayout.addWidget(self.navbar)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setStyleSheet("QScrollArea { border: none; background-color: #f5f5f5; }")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollContent = QtWidgets.QWidget()
        self.scrollContent.setGeometry(QtCore.QRect(0, 0, 1187, 750))
        self.scrollContent.setObjectName("scrollContent")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollContent)
        self.verticalLayout_2.setContentsMargins(30, 30, 30, 30)
        self.verticalLayout_2.setSpacing(25)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pageTitle = QtWidgets.QLabel(self.scrollContent)
        self.pageTitle.setStyleSheet("font-size: 28px; font-weight: bold; color: #750003;")
        self.pageTitle.setObjectName("pageTitle")
        self.verticalLayout_2.addWidget(self.pageTitle)
        self.photoCard = QtWidgets.QFrame(self.scrollContent)
        self.photoCard.setStyleSheet("\n"
"QFrame#photoCard {\n"
"    background-color: white;\n"
"    border: 2px solid #750003;\n"
"    padding: 20px;\n"
"}\n"
"           ")
        self.photoCard.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.photoCard.setObjectName("photoCard")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.photoCard)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.photoLabel = QtWidgets.QLabel(self.photoCard)
        self.photoLabel.setMinimumSize(QtCore.QSize(120, 120))
        self.photoLabel.setMaximumSize(QtCore.QSize(120, 120))
        self.photoLabel.setStyleSheet("\n"
"QLabel {\n"
"    background-color: #750003;\n"
"    border-radius: 60px;\n"
"    color: white;\n"
"    font-size: 60px;\n"
"}\n"
"              ")
        self.photoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.photoLabel.setObjectName("photoLabel")
        self.verticalLayout_3.addWidget(self.photoLabel)
        self.btnGantiFoto = QtWidgets.QPushButton(self.photoCard)
        self.btnGantiFoto.setMinimumSize(QtCore.QSize(150, 35))
        self.btnGantiFoto.setMaximumSize(QtCore.QSize(150, 35))
        self.btnGantiFoto.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: #750003;\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 8px 16px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5a0002;\n"
"}\n"
"              ")
        self.btnGantiFoto.setObjectName("btnGantiFoto")
        self.verticalLayout_3.addWidget(self.btnGantiFoto)
        self.verticalLayout_2.addWidget(self.photoCard)
        self.dataFrame = QtWidgets.QFrame(self.scrollContent)
        self.dataFrame.setStyleSheet("\n"
"QFrame#dataFrame {\n"
"    background-color: white;\n"
"    border: 1px solid #ddd;\n"
"}\n"
"           ")
        self.dataFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dataFrame.setObjectName("dataFrame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.dataFrame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lblDataPribadi = QtWidgets.QLabel(self.dataFrame)
        self.lblDataPribadi.setStyleSheet("font-size: 18px; font-weight: bold; color: #750003; margin-bottom: 10px;")
        self.lblDataPribadi.setObjectName("lblDataPribadi")
        self.verticalLayout_4.addWidget(self.lblDataPribadi)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setHorizontalSpacing(20)
        self.formLayout.setVerticalSpacing(15)
        self.formLayout.setObjectName("formLayout")
        self.lblNama = QtWidgets.QLabel(self.dataFrame)
        self.lblNama.setStyleSheet("font-size: 14px; font-weight: bold; color: #666;")
        self.lblNama.setObjectName("lblNama")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblNama)
        self.inputNama = QtWidgets.QLineEdit(self.dataFrame)
        self.inputNama.setMinimumSize(QtCore.QSize(0, 40))
        self.inputNama.setStyleSheet("\n"
"QLineEdit {\n"
"    border: 2px solid #ddd;\n"
"    border-radius: 5px;\n"
"    padding: 8px 12px;\n"
"    background-color: white;\n"
"    font-size: 14px;\n"
"}\n"
"QLineEdit:focus {\n"
"    border-color: #750003;\n"
"}\n"
"QLineEdit:disabled {\n"
"    background-color: #f5f5f5;\n"
"    color: #999;\n"
"}\n"
"                ")
        self.inputNama.setReadOnly(True)
        self.inputNama.setObjectName("inputNama")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.inputNama)
        self.lblNIK = QtWidgets.QLabel(self.dataFrame)
        self.lblNIK.setStyleSheet("font-size: 14px; font-weight: bold; color: #666;")
        self.lblNIK.setObjectName("lblNIK")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblNIK)
        self.inputNIK = QtWidgets.QLineEdit(self.dataFrame)
        self.inputNIK.setMinimumSize(QtCore.QSize(0, 40))
        self.inputNIK.setStyleSheet("\n"
"QLineEdit {\n"
"    border: 2px solid #ddd;\n"
"    border-radius: 5px;\n"
"    padding: 8px 12px;\n"
"    background-color: white;\n"
"    font-size: 14px;\n"
"}\n"
"QLineEdit:focus {\n"
"    border-color: #750003;\n"
"}\n"
"QLineEdit:disabled {\n"
"    background-color: #f5f5f5;\n"
"    color: #999;\n"
"}\n"
"                ")
        self.inputNIK.setReadOnly(True)
        self.inputNIK.setObjectName("inputNIK")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.inputNIK)
        self.lblTglLahir = QtWidgets.QLabel(self.dataFrame)
        self.lblTglLahir.setStyleSheet("font-size: 14px; font-weight: bold; color: #666;")
        self.lblTglLahir.setObjectName("lblTglLahir")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lblTglLahir)
        self.inputTglLahir = QtWidgets.QLineEdit(self.dataFrame)
        self.inputTglLahir.setMinimumSize(QtCore.QSize(0, 40))
        self.inputTglLahir.setStyleSheet("\n"
"QLineEdit {\n"
"    border: 2px solid #ddd;\n"
"    border-radius: 5px;\n"
"    padding: 8px 12px;\n"
"    background-color: white;\n"
"    font-size: 14px;\n"
"}\n"
"QLineEdit:focus {\n"
"    border-color: #750003;\n"
"}\n"
"QLineEdit:disabled {\n"
"    background-color: #f5f5f5;\n"
"    color: #999;\n"
"}\n"
"                ")
        self.inputTglLahir.setReadOnly(True)
        self.inputTglLahir.setObjectName("inputTglLahir")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.inputTglLahir)
        self.lblJenisKelamin = QtWidgets.QLabel(self.dataFrame)
        self.lblJenisKelamin.setStyleSheet("font-size: 14px; font-weight: bold; color: #666;")
        self.lblJenisKelamin.setObjectName("lblJenisKelamin")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lblJenisKelamin)
        self.inputJenisKelamin = QtWidgets.QLineEdit(self.dataFrame)
        self.inputJenisKelamin.setMinimumSize(QtCore.QSize(0, 40))
        self.inputJenisKelamin.setStyleSheet("\n"
"QLineEdit {\n"
"    border: 2px solid #ddd;\n"
"    border-radius: 5px;\n"
"    padding: 8px 12px;\n"
"    background-color: white;\n"
"    font-size: 14px;\n"
"}\n"
"QLineEdit:focus {\n"
"    border-color: #750003;\n"
"}\n"
"QLineEdit:disabled {\n"
"    background-color: #f5f5f5;\n"
"    color: #999;\n"
"}\n"
"                ")
        self.inputJenisKelamin.setReadOnly(True)
        self.inputJenisKelamin.setObjectName("inputJenisKelamin")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.inputJenisKelamin)
        self.lblGolDarah = QtWidgets.QLabel(self.dataFrame)
        self.lblGolDarah.setStyleSheet("font-size: 14px; font-weight: bold; color: #666;")
        self.lblGolDarah.setObjectName("lblGolDarah")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lblGolDarah)
        self.inputGolDarah = QtWidgets.QLineEdit(self.dataFrame)
        self.inputGolDarah.setMinimumSize(QtCore.QSize(0, 40))
        self.inputGolDarah.setStyleSheet("\n"
"QLineEdit {\n"
"    border: 2px solid #ddd;\n"
"    border-radius: 5px;\n"
"    padding: 8px 12px;\n"
"    background-color: white;\n"
"    font-size: 14px;\n"
"}\n"
"QLineEdit:focus {\n"
"    border-color: #750003;\n"
"}\n"
"QLineEdit:disabled {\n"
"    background-color: #f5f5f5;\n"
"    color: #999;\n"
"}\n"
"                ")
        self.inputGolDarah.setReadOnly(True)
        self.inputGolDarah.setObjectName("inputGolDarah")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.inputGolDarah)
        self.lblTelepon = QtWidgets.QLabel(self.dataFrame)
        self.lblTelepon.setStyleSheet("font-size: 14px; font-weight: bold; color: #666;")
        self.lblTelepon.setObjectName("lblTelepon")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lblTelepon)
        self.inputTelepon = QtWidgets.QLineEdit(self.dataFrame)
        self.inputTelepon.setMinimumSize(QtCore.QSize(0, 40))
        self.inputTelepon.setStyleSheet("\n"
"QLineEdit {\n"
"    border: 2px solid #ddd;\n"
"    border-radius: 5px;\n"
"    padding: 8px 12px;\n"
"    background-color: white;\n"
"    font-size: 14px;\n"
"}\n"
"QLineEdit:focus {\n"
"    border-color: #750003;\n"
"}\n"
"                ")
        self.inputTelepon.setObjectName("inputTelepon")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.inputTelepon)
        self.lblEmail = QtWidgets.QLabel(self.dataFrame)
        self.lblEmail.setStyleSheet("font-size: 14px; font-weight: bold; color: #666;")
        self.lblEmail.setObjectName("lblEmail")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.lblEmail)
        self.inputEmail = QtWidgets.QLineEdit(self.dataFrame)
        self.inputEmail.setMinimumSize(QtCore.QSize(0, 40))
        self.inputEmail.setStyleSheet("\n"
"QLineEdit {\n"
"    border: 2px solid #ddd;\n"
"    border-radius: 5px;\n"
"    padding: 8px 12px;\n"
"    background-color: white;\n"
"    font-size: 14px;\n"
"}\n"
"QLineEdit:focus {\n"
"    border-color: #750003;\n"
"}\n"
"                ")
        self.inputEmail.setObjectName("inputEmail")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.inputEmail)
        self.lblAlamat = QtWidgets.QLabel(self.dataFrame)
        self.lblAlamat.setStyleSheet("font-size: 14px; font-weight: bold; color: #666;")
        self.lblAlamat.setObjectName("lblAlamat")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.lblAlamat)
        self.inputAlamat = QtWidgets.QTextEdit(self.dataFrame)
        self.inputAlamat.setMinimumSize(QtCore.QSize(0, 80))
        self.inputAlamat.setMaximumSize(QtCore.QSize(16777215, 80))
        self.inputAlamat.setStyleSheet("\n"
"QTextEdit {\n"
"    border: 2px solid #ddd;\n"
"    border-radius: 5px;\n"
"    padding: 8px 12px;\n"
"    background-color: white;\n"
"    font-size: 14px;\n"
"}\n"
"QTextEdit:focus {\n"
"    border-color: #750003;\n"
"}\n"
"                ")
        self.inputAlamat.setObjectName("inputAlamat")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.inputAlamat)
        self.verticalLayout_4.addLayout(self.formLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.btnBatal = QtWidgets.QPushButton(self.dataFrame)
        self.btnBatal.setMinimumSize(QtCore.QSize(120, 40))
        self.btnBatal.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: #ddd;\n"
"    color: #333;\n"
"    border-radius: 5px;\n"
"    padding: 10px 20px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #ccc;\n"
"}\n"
"                ")
        self.btnBatal.setObjectName("btnBatal")
        self.horizontalLayout_2.addWidget(self.btnBatal)
        self.btnSimpan = QtWidgets.QPushButton(self.dataFrame)
        self.btnSimpan.setMinimumSize(QtCore.QSize(120, 40))
        self.btnSimpan.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: #750003;\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 10px 20px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5a0002;\n"
"}\n"
"                ")
        self.btnSimpan.setObjectName("btnSimpan")
        self.horizontalLayout_2.addWidget(self.btnSimpan)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addWidget(self.dataFrame)
        self.scrollArea.setWidget(self.scrollContent)
        self.verticalLayout.addWidget(self.scrollArea)
        ProfilDonor.setCentralWidget(self.centralwidget)

        self.retranslateUi(ProfilDonor)
        QtCore.QMetaObject.connectSlotsByName(ProfilDonor)

    def retranslateUi(self, ProfilDonor):
        _translate = QtCore.QCoreApplication.translate
        ProfilDonor.setWindowTitle(_translate("ProfilDonor", "Profil Pendonor - PMI"))
        self.logoLabel.setText(_translate("ProfilDonor", "PMI DONOR DARAH"))
        self.btnDashboard.setText(_translate("ProfilDonor", "Dashboard"))
        self.btnPendaftaran.setText(_translate("ProfilDonor", "Pendaftaran Donor"))
        self.btnJadwal.setText(_translate("ProfilDonor", "Jadwal Donor"))
        self.btnProfil.setText(_translate("ProfilDonor", "👤"))
        self.pageTitle.setText(_translate("ProfilDonor", "Profil Pendonor"))
        self.photoLabel.setText(_translate("ProfilDonor", "👤"))
        self.btnGantiFoto.setText(_translate("ProfilDonor", "Ganti Foto"))
        self.lblDataPribadi.setText(_translate("ProfilDonor", "Data Pribadi"))
        self.lblNama.setText(_translate("ProfilDonor", "Nama Lengkap"))
        self.inputNama.setText(_translate("ProfilDonor", "Ahmad Rifai"))
        self.lblNIK.setText(_translate("ProfilDonor", "NIK"))
        self.inputNIK.setText(_translate("ProfilDonor", "3507012345678901"))
        self.lblTglLahir.setText(_translate("ProfilDonor", "Tanggal Lahir"))
        self.inputTglLahir.setText(_translate("ProfilDonor", "15 Januari 1995"))
        self.lblJenisKelamin.setText(_translate("ProfilDonor", "Jenis Kelamin"))
        self.inputJenisKelamin.setText(_translate("ProfilDonor", "Laki-laki"))
        self.lblGolDarah.setText(_translate("ProfilDonor", "Golongan Darah"))
        self.inputGolDarah.setText(_translate("ProfilDonor", "O+"))
        self.lblTelepon.setText(_translate("ProfilDonor", "No. Telepon"))
        self.inputTelepon.setText(_translate("ProfilDonor", "081234567890"))
        self.lblEmail.setText(_translate("ProfilDonor", "Email"))
        self.inputEmail.setText(_translate("ProfilDonor", "ahmadrifai@email.com"))
        self.lblAlamat.setText(_translate("ProfilDonor", "Alamat"))
        self.inputAlamat.setHtml(_translate("ProfilDonor", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Jl. Soekarno Hatta No. 123, Malang, Jawa Timur 65141</p></body></html>"))
        self.btnBatal.setText(_translate("ProfilDonor", "Batal"))
        self.btnSimpan.setText(_translate("ProfilDonor", "Simpan Perubahan"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ProfilDonor = QtWidgets.QMainWindow()
    ui = Ui_ProfilDonor()
    ui.setupUi(ProfilDonor)
    ProfilDonor.show()
    sys.exit(app.exec_())
