# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'daftardonor.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from TRANSAKSI import PendaftaranDonor


class Ui_PendaftaranDonor(object):
    def setupUi(self, PendaftaranDonor):
        self.window = PendaftaranDonor
        self.id_pendonor = None
        PendaftaranDonor.setObjectName("PendaftaranDonor")
        PendaftaranDonor.resize(1200, 800)
        PendaftaranDonor.setStyleSheet("\n"
"QMainWindow {\n"
"    background-color: #f5f5f5;\n"
"}\n"
"QPushButton {\n"
"    border: none;\n"
"    padding: 10px 20px;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    opacity: 0.8;\n"
"}\n"
"QFrame {\n"
"    border-radius: 10px;\n"
"}\n"
"QLabel {\n"
"    color: #333333;\n"
"}\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(PendaftaranDonor)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.navbar = QtWidgets.QFrame(self.centralwidget)
        self.navbar.setMinimumSize(QtCore.QSize(0, 70))
        self.navbar.setMaximumSize(QtCore.QSize(16777215, 70))
        self.navbar.setStyleSheet("\n"
"QFrame#navbar {\n"
"    background-color: #750003;\n"
"}\n"
"QPushButton {\n"
"    color: white;\n"
"    background-color: transparent;\n"
"    text-align: left;\n"
"    padding: 15px 25px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.1);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 0.2);\n"
"}\n"
"       ")
        self.navbar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.navbar.setObjectName("navbar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.navbar)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logoLabel = QtWidgets.QLabel(self.navbar)
        self.logoLabel.setMinimumSize(QtCore.QSize(200, 0))
        self.logoLabel.setStyleSheet("color: white; font-size: 18px; font-weight: bold; padding-left: 20px;")
        self.logoLabel.setObjectName("logoLabel")
        self.horizontalLayout.addWidget(self.logoLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnDashboard = QtWidgets.QPushButton(self.navbar)
        self.btnDashboard.setMinimumSize(QtCore.QSize(120, 0))
        self.btnDashboard.setObjectName("btnDashboard")
        self.horizontalLayout.addWidget(self.btnDashboard)
        self.btnPendaftaran = QtWidgets.QPushButton(self.navbar)
        self.btnPendaftaran.setMinimumSize(QtCore.QSize(170, 0))
        self.btnPendaftaran.setObjectName("btnPendaftaran")
        self.horizontalLayout.addWidget(self.btnPendaftaran)
        self.btnJadwal = QtWidgets.QPushButton(self.navbar)
        self.btnJadwal.setMinimumSize(QtCore.QSize(130, 0))
        self.btnJadwal.setObjectName("btnJadwal")
        self.horizontalLayout.addWidget(self.btnJadwal)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btnProfil = QtWidgets.QPushButton(self.navbar)
        self.btnProfil.setMinimumSize(QtCore.QSize(50, 50))
        self.btnProfil.setMaximumSize(QtCore.QSize(50, 50))
        self.btnProfil.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: white;\n"
"    border-radius: 25px; \n"
"    min-width: 50px;\n"
"    max-width: 50px;\n"
"    min-height: 50px;\n"
"    max-height: 50px;\n"
"    padding: 0px; \n"
"    font-size: 24px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.9);\n"
"}\n"
"          ")
        self.btnProfil.setObjectName("btnProfil")
        self.horizontalLayout.addWidget(self.btnProfil)
        self.verticalLayout.addWidget(self.navbar)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setStyleSheet("QScrollArea { border: none; background-color: #f5f5f5; }")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollContent = QtWidgets.QWidget()
        self.scrollContent.setGeometry(QtCore.QRect(0, 0, 1187, 900))
        self.scrollContent.setObjectName("scrollContent")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollContent)
        self.verticalLayout_2.setContentsMargins(30, 30, 30, 30)
        self.verticalLayout_2.setSpacing(25)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.titleLabel = QtWidgets.QLabel(self.scrollContent)
        self.titleLabel.setStyleSheet("font-size: 28px; font-weight: bold; color: #750003;")
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout_2.addWidget(self.titleLabel)
        self.subtitleLabel = QtWidgets.QLabel(self.scrollContent)
        self.subtitleLabel.setStyleSheet("font-size: 14px; color: #666;")
        self.subtitleLabel.setObjectName("subtitleLabel")
        self.verticalLayout_2.addWidget(self.subtitleLabel)
        self.formFrame = QtWidgets.QFrame(self.scrollContent)
        self.formFrame.setStyleSheet("\n"
"QFrame#formFrame {\n"
"    background-color: white;\n"
"    border: 2px solid #750003;\n"
"    padding: 30px;\n"
"}\n"
"QLabel {\n"
"    color: #333333;\n"
"    font-size: 14px;\n"
"}\n"
"QLineEdit, QComboBox, QDateEdit, QTextEdit {\n"
"    padding: 10px;\n"
"    border: 1px solid #ddd;\n"
"    border-radius: 5px;\n"
"    background-color: white;\n"
"    font-size: 14px;\n"
"}\n"
"QLineEdit:focus, QComboBox:focus, QDateEdit:focus, QTextEdit:focus {\n"
"    border: 2px solid #750003;\n"
"}\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"    padding-right: 10px;\n"
"}\n"
"           ")
        self.formFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.formFrame.setObjectName("formFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.formFrame)
        self.verticalLayout_3.setSpacing(20)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.sectionData = QtWidgets.QLabel(self.formFrame)
        self.sectionData.setStyleSheet("font-size: 18px; font-weight: bold; color: #750003; margin-top: 10px;")
        self.sectionData.setObjectName("sectionData")
        self.verticalLayout_3.addWidget(self.sectionData)
        self.rowNamaEmail = QtWidgets.QHBoxLayout()
        self.rowNamaEmail.setSpacing(20)
        self.rowNamaEmail.setObjectName("rowNamaEmail")
        self.colNama = QtWidgets.QVBoxLayout()
        self.colNama.setObjectName("colNama")
        self.lblNama = QtWidgets.QLabel(self.formFrame)
        self.lblNama.setObjectName("lblNama")
        self.colNama.addWidget(self.lblNama)
        self.inputNama = QtWidgets.QLineEdit(self.formFrame)
        self.inputNama.setObjectName("inputNama")
        self.colNama.addWidget(self.inputNama)
        self.rowNamaEmail.addLayout(self.colNama)
        self.colEmail = QtWidgets.QVBoxLayout()
        self.colEmail.setObjectName("colEmail")
        self.lblEmail = QtWidgets.QLabel(self.formFrame)
        self.lblEmail.setObjectName("lblEmail")
        self.colEmail.addWidget(self.lblEmail)
        self.inputEmail = QtWidgets.QLineEdit(self.formFrame)
        self.inputEmail.setObjectName("inputEmail")
        self.colEmail.addWidget(self.inputEmail)
        self.rowNamaEmail.addLayout(self.colEmail)
        self.verticalLayout_3.addLayout(self.rowNamaEmail)
        self.rowNIKTelepon = QtWidgets.QHBoxLayout()
        self.rowNIKTelepon.setSpacing(20)
        self.rowNIKTelepon.setObjectName("rowNIKTelepon")
        self.colNIK = QtWidgets.QVBoxLayout()
        self.colNIK.setObjectName("colNIK")
        self.lblNIK = QtWidgets.QLabel(self.formFrame)
        self.lblNIK.setObjectName("lblNIK")
        self.colNIK.addWidget(self.lblNIK)
        self.inputNIK = QtWidgets.QLineEdit(self.formFrame)
        self.inputNIK.setMaxLength(16)
        self.inputNIK.setObjectName("inputNIK")
        self.colNIK.addWidget(self.inputNIK)
        self.rowNIKTelepon.addLayout(self.colNIK)
        self.colTelepon = QtWidgets.QVBoxLayout()
        self.colTelepon.setObjectName("colTelepon")
        self.lblTelepon = QtWidgets.QLabel(self.formFrame)
        self.lblTelepon.setObjectName("lblTelepon")
        self.colTelepon.addWidget(self.lblTelepon)
        self.inputTelepon = QtWidgets.QLineEdit(self.formFrame)
        self.inputTelepon.setObjectName("inputTelepon")
        self.colTelepon.addWidget(self.inputTelepon)
        self.rowNIKTelepon.addLayout(self.colTelepon)
        self.verticalLayout_3.addLayout(self.rowNIKTelepon)
        self.rowTanggalJenisKelamin = QtWidgets.QHBoxLayout()
        self.rowTanggalJenisKelamin.setSpacing(20)
        self.rowTanggalJenisKelamin.setObjectName("rowTanggalJenisKelamin")
        self.colTanggal = QtWidgets.QVBoxLayout()
        self.colTanggal.setObjectName("colTanggal")
        self.lblTanggalLahir = QtWidgets.QLabel(self.formFrame)
        self.lblTanggalLahir.setObjectName("lblTanggalLahir")
        self.colTanggal.addWidget(self.lblTanggalLahir)
        self.inputTanggalLahir = QtWidgets.QDateEdit(self.formFrame)
        self.inputTanggalLahir.setCalendarPopup(True)
        self.inputTanggalLahir.setObjectName("inputTanggalLahir")
        self.colTanggal.addWidget(self.inputTanggalLahir)
        self.rowTanggalJenisKelamin.addLayout(self.colTanggal)
        self.colJenisKelamin = QtWidgets.QVBoxLayout()
        self.colJenisKelamin.setObjectName("colJenisKelamin")
        self.lblJenisKelamin = QtWidgets.QLabel(self.formFrame)
        self.lblJenisKelamin.setObjectName("lblJenisKelamin")
        self.colJenisKelamin.addWidget(self.lblJenisKelamin)
        self.inputJenisKelamin = QtWidgets.QComboBox(self.formFrame)
        self.inputJenisKelamin.setObjectName("inputJenisKelamin")
        self.inputJenisKelamin.addItem("")
        self.inputJenisKelamin.addItem("")
        self.inputJenisKelamin.addItem("")
        self.colJenisKelamin.addWidget(self.inputJenisKelamin)
        self.rowTanggalJenisKelamin.addLayout(self.colJenisKelamin)
        self.verticalLayout_3.addLayout(self.rowTanggalJenisKelamin)
        self.colAlamat = QtWidgets.QVBoxLayout()
        self.colAlamat.setObjectName("colAlamat")
        self.lblAlamat = QtWidgets.QLabel(self.formFrame)
        self.lblAlamat.setObjectName("lblAlamat")
        self.colAlamat.addWidget(self.lblAlamat)
        self.inputAlamat = QtWidgets.QTextEdit(self.formFrame)
        self.inputAlamat.setMaximumSize(QtCore.QSize(16777215, 80))
        self.inputAlamat.setObjectName("inputAlamat")
        self.colAlamat.addWidget(self.inputAlamat)
        self.verticalLayout_3.addLayout(self.colAlamat)
        self.sectionKesehatan = QtWidgets.QLabel(self.formFrame)
        self.sectionKesehatan.setStyleSheet("font-size: 18px; font-weight: bold; color: #750003; margin-top: 20px;")
        self.sectionKesehatan.setObjectName("sectionKesehatan")
        self.verticalLayout_3.addWidget(self.sectionKesehatan)
        self.rowGolDarahBerat = QtWidgets.QHBoxLayout()
        self.rowGolDarahBerat.setSpacing(20)
        self.rowGolDarahBerat.setObjectName("rowGolDarahBerat")
        self.colGolDarah = QtWidgets.QVBoxLayout()
        self.colGolDarah.setObjectName("colGolDarah")
        self.lblGolDarah = QtWidgets.QLabel(self.formFrame)
        self.lblGolDarah.setObjectName("lblGolDarah")
        self.colGolDarah.addWidget(self.lblGolDarah)
        self.inputGolDarah = QtWidgets.QComboBox(self.formFrame)
        self.inputGolDarah.setObjectName("inputGolDarah")
        self.inputGolDarah.addItem("")
        self.inputGolDarah.addItem("")
        self.inputGolDarah.addItem("")
        self.inputGolDarah.addItem("")
        self.inputGolDarah.addItem("")
        self.inputGolDarah.addItem("")
        self.inputGolDarah.addItem("")
        self.inputGolDarah.addItem("")
        self.inputGolDarah.addItem("")
        self.colGolDarah.addWidget(self.inputGolDarah)
        self.rowGolDarahBerat.addLayout(self.colGolDarah)
        self.colBerat = QtWidgets.QVBoxLayout()
        self.colBerat.setObjectName("colBerat")
        self.lblBerat = QtWidgets.QLabel(self.formFrame)
        self.lblBerat.setObjectName("lblBerat")
        self.colBerat.addWidget(self.lblBerat)
        self.inputBerat = QtWidgets.QLineEdit(self.formFrame)
        self.inputBerat.setObjectName("inputBerat")
        self.colBerat.addWidget(self.inputBerat)
        self.rowGolDarahBerat.addLayout(self.colBerat)
        self.verticalLayout_3.addLayout(self.rowGolDarahBerat)
        self.colRiwayat = QtWidgets.QVBoxLayout()
        self.colRiwayat.setObjectName("colRiwayat")
        self.lblRiwayat = QtWidgets.QLabel(self.formFrame)
        self.lblRiwayat.setObjectName("lblRiwayat")
        self.colRiwayat.addWidget(self.lblRiwayat)
        self.inputRiwayat = QtWidgets.QTextEdit(self.formFrame)
        self.inputRiwayat.setMaximumSize(QtCore.QSize(16777215, 80))
        self.inputRiwayat.setObjectName("inputRiwayat")
        self.colRiwayat.addWidget(self.inputRiwayat)
        self.verticalLayout_3.addLayout(self.colRiwayat)
        self.infoFrame = QtWidgets.QFrame(self.formFrame)
        self.infoFrame.setStyleSheet("\n"
"QFrame#infoFrame {\n"
"    background-color: #fff3cd;\n"
"    border: 1px solid #ffc107;\n"
"    border-radius: 8px;\n"
"    padding: 15px;\n"
"}\n"
"              ")
        self.infoFrame.setObjectName("infoFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.infoFrame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.iconInfo = QtWidgets.QLabel(self.infoFrame)
        self.iconInfo.setStyleSheet("font-size: 24px; border: none;")
        self.iconInfo.setObjectName("iconInfo")
        self.horizontalLayout_2.addWidget(self.iconInfo)
        self.textInfo = QtWidgets.QLabel(self.infoFrame)
        self.textInfo.setStyleSheet("font-size: 13px; color: #856404; border: none;")
        self.textInfo.setWordWrap(True)
        self.textInfo.setObjectName("textInfo")
        self.horizontalLayout_2.addWidget(self.textInfo)
        self.verticalLayout_3.addWidget(self.infoFrame)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonLayout.addItem(spacerItem2)
        self.btnBatal = QtWidgets.QPushButton(self.formFrame)
        self.btnBatal.setMinimumSize(QtCore.QSize(150, 45))
        self.btnBatal.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: #6c757d;\n"
"    color: white;\n"
"    font-size: 15px;\n"
"    padding: 12px 30px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5a6268;\n"
"}\n"
"                ")
        self.btnBatal.setObjectName("btnBatal")
        self.buttonLayout.addWidget(self.btnBatal)
        self.btnDaftar = QtWidgets.QPushButton(self.formFrame)
        self.btnDaftar.setMinimumSize(QtCore.QSize(150, 45))
        self.btnDaftar.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: #750003;\n"
"    color: white;\n"
"    font-size: 15px;\n"
"    padding: 12px 30px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5a0002;\n"
"}\n"
"                ")
        self.btnDaftar.setObjectName("btnDaftar")
        self.buttonLayout.addWidget(self.btnDaftar)
        self.verticalLayout_3.addLayout(self.buttonLayout)
        self.verticalLayout_2.addWidget(self.formFrame)
        self.scrollArea.setWidget(self.scrollContent)
        self.verticalLayout.addWidget(self.scrollArea)
        PendaftaranDonor.setCentralWidget(self.centralwidget)
        self.btnDashboard.clicked.connect(self.balik_dashboard)
        self.btnJadwal.clicked.connect(self.masuk_jadwal_donor)
        self.btnDaftar.clicked.connect(self.daftar_donor)

        self.retranslateUi(PendaftaranDonor)
        QtCore.QMetaObject.connectSlotsByName(PendaftaranDonor)
        
    def set_pendonor(self, id_pendonor):
        self.id_pendonor = id_pendonor
        
    def balik_dashboard(self):
        import dasboardpendonor
        self.dashboardWindow = QtWidgets.QMainWindow()
        self.dashboardUI = dasboardpendonor.Ui_DonorDashboard()
        self.dashboardUI.setupUi(self.dashboardWindow)
        self.dashboardUI.set_pendonor(self.id_pendonor)
        self.dashboardWindow.show()
        self.window.close()
    
    def masuk_jadwal_donor(self):
        import jadwal
        self.jadwal_window = QtWidgets.QMainWindow()
        self.jadwal_ui = jadwal.Ui_JadwalDonor()
        self.jadwal_ui.setupUi(self.jadwal_window)
        self.jadwal_ui.set_pendonor(self.id_pendonor)
        self.jadwal_window.show()
        self.window.close()
        
    def daftar_donor(self):
        if not self.id_pendonor:
            QMessageBox.warning(
                self.window,
                "Error",
                "Anda belum login sebagai pendonor."
            )
            return

        berat = self.inputBerat.text().strip()

        # validasi input
        if not berat.isdigit():
            QMessageBox.warning(
                self.window,
                "Error",
                "Berat badan harus berupa angka."
            )
            return

        berat = int(berat)

        if berat < 45:
            QMessageBox.warning(
                self.window,
                "Error",
                "Berat badan minimal 45 kg."
            )
            return

        # simpan ke database
        db = PendaftaranDonor()

        # cek apakah masih ada pendaftaran aktif
        if db.cek_daftar_aktif(self.id_pendonor) > 0:
            QMessageBox.information(
                self.window,
                "Info",
                "Anda sudah memiliki pendaftaran donor yang menunggu."
            )
            return

        db.simpan_pendaftaran(self.id_pendonor, berat)

        QMessageBox.information(
            self.window,
            "Berhasil",
            "Pendaftaran donor berhasil dikirim.\nSilakan menunggu konfirmasi PMI."
        )

        # optional: reset form
        self.inputBerat.clear()
        self.inputRiwayat.clear()


    def retranslateUi(self, PendaftaranDonor):
        _translate = QtCore.QCoreApplication.translate
        PendaftaranDonor.setWindowTitle(_translate("PendaftaranDonor", "Pendaftaran Donor - PMI"))
        self.logoLabel.setText(_translate("PendaftaranDonor", "PMI DONOR DARAH"))
        self.btnDashboard.setText(_translate("PendaftaranDonor", "Dashboard"))
        self.btnPendaftaran.setText(_translate("PendaftaranDonor", "Pendaftaran Donor"))
        self.btnJadwal.setText(_translate("PendaftaranDonor", "Jadwal Donor"))
        self.btnProfil.setText(_translate("PendaftaranDonor", "👤"))
        self.titleLabel.setText(_translate("PendaftaranDonor", "Pendaftaran Donor Darah"))
        self.subtitleLabel.setText(_translate("PendaftaranDonor", "Isi formulir di bawah ini untuk mendaftar sebagai pendonor darah"))
        self.sectionData.setText(_translate("PendaftaranDonor", "Data Pribadi"))
        self.lblNama.setText(_translate("PendaftaranDonor", "Nama Lengkap *"))
        self.inputNama.setPlaceholderText(_translate("PendaftaranDonor", "Masukkan nama lengkap"))
        self.lblEmail.setText(_translate("PendaftaranDonor", "Email *"))
        self.inputEmail.setPlaceholderText(_translate("PendaftaranDonor", "contoh@email.com"))
        self.lblNIK.setText(_translate("PendaftaranDonor", "NIK *"))
        self.inputNIK.setPlaceholderText(_translate("PendaftaranDonor", "16 digit NIK"))
        self.lblTelepon.setText(_translate("PendaftaranDonor", "No. Telepon *"))
        self.inputTelepon.setPlaceholderText(_translate("PendaftaranDonor", "08xx-xxxx-xxxx"))
        self.lblTanggalLahir.setText(_translate("PendaftaranDonor", "Tanggal Lahir *"))
        self.inputTanggalLahir.setDisplayFormat(_translate("PendaftaranDonor", "dd/MM/yyyy"))
        self.lblJenisKelamin.setText(_translate("PendaftaranDonor", "Jenis Kelamin *"))
        self.inputJenisKelamin.setItemText(0, _translate("PendaftaranDonor", "Pilih jenis kelamin"))
        self.inputJenisKelamin.setItemText(1, _translate("PendaftaranDonor", "Laki-laki"))
        self.inputJenisKelamin.setItemText(2, _translate("PendaftaranDonor", "Perempuan"))
        self.lblAlamat.setText(_translate("PendaftaranDonor", "Alamat Lengkap *"))
        self.inputAlamat.setPlaceholderText(_translate("PendaftaranDonor", "Jalan, RT/RW, Kelurahan, Kecamatan, Kota"))
        self.sectionKesehatan.setText(_translate("PendaftaranDonor", "Data Kesehatan"))
        self.lblGolDarah.setText(_translate("PendaftaranDonor", "Golongan Darah *"))
        self.inputGolDarah.setItemText(0, _translate("PendaftaranDonor", "Pilih golongan darah"))
        self.inputGolDarah.setItemText(1, _translate("PendaftaranDonor", "A+"))
        self.inputGolDarah.setItemText(2, _translate("PendaftaranDonor", "A-"))
        self.inputGolDarah.setItemText(3, _translate("PendaftaranDonor", "B+"))
        self.inputGolDarah.setItemText(4, _translate("PendaftaranDonor", "B-"))
        self.inputGolDarah.setItemText(5, _translate("PendaftaranDonor", "AB+"))
        self.inputGolDarah.setItemText(6, _translate("PendaftaranDonor", "AB-"))
        self.inputGolDarah.setItemText(7, _translate("PendaftaranDonor", "O+"))
        self.inputGolDarah.setItemText(8, _translate("PendaftaranDonor", "O-"))
        self.lblBerat.setText(_translate("PendaftaranDonor", "Berat Badan (kg) *"))
        self.inputBerat.setPlaceholderText(_translate("PendaftaranDonor", "Minimal 45 kg"))
        self.lblRiwayat.setText(_translate("PendaftaranDonor", "Riwayat Penyakit"))
        self.inputRiwayat.setPlaceholderText(_translate("PendaftaranDonor", "Tuliskan riwayat penyakit jika ada (opsional)"))
        self.iconInfo.setText(_translate("PendaftaranDonor", "ℹ️"))
        self.textInfo.setText(_translate("PendaftaranDonor", "Pastikan Anda telah makan dan minum yang cukup sebelum donor. Bawa KTP/identitas saat datang."))
        self.btnBatal.setText(_translate("PendaftaranDonor", "Batal"))
        self.btnDaftar.setText(_translate("PendaftaranDonor", "Daftar Sekarang"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PendaftaranDonor = QtWidgets.QMainWindow()
    ui = Ui_PendaftaranDonor()
    ui.setupUi(PendaftaranDonor)
    PendaftaranDonor.show()
    sys.exit(app.exec_())
