# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signup.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(552, 704)
        Dialog.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    font-size: 14px;\n"
"    font-weight: 500;\n"
"    letter-spacing: 0.5px;\n"
"}\n"
"\n"
"/* Hilangkan underline & warna biru pada QLabel */\n"
"QLabel {\n"
"    text-decoration: none;\n"
"    color: white;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background: rgba(255,255,255,0.9);\n"
"    border: 2px solid transparent;\n"
"    border-radius: 12px;\n"
"    padding: 10px 14px;\n"
"    font-size: 16px;\n"
"\n"
"    /* simple shadow */\n"
"    box-shadow: 0px 4px 12px rgba(0,0,0,0.35);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #D50000;\n"
"    background: rgba(255,255,255,1);\n"
"    box-shadow: 0px 6px 18px rgba(0,0,0,0.45);\n"
"}\n"
"\n"
"/* ====== PUSH BUTTON (Login, Daftar, dll) ====== */\n"
"QPushButton {\n"
"    background-color: #D50000;\n"
"    color: white;\n"
"    border-radius: 14px;\n"
"    padding: 12px 20px;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"\n"
"    /* Drop shadow simple */\n"
"    box-shadow: 0px 4px 10px rgba(0,0,0,0.35);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #b40000;\n"
"    box-shadow: 0px 6px 14px rgba(0,0,0,0.45);\n"
"}\n"
"#pushButton {\n"
"    background-color: #D50000;\n"
"    color: white;\n"
"    border-radius: 14px;\n"
"    padding: 12px 20px;\n"
"    border: none;\n"
"    font-size: 17px;\n"
"    font-weight: bold;\n"
"\n"
"    /* Shadow */\n"
"    box-shadow: 0px 5px 16px rgba(0,0,0,0.40);\n"
"}\n"
"\n"
"#pushButton:hover {\n"
"    background-color: #b40000;\n"
"    box-shadow: 0px 7px 20px rgba(0,0,0,0.50);\n"
"    letter-spacing: 1px; /* efek modern */\n"
"}\n"
"\n"
"#pushButton:pressed {\n"
"    background-color: #8e0000;\n"
"    box-shadow: 0px 3px 10px rgba(0,0,0,0.30);\n"
"    padding-top: 14px;\n"
"    padding-bottom: 10px;\n"
"}\n"
"\n"
"#pushButton_2 {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: #1E88E5;\n"
"    font-size: 16px;\n"
"    text-decoration: underline;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"#pushButton_2:hover {\n"
"    color: #64B5F6;\n"
"    cursor: pointer;\n"
"    text-decoration: underline;\n"
"    letter-spacing: 0.5px;\n"
"}\n"
"\n"
"#pushButton_2:pressed {\n"
"    color: #0D47A1;\n"
"}\n"
"")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(15, 5, 526, 676))
        self.label_3.setStyleSheet("QLabel {\n"
"    border-image: url(:/gambar/pexels-charliehelenrobinson-4531306.jpg);\n"
"    background-color: rgba(60, 0, 0, 110);\n"
"    border-radius: 20px;\n"
"}\n"
"")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(15, 5, 526, 676))
        self.label_4.setStyleSheet("QLabel {\n"
"    background-color: rgba(0, 0, 0, 150);\n"
"    border-radius: 20px;\n"
"}\n"
"")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(15, 5, 526, 676))
        self.label_5.setStyleSheet("QLabel {\n"
"    background-color: rgba(60, 0, 0, 110);\n"
"    border-radius: 20px;\n"
"}\n"
"")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(180, 45, 231, 96))
        self.label_9.setStyleSheet("border-image: url(:/gambar/pngtree-indonesian-red-cross-pmi-logo-vector-png-image_12258331.png);")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(100, 220, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(62)
        font.setStrikeOut(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(105, 245, 366, 41))
        self.lineEdit.setStyleSheet("background-color: rgba(0, 0, 0, 0.50);")
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(105, 295, 76, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(62)
        font.setStrikeOut(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(105, 385, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(62)
        font.setStrikeOut(False)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(115, 325, 361, 41))
        self.lineEdit_2.setStyleSheet("background-color: rgba(0, 0, 0, 0.50);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(100, 240, 366, 41))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_4.setGeometry(QtCore.QRect(105, 320, 366, 41))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_5.setGeometry(QtCore.QRect(110, 415, 361, 41))
        self.lineEdit_5.setStyleSheet("background-color: rgba(0, 0, 0, 0.50);")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_6.setGeometry(QtCore.QRect(105, 410, 361, 41))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(105, 495, 361, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(190, 545, 136, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(62)
        font.setStrikeOut(False)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(300, 530, 86, 46))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(250, 160, 116, 26))
        self.label_6.setStyleSheet("#label_6 {\n"
"    color: #FFFFFF;\n"
"    font-size: 23px;\n"
"    font-weight: 700;\n"
"    letter-spacing: 1px;\n"
"    text-transform: uppercase;\n"
"\n"
"    /* Shadow agar terlihat jelas di background */\n"
"    text-shadow: 0px 4px 12px rgba(0, 0, 0, 0.45);\n"
"}\n"
"")
        self.label_6.setObjectName("label_6")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Username:"))
        self.label_2.setText(_translate("Dialog", "Email:"))
        self.label_7.setText(_translate("Dialog", "Password:"))
        self.pushButton.setText(_translate("Dialog", "Daftar"))
        self.label_8.setText(_translate("Dialog", "Sudah Punya Akun?"))
        self.pushButton_2.setText(_translate("Dialog", "Login"))
        self.label_6.setText(_translate("Dialog", "SIGN UP"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
