# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signin.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QMainWindow 
from USER import register_pendonor
from login_pendonor import Ui_LoginWindow


class Ui_SignUpWindow(object):
    def setupUi(self, SignUpWindow):
        self.registwindow = None
        SignUpWindow.setObjectName("SignUpWindow")
        SignUpWindow.resize(1100, 700)
        SignUpWindow.setStyleSheet("\n"
"QMainWindow {\n"
"    background-color: #f5f5f5;\n"
"}\n"
"QPushButton {\n"
"    border: none;\n"
"    padding: 10px 20px;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    opacity: 0.8;\n"
"}\n"
"QFrame {\n"
"    border-radius: 10px;\n"
"}\n"
"QLabel {\n"
"    color: #333333;\n"
"}\n"
"QLineEdit, QComboBox, QDateEdit {\n"
"    padding: 12px 15px;\n"
"    border: 2px solid #ddd;\n"
"    border-radius: 8px;\n"
"    font-size: 14px;\n"
"    background-color: white;\n"
"}\n"
"QLineEdit:focus, QComboBox:focus, QDateEdit:focus {\n"
"    border: 2px solid #750003;\n"
"}\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(SignUpWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.mainLayout.setContentsMargins(0, 0, 0, 0)
        self.mainLayout.setSpacing(0)
        self.mainLayout.setObjectName("mainLayout")
        self.leftPanel = QtWidgets.QFrame(self.centralwidget)
        self.leftPanel.setMinimumSize(QtCore.QSize(420, 0))
        self.leftPanel.setMaximumSize(QtCore.QSize(420, 16777215))
        self.leftPanel.setStyleSheet("\n"
"QFrame#leftPanel {\n"
"    background-color: #750003;\n"
"}\n"
"QLabel {\n"
"    color: white;\n"
"}\n"
"       ")
        self.leftPanel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftPanel.setObjectName("leftPanel")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.leftPanel)
        self.verticalLayout.setContentsMargins(40, 60, 40, 60)
        self.verticalLayout.setSpacing(25)
        self.verticalLayout.setObjectName("verticalLayout")
        self.logoIcon = QtWidgets.QLabel(self.leftPanel)
        self.logoIcon.setStyleSheet("font-size: 70px;")
        self.logoIcon.setAlignment(QtCore.Qt.AlignCenter)
        self.logoIcon.setObjectName("logoIcon")
        self.verticalLayout.addWidget(self.logoIcon)
        self.appTitle = QtWidgets.QLabel(self.leftPanel)
        self.appTitle.setStyleSheet("font-size: 28px; font-weight: bold;")
        self.appTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.appTitle.setObjectName("appTitle")
        self.verticalLayout.addWidget(self.appTitle)
        self.tagline = QtWidgets.QLabel(self.leftPanel)
        self.tagline.setStyleSheet("font-size: 16px; color: rgba(255, 255, 255, 0.9);")
        self.tagline.setAlignment(QtCore.Qt.AlignCenter)
        self.tagline.setObjectName("tagline")
        self.verticalLayout.addWidget(self.tagline)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.benefitFrame = QtWidgets.QFrame(self.leftPanel)
        self.benefitFrame.setStyleSheet("\n"
"QFrame {\n"
"    background-color: rgba(255, 255, 255, 0.1);\n"
"    border-radius: 10px;\n"
"    padding: 20px;\n"
"}\n"
"          ")
        self.benefitFrame.setObjectName("benefitFrame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.benefitFrame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.benefit1 = QtWidgets.QLabel(self.benefitFrame)
        self.benefit1.setStyleSheet("font-size: 14px; margin-bottom: 10px;")
        self.benefit1.setObjectName("benefit1")
        self.verticalLayout_4.addWidget(self.benefit1)
        self.benefit2 = QtWidgets.QLabel(self.benefitFrame)
        self.benefit2.setStyleSheet("font-size: 14px; margin-bottom: 10px;")
        self.benefit2.setObjectName("benefit2")
        self.verticalLayout_4.addWidget(self.benefit2)
        self.benefit3 = QtWidgets.QLabel(self.benefitFrame)
        self.benefit3.setStyleSheet("font-size: 14px; margin-bottom: 10px;")
        self.benefit3.setObjectName("benefit3")
        self.verticalLayout_4.addWidget(self.benefit3)
        self.benefit4 = QtWidgets.QLabel(self.benefitFrame)
        self.benefit4.setStyleSheet("font-size: 14px;")
        self.benefit4.setObjectName("benefit4")
        self.verticalLayout_4.addWidget(self.benefit4)
        self.verticalLayout.addWidget(self.benefitFrame)
        self.mainLayout.addWidget(self.leftPanel)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setStyleSheet("QScrollArea { border: none; background-color: white; }")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollContent = QtWidgets.QWidget()
        self.scrollContent.setGeometry(QtCore.QRect(0, 0, 660, 700))
        self.scrollContent.setObjectName("scrollContent")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollContent)
        self.verticalLayout_2.setContentsMargins(50, 40, 50, 40)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.titleLabel = QtWidgets.QLabel(self.scrollContent)
        self.titleLabel.setStyleSheet("font-size: 26px; font-weight: bold; color: #750003; margin-bottom: 8px;")
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout_2.addWidget(self.titleLabel)
        self.subtitleLabel = QtWidgets.QLabel(self.scrollContent)
        self.subtitleLabel.setStyleSheet("font-size: 14px; color: #666; margin-bottom: 30px;")
        self.subtitleLabel.setObjectName("subtitleLabel")
        self.verticalLayout_2.addWidget(self.subtitleLabel)
        self.nameLayout = QtWidgets.QHBoxLayout()
        self.nameLayout.setSpacing(15)
        self.nameLayout.setObjectName("nameLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lblNamaLengkap = QtWidgets.QLabel(self.scrollContent)
        self.lblNamaLengkap.setStyleSheet("font-size: 13px; font-weight: bold; color: #333; margin-top: 15px; margin-bottom: 8px;")
        self.lblNamaLengkap.setObjectName("lblNamaLengkap")
        self.verticalLayout_5.addWidget(self.lblNamaLengkap)
        self.inputNamaLengkap = QtWidgets.QLineEdit(self.scrollContent)
        self.inputNamaLengkap.setObjectName("inputNamaLengkap")
        self.verticalLayout_5.addWidget(self.inputNamaLengkap)
        self.nameLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_2.addLayout(self.nameLayout)
        self.lblNIK = QtWidgets.QLabel(self.scrollContent)
        self.lblNIK.setStyleSheet("font-size: 13px; font-weight: bold; color: #333; margin-top: 15px; margin-bottom: 8px;")
        self.lblNIK.setObjectName("lblNIK")
        self.verticalLayout_2.addWidget(self.lblNIK)
        self.inputNIK = QtWidgets.QLineEdit(self.scrollContent)
        self.inputNIK.setObjectName("inputNIK")
        self.verticalLayout_2.addWidget(self.inputNIK)
        self.personalLayout = QtWidgets.QHBoxLayout()
        self.personalLayout.setSpacing(15)
        self.personalLayout.setObjectName("personalLayout")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.lblTanggalLahir = QtWidgets.QLabel(self.scrollContent)
        self.lblTanggalLahir.setStyleSheet("font-size: 13px; font-weight: bold; color: #333; margin-top: 15px; margin-bottom: 8px;")
        self.lblTanggalLahir.setObjectName("lblTanggalLahir")
        self.verticalLayout_7.addWidget(self.lblTanggalLahir)
        self.inputTanggalLahir = QtWidgets.QDateEdit(self.scrollContent)
        self.inputTanggalLahir.setCalendarPopup(True)
        self.inputTanggalLahir.setObjectName("inputTanggalLahir")
        self.verticalLayout_7.addWidget(self.inputTanggalLahir)
        self.personalLayout.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.lblGolDarah = QtWidgets.QLabel(self.scrollContent)
        self.lblGolDarah.setStyleSheet("font-size: 13px; font-weight: bold; color: #333; margin-top: 15px; margin-bottom: 8px;")
        self.lblGolDarah.setObjectName("lblGolDarah")
        self.verticalLayout_8.addWidget(self.lblGolDarah)
        self.inputGolDarah = QtWidgets.QComboBox(self.scrollContent)
        self.inputGolDarah.setObjectName("inputGolDarah")
        self.inputGolDarah.addItem("")
        self.inputGolDarah.addItem("")
        self.inputGolDarah.addItem("")
        self.inputGolDarah.addItem("")
        self.inputGolDarah.addItem("")
        self.inputGolDarah.addItem("")
        self.inputGolDarah.addItem("")
        self.inputGolDarah.addItem("")
        self.inputGolDarah.addItem("")
        self.verticalLayout_8.addWidget(self.inputGolDarah)
        self.personalLayout.addLayout(self.verticalLayout_8)
        self.verticalLayout_2.addLayout(self.personalLayout)
        self.lblNoHP = QtWidgets.QLabel(self.scrollContent)
        self.lblNoHP.setStyleSheet("font-size: 13px; font-weight: bold; color: #333; margin-top: 15px; margin-bottom: 8px;")
        self.lblNoHP.setObjectName("lblNoHP")
        self.verticalLayout_2.addWidget(self.lblNoHP)
        self.inputNoHP = QtWidgets.QLineEdit(self.scrollContent)
        self.inputNoHP.setObjectName("inputNoHP")
        self.verticalLayout_2.addWidget(self.inputNoHP)
        self.lblPassword = QtWidgets.QLabel(self.scrollContent)
        self.lblPassword.setStyleSheet("font-size: 13px; font-weight: bold; color: #333; margin-top: 15px; margin-bottom: 8px;")
        self.lblPassword.setObjectName("lblPassword")
        self.verticalLayout_2.addWidget(self.lblPassword)
        self.inputPassword = QtWidgets.QLineEdit(self.scrollContent)
        self.inputPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.inputPassword.setObjectName("inputPassword")
        self.verticalLayout_2.addWidget(self.inputPassword)
        self.lblKonfirmPassword = QtWidgets.QLabel(self.scrollContent)
        self.lblKonfirmPassword.setStyleSheet("font-size: 13px; font-weight: bold; color: #333; margin-top: 15px; margin-bottom: 8px;")
        self.lblKonfirmPassword.setObjectName("lblKonfirmPassword")
        self.verticalLayout_2.addWidget(self.lblKonfirmPassword)
        self.inputKonfirmPassword = QtWidgets.QLineEdit(self.scrollContent)
        self.inputKonfirmPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.inputKonfirmPassword.setObjectName("inputKonfirmPassword")
        self.verticalLayout_2.addWidget(self.inputKonfirmPassword)
        self.checkSetuju = QtWidgets.QCheckBox(self.scrollContent)
        self.checkSetuju.setStyleSheet("\n"
"QCheckBox {\n"
"    font-size: 13px;\n"
"    color: #666;\n"
"    margin-top: 20px;\n"
"}\n"
"QCheckBox::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border: 2px solid #ddd;\n"
"    border-radius: 4px;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #750003;\n"
"    border-color: #750003;\n"
"}\n"
"           ")
        self.checkSetuju.setObjectName("checkSetuju")
        self.verticalLayout_2.addWidget(self.checkSetuju)
        self.btnDaftar = QtWidgets.QPushButton(self.scrollContent)
        self.btnDaftar.setMinimumSize(QtCore.QSize(0, 45))
        self.btnDaftar.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: #750003;\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    margin-top: 20px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #a00004;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #5a0002;\n"
"}\n"
"           ")
        self.btnDaftar.setObjectName("btnDaftar")
        self.verticalLayout_2.addWidget(self.btnDaftar)
        self.loginLayout = QtWidgets.QHBoxLayout()
        self.loginLayout.setContentsMargins(-1, 20, -1, -1)
        self.loginLayout.setObjectName("loginLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.loginLayout.addItem(spacerItem1)
        self.lblSudahPunya = QtWidgets.QLabel(self.scrollContent)
        self.lblSudahPunya.setStyleSheet("font-size: 13px; color: #666;")
        self.lblSudahPunya.setObjectName("lblSudahPunya")
        self.loginLayout.addWidget(self.lblSudahPunya)
        self.btnLogin = QtWidgets.QPushButton(self.scrollContent)
        self.btnLogin.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: transparent;\n"
"    color: #750003;\n"
"    text-decoration: underline;\n"
"    font-size: 13px;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    color: #a00004;\n"
"}\n"
"             ")
        self.btnLogin.setObjectName("btnLogin")
        self.loginLayout.addWidget(self.btnLogin)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.loginLayout.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.loginLayout)
        self.scrollArea.setWidget(self.scrollContent)
        self.mainLayout.addWidget(self.scrollArea)
        SignUpWindow.setCentralWidget(self.centralwidget)
        self.btnDaftar.clicked.connect(self.register)
        self.btnLogin.clicked.connect(self.login_disini)

        self.retranslateUi(SignUpWindow)
        QtCore.QMetaObject.connectSlotsByName(SignUpWindow)
        
    def register(self):
        nama = self.inputNamaLengkap.text()
        nik = self.inputNIK.text()
        tanggal_lahir = self.inputTanggalLahir.date().toString("yyyy-MM-dd")
        gol_darah = self.inputGolDarah.currentText()
        no_hp = self.inputNoHP.text()
        password = self.inputPassword.text()
        konfirm_password = self.inputKonfirmPassword.text()
        setuju = self.checkSetuju.isChecked()
     
        if not nama or not nik or not tanggal_lahir or gol_darah == "Pilih golongan darah" or not no_hp or not password or not konfirm_password:
            QMessageBox.warning(None, "Error", "Semua field wajib diisi.")
            return
        if password != konfirm_password:
                QMessageBox.warning(None, "Error", "Password dan konfirmasi password tidak sesuai.")
                return
        if not setuju:
                QMessageBox.warning(None, "Error", "Anda harus menyetujui syarat dan ketentuan.")
                return
        
        hasil = register_pendonor(nama, nik, tanggal_lahir, gol_darah, no_hp, password)
        if "berhasil" in hasil:
                QMessageBox.information(None, "Sukses", hasil)
                self.loginWindow = QMainWindow()
                self.loginUI = Ui_LoginWindow()
                self.loginUI.setupUi(self.loginWindow)
                self.loginWindow.show()
                self.registwindow.close()
        else:
                QMessageBox.warning(None, "Gagal", hasil)
                
    def login_disini(self):
        self.registwindow = QMainWindow()
        self.registwindow = Ui_SignUpWindow()
        self.registwindow.setupUi(self.registwindow)
        self.registwindow.close()             

    def retranslateUi(self, SignUpWindow):
        _translate = QtCore.QCoreApplication.translate
        SignUpWindow.setWindowTitle(_translate("SignUpWindow", "Daftar - PMI Donor Darah"))
        self.logoIcon.setText(_translate("SignUpWindow", "🩸"))
        self.appTitle.setText(_translate("SignUpWindow", "PMI DONOR DARAH"))
        self.tagline.setText(_translate("SignUpWindow", "Jadilah Pahlawan Kehidupan"))
        self.benefit1.setText(_translate("SignUpWindow", "✓ Jadwal donor yang fleksibel"))
        self.benefit2.setText(_translate("SignUpWindow", "✓ Tracking riwayat donor"))
        self.benefit3.setText(_translate("SignUpWindow", "✓ Dapatkan badge pencapaian"))
        self.benefit4.setText(_translate("SignUpWindow", "✓ Notifikasi jadwal donor"))
        self.titleLabel.setText(_translate("SignUpWindow", "Daftar Akun Baru"))
        self.subtitleLabel.setText(_translate("SignUpWindow", "Lengkapi data diri Anda untuk menjadi donor"))
        self.lblNamaLengkap.setText(_translate("SignUpWindow", "Nama Lengkap *"))
        self.inputNamaLengkap.setPlaceholderText(_translate("SignUpWindow", "Nama Lengkap"))
        self.lblNIK.setText(_translate("SignUpWindow", "NIK (Nomor Induk Kependudukan) *"))
        self.inputNIK.setPlaceholderText(_translate("SignUpWindow", "16 digit NIK"))
        self.lblTanggalLahir.setText(_translate("SignUpWindow", "Tanggal Lahir *"))
        self.lblGolDarah.setText(_translate("SignUpWindow", "Golongan Darah *"))
        self.inputGolDarah.setItemText(0, _translate("SignUpWindow", "Pilih golongan darah"))
        self.inputGolDarah.setItemText(1, _translate("SignUpWindow", "A+"))
        self.inputGolDarah.setItemText(2, _translate("SignUpWindow", "A-"))
        self.inputGolDarah.setItemText(3, _translate("SignUpWindow", "B+"))
        self.inputGolDarah.setItemText(4, _translate("SignUpWindow", "B-"))
        self.inputGolDarah.setItemText(5, _translate("SignUpWindow", "AB+"))
        self.inputGolDarah.setItemText(6, _translate("SignUpWindow", "AB-"))
        self.inputGolDarah.setItemText(7, _translate("SignUpWindow", "O+"))
        self.inputGolDarah.setItemText(8, _translate("SignUpWindow", "O-"))
        self.lblNoHP.setText(_translate("SignUpWindow", "Nomor HP *"))
        self.inputNoHP.setPlaceholderText(_translate("SignUpWindow", "08xxxxxxxxxx"))
        self.lblPassword.setText(_translate("SignUpWindow", "Password *"))
        self.inputPassword.setPlaceholderText(_translate("SignUpWindow", "Minimal 8 karakter"))
        self.lblKonfirmPassword.setText(_translate("SignUpWindow", "Konfirmasi Password *"))
        self.inputKonfirmPassword.setPlaceholderText(_translate("SignUpWindow", "Ulangi password"))
        self.checkSetuju.setText(_translate("SignUpWindow", "Saya setuju dengan syarat dan ketentuan"))
        self.btnDaftar.setText(_translate("SignUpWindow", "Daftar"))
        self.lblSudahPunya.setText(_translate("SignUpWindow", "Sudah punya akun?"))
        self.btnLogin.setText(_translate("SignUpWindow", "Masuk di sini"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SignUpWindow = QtWidgets.QMainWindow()
    ui = Ui_SignUpWindow()
    ui.setupUi(SignUpWindow)
    SignUpWindow.show()
    sys.exit(app.exec_())
