# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dasboardpetugas.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PENDAFTARAN import ( 
        get_pendaftaran_pending,
        update_status_pendaftaran,
        terima_pendaftaran
)



class Ui_MainWindow(object):
    def set_petugas(self, id_user):
        self.id_petugas = id_user
        
    def setupUi(self, MainWindow):
        self.mainwindow = MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        MainWindow.setStyleSheet("\n"
"QMainWindow {\n"
"    background-color: #f5f5f5;\n"
"}\n"
"QPushButton {\n"
"    border: none;\n"
"    padding: 10px 20px;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    opacity: 0.8;\n"
"}\n"
"QFrame {\n"
"    border-radius: 10px;\n"
"}\n"
"QLabel {\n"
"    color: #333333;\n"
"}\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.navbar = QtWidgets.QFrame(self.centralwidget)
        self.navbar.setMinimumSize(QtCore.QSize(0, 70))
        self.navbar.setMaximumSize(QtCore.QSize(16777215, 70))
        self.navbar.setStyleSheet("\n"
"QFrame#navbar {\n"
"    background-color: #750003;\n"
"}\n"
"QPushButton {\n"
"    color: white;\n"
"    background-color: transparent;\n"
"    text-align: left;\n"
"    padding: 15px 25px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.1);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 0.2);\n"
"}\n"
"       ")
        self.navbar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.navbar.setObjectName("navbar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.navbar)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logoLabel = QtWidgets.QLabel(self.navbar)
        self.logoLabel.setMinimumSize(QtCore.QSize(200, 0))
        self.logoLabel.setStyleSheet("color: white; font-size: 18px; font-weight: bold; padding-left: 20px;")
        self.logoLabel.setObjectName("logoLabel")
        self.horizontalLayout.addWidget(self.logoLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnDashboard = QtWidgets.QPushButton(self.navbar)
        self.btnDashboard.setMinimumSize(QtCore.QSize(120, 0))
        self.btnDashboard.setObjectName("btnDashboard")
        self.horizontalLayout.addWidget(self.btnDashboard)
        self.btnTransaksi = QtWidgets.QPushButton(self.navbar)
        self.btnTransaksi.setMinimumSize(QtCore.QSize(150, 0))
        self.btnTransaksi.setObjectName("btnTransaksi")
        self.horizontalLayout.addWidget(self.btnTransaksi)
        self.btnStok = QtWidgets.QPushButton(self.navbar)
        self.btnStok.setMinimumSize(QtCore.QSize(100, 0))
        self.btnStok.setObjectName("btnStok")
        self.horizontalLayout.addWidget(self.btnStok)
        self.btnValidasi = QtWidgets.QPushButton(self.navbar)
        self.btnValidasi.setMinimumSize(QtCore.QSize(180, 0))
        self.btnValidasi.setObjectName("btnValidasi")
        self.horizontalLayout.addWidget(self.btnValidasi)
        self.btnLaporan = QtWidgets.QPushButton(self.navbar)
        self.btnLaporan.setMinimumSize(QtCore.QSize(100, 0))
        self.btnLaporan.setObjectName("btnLaporan")
        self.horizontalLayout.addWidget(self.btnLaporan)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.navbar)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.dashboardPage = QtWidgets.QWidget()
        self.dashboardPage.setObjectName("dashboardPage")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dashboardPage)
        self.verticalLayout_2.setContentsMargins(30, 30, 30, 30)
        self.verticalLayout_2.setSpacing(20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.titleLabel = QtWidgets.QLabel(self.dashboardPage)
        self.titleLabel.setStyleSheet("font-size: 24px; font-weight: bold; color: #750003;")
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout_2.addWidget(self.titleLabel)
        self.statsLayout = QtWidgets.QHBoxLayout()
        self.statsLayout.setSpacing(20)
        self.statsLayout.setObjectName("statsLayout")
        self.cardPendonor = QtWidgets.QFrame(self.dashboardPage)
        self.cardPendonor.setStyleSheet("\n"
"QFrame#cardPendonor {\n"
"    background-color: white;\n"
"    border: 2px solid #750003;\n"
"}\n"
"             ")
        self.cardPendonor.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cardPendonor.setObjectName("cardPendonor")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.cardPendonor)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.iconPendonor = QtWidgets.QLabel(self.cardPendonor)
        self.iconPendonor.setStyleSheet("font-size: 48px; color: #750003;")
        self.iconPendonor.setAlignment(QtCore.Qt.AlignCenter)
        self.iconPendonor.setObjectName("iconPendonor")
        self.verticalLayout_3.addWidget(self.iconPendonor)
        self.lblPendonor = QtWidgets.QLabel(self.cardPendonor)
        self.lblPendonor.setStyleSheet("font-size: 14px; color: #666;")
        self.lblPendonor.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPendonor.setObjectName("lblPendonor")
        self.verticalLayout_3.addWidget(self.lblPendonor)
        self.valuePendonor = QtWidgets.QLabel(self.cardPendonor)
        self.valuePendonor.setStyleSheet("font-size: 36px; font-weight: bold; color: #750003;")
        self.valuePendonor.setAlignment(QtCore.Qt.AlignCenter)
        self.valuePendonor.setObjectName("valuePendonor")
        self.verticalLayout_3.addWidget(self.valuePendonor)
        self.statsLayout.addWidget(self.cardPendonor)
        self.cardKantong = QtWidgets.QFrame(self.dashboardPage)
        self.cardKantong.setStyleSheet("\n"
"QFrame#cardKantong {\n"
"    background-color: white;\n"
"    border: 2px solid #750003;\n"
"}\n"
"             ")
        self.cardKantong.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cardKantong.setObjectName("cardKantong")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.cardKantong)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.iconKantong = QtWidgets.QLabel(self.cardKantong)
        self.iconKantong.setStyleSheet("font-size: 48px; color: #750003;")
        self.iconKantong.setAlignment(QtCore.Qt.AlignCenter)
        self.iconKantong.setObjectName("iconKantong")
        self.verticalLayout_4.addWidget(self.iconKantong)
        self.lblKantong = QtWidgets.QLabel(self.cardKantong)
        self.lblKantong.setStyleSheet("font-size: 14px; color: #666;")
        self.lblKantong.setAlignment(QtCore.Qt.AlignCenter)
        self.lblKantong.setObjectName("lblKantong")
        self.verticalLayout_4.addWidget(self.lblKantong)
        self.valueKantong = QtWidgets.QLabel(self.cardKantong)
        self.valueKantong.setStyleSheet("font-size: 36px; font-weight: bold; color: #750003;")
        self.valueKantong.setAlignment(QtCore.Qt.AlignCenter)
        self.valueKantong.setObjectName("valueKantong")
        self.verticalLayout_4.addWidget(self.valueKantong)
        self.statsLayout.addWidget(self.cardKantong)
        self.cardStok = QtWidgets.QFrame(self.dashboardPage)
        self.cardStok.setStyleSheet("\n"
"QFrame#cardStok {\n"
"    background-color: white;\n"
"    border: 2px solid #750003;\n"
"}\n"
"             ")
        self.cardStok.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cardStok.setObjectName("cardStok")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.cardStok)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.iconStok = QtWidgets.QLabel(self.cardStok)
        self.iconStok.setStyleSheet("font-size: 48px; color: #750003;")
        self.iconStok.setAlignment(QtCore.Qt.AlignCenter)
        self.iconStok.setObjectName("iconStok")
        self.verticalLayout_5.addWidget(self.iconStok)
        self.lblStok = QtWidgets.QLabel(self.cardStok)
        self.lblStok.setStyleSheet("font-size: 14px; color: #666;")
        self.lblStok.setAlignment(QtCore.Qt.AlignCenter)
        self.lblStok.setObjectName("lblStok")
        self.verticalLayout_5.addWidget(self.lblStok)
        self.valueStok = QtWidgets.QLabel(self.cardStok)
        self.valueStok.setStyleSheet("font-size: 36px; font-weight: bold; color: #750003;")
        self.valueStok.setAlignment(QtCore.Qt.AlignCenter)
        self.valueStok.setObjectName("valueStok")
        self.verticalLayout_5.addWidget(self.valueStok)
        self.statsLayout.addWidget(self.cardStok)
        self.cardPermintaan = QtWidgets.QFrame(self.dashboardPage)
        self.cardPermintaan.setStyleSheet("\n"
"QFrame#cardPermintaan {\n"
"    background-color: white;\n"
"    border: 2px solid #750003;\n"
"}\n"
"             ")
        self.cardPermintaan.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cardPermintaan.setObjectName("cardPermintaan")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.cardPermintaan)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.iconPermintaan = QtWidgets.QLabel(self.cardPermintaan)
        self.iconPermintaan.setStyleSheet("font-size: 48px; color: #750003;")
        self.iconPermintaan.setAlignment(QtCore.Qt.AlignCenter)
        self.iconPermintaan.setObjectName("iconPermintaan")
        self.verticalLayout_6.addWidget(self.iconPermintaan)
        self.lblPermintaan = QtWidgets.QLabel(self.cardPermintaan)
        self.lblPermintaan.setStyleSheet("font-size: 14px; color: #666;")
        self.lblPermintaan.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPermintaan.setObjectName("lblPermintaan")
        self.verticalLayout_6.addWidget(self.lblPermintaan)
        self.valuePermintaan = QtWidgets.QLabel(self.cardPermintaan)
        self.valuePermintaan.setStyleSheet("font-size: 36px; font-weight: bold; color: #750003;")
        self.valuePermintaan.setAlignment(QtCore.Qt.AlignCenter)
        self.valuePermintaan.setObjectName("valuePermintaan")
        self.verticalLayout_6.addWidget(self.valuePermintaan)
        self.statsLayout.addWidget(self.cardPermintaan)
        self.verticalLayout_2.addLayout(self.statsLayout)
        self.chartsLayout = QtWidgets.QHBoxLayout()
        self.chartsLayout.setSpacing(20)
        self.chartsLayout.setObjectName("chartsLayout")
        self.chartGolongan = QtWidgets.QFrame(self.dashboardPage)
        self.chartGolongan.setStyleSheet("\n"
"QFrame#chartGolongan {\n"
"    background-color: white;\n"
"    border: 1px solid #ddd;\n"
"}\n"
"             ")
        self.chartGolongan.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.chartGolongan.setObjectName("chartGolongan")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.chartGolongan)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.lblChartGolongan = QtWidgets.QLabel(self.chartGolongan)
        self.lblChartGolongan.setStyleSheet("font-size: 16px; font-weight: bold; color: #750003;")
        self.lblChartGolongan.setObjectName("lblChartGolongan")
        self.verticalLayout_7.addWidget(self.lblChartGolongan)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lblA = QtWidgets.QLabel(self.chartGolongan)
        self.lblA.setStyleSheet("font-size: 14px; font-weight: bold;")
        self.lblA.setObjectName("lblA")
        self.gridLayout.addWidget(self.lblA, 0, 0, 1, 1)
        self.progressA = QtWidgets.QProgressBar(self.chartGolongan)
        self.progressA.setStyleSheet("\n"
"QProgressBar {\n"
"    border: 1px solid #ddd;\n"
"    border-radius: 5px;\n"
"    text-align: center;\n"
"    background-color: #f0f0f0;\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: #750003;\n"
"    border-radius: 4px;\n"
"}\n"
"                  ")
        self.progressA.setProperty("value", 85)
        self.progressA.setObjectName("progressA")
        self.gridLayout.addWidget(self.progressA, 0, 1, 1, 1)
        self.valueA = QtWidgets.QLabel(self.chartGolongan)
        self.valueA.setObjectName("valueA")
        self.gridLayout.addWidget(self.valueA, 0, 2, 1, 1)
        self.lblB = QtWidgets.QLabel(self.chartGolongan)
        self.lblB.setStyleSheet("font-size: 14px; font-weight: bold;")
        self.lblB.setObjectName("lblB")
        self.gridLayout.addWidget(self.lblB, 1, 0, 1, 1)
        self.progressB = QtWidgets.QProgressBar(self.chartGolongan)
        self.progressB.setStyleSheet("\n"
"QProgressBar {\n"
"    border: 1px solid #ddd;\n"
"    border-radius: 5px;\n"
"    text-align: center;\n"
"    background-color: #f0f0f0;\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: #750003;\n"
"    border-radius: 4px;\n"
"}\n"
"                  ")
        self.progressB.setProperty("value", 72)
        self.progressB.setObjectName("progressB")
        self.gridLayout.addWidget(self.progressB, 1, 1, 1, 1)
        self.valueB = QtWidgets.QLabel(self.chartGolongan)
        self.valueB.setObjectName("valueB")
        self.gridLayout.addWidget(self.valueB, 1, 2, 1, 1)
        self.lblO = QtWidgets.QLabel(self.chartGolongan)
        self.lblO.setStyleSheet("font-size: 14px; font-weight: bold;")
        self.lblO.setObjectName("lblO")
        self.gridLayout.addWidget(self.lblO, 2, 0, 1, 1)
        self.progressO = QtWidgets.QProgressBar(self.chartGolongan)
        self.progressO.setStyleSheet("\n"
"QProgressBar {\n"
"    border: 1px solid #ddd;\n"
"    border-radius: 5px;\n"
"    text-align: center;\n"
"    background-color: #f0f0f0;\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: #750003;\n"
"    border-radius: 4px;\n"
"}\n"
"                  ")
        self.progressO.setProperty("value", 95)
        self.progressO.setObjectName("progressO")
        self.gridLayout.addWidget(self.progressO, 2, 1, 1, 1)
        self.valueO = QtWidgets.QLabel(self.chartGolongan)
        self.valueO.setObjectName("valueO")
        self.gridLayout.addWidget(self.valueO, 2, 2, 1, 1)
        self.lblAB = QtWidgets.QLabel(self.chartGolongan)
        self.lblAB.setStyleSheet("font-size: 14px; font-weight: bold;")
        self.lblAB.setObjectName("lblAB")
        self.gridLayout.addWidget(self.lblAB, 3, 0, 1, 1)
        self.progressAB = QtWidgets.QProgressBar(self.chartGolongan)
        self.progressAB.setStyleSheet("\n"
"QProgressBar {\n"
"    border: 1px solid #ddd;\n"
"    border-radius: 5px;\n"
"    text-align: center;\n"
"    background-color: #f0f0f0;\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: #750003;\n"
"    border-radius: 4px;\n"
"}\n"
"                  ")
        self.progressAB.setProperty("value", 76)
        self.progressAB.setObjectName("progressAB")
        self.gridLayout.addWidget(self.progressAB, 3, 1, 1, 1)
        self.valueAB = QtWidgets.QLabel(self.chartGolongan)
        self.valueAB.setObjectName("valueAB")
        self.gridLayout.addWidget(self.valueAB, 3, 2, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout)
        self.chartsLayout.addWidget(self.chartGolongan)
        self.chartAktivitas = QtWidgets.QFrame(self.dashboardPage)
        self.chartAktivitas.setStyleSheet("\n"
"QFrame#chartAktivitas {\n"
"    background-color: white;\n"
"    border: 1px solid #ddd;\n"
"}\n"
"             ")
        self.chartAktivitas.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.chartAktivitas.setObjectName("chartAktivitas")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.chartAktivitas)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.lblChartAktivitas = QtWidgets.QLabel(self.chartAktivitas)
        self.lblChartAktivitas.setStyleSheet("font-size: 16px; font-weight: bold; color: #750003;")
        self.lblChartAktivitas.setObjectName("lblChartAktivitas")
        self.verticalLayout_8.addWidget(self.lblChartAktivitas)
        self.tableAktivitas = QtWidgets.QTableWidget(self.chartAktivitas)
        self.tableAktivitas.setStyleSheet("\n"
"QTableWidget {\n"
"    border: none;\n"
"    background-color: white;\n"
"    gridline-color: #f0f0f0;\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #750003;\n"
"    color: white;\n"
"    padding: 8px;\n"
"    border: none;\n"
"    font-weight: bold;\n"
"}\n"
"QTableWidget::item {\n"
"    padding: 8px;\n"
"}\n"
"                ")
        self.tableAktivitas.setObjectName("tableAktivitas")
        self.tableAktivitas.setColumnCount(3)
        self.tableAktivitas.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableAktivitas.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAktivitas.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAktivitas.setHorizontalHeaderItem(2, item)
        self.verticalLayout_8.addWidget(self.tableAktivitas)
        self.chartsLayout.addWidget(self.chartAktivitas)
        self.verticalLayout_2.addLayout(self.chartsLayout)
        self.framePendonorHariIni = QtWidgets.QFrame(self.dashboardPage)
        self.framePendonorHariIni.setStyleSheet("\n"
"QFrame#framePendonorHariIni {\n"
"    background-color: white;\n"
"    border: 1px solid #ddd;\n"
"}\n"
"           ")
        self.framePendonorHariIni.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framePendonorHariIni.setObjectName("framePendonorHariIni")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.framePendonorHariIni)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.lblPendonorHariIni = QtWidgets.QLabel(self.framePendonorHariIni)
        self.lblPendonorHariIni.setStyleSheet("font-size: 16px; font-weight: bold; color: #750003; padding: 10px;")
        self.lblPendonorHariIni.setObjectName("lblPendonorHariIni")
        self.verticalLayout_9.addWidget(self.lblPendonorHariIni)
        self.tablePendonorHariIni = QtWidgets.QTableWidget(self.framePendonorHariIni)
        self.tablePendonorHariIni.setStyleSheet("\n"
"QTableWidget {\n"
"    border: none;\n"
"    background-color: white;\n"
"    gridline-color: #f0f0f0;\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #750003;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    border: none;\n"
"    font-weight: bold;\n"
"    font-size: 13px;\n"
"}\n"
"QTableWidget::item {\n"
"    padding: 10px;\n"
"    border-bottom: 1px solid #f0f0f0;\n"
"}\n"
"QTableWidget::item:selected {\n"
"    background-color: #ffeaea;\n"
"    color: #333333;\n"
"}\n"
"              ")
        self.tablePendonorHariIni.setAlternatingRowColors(True)
        self.tablePendonorHariIni.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tablePendonorHariIni.setObjectName("tablePendonorHariIni")
        self.tablePendonorHariIni.setColumnCount(7)
        self.tablePendonorHariIni.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablePendonorHariIni.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePendonorHariIni.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePendonorHariIni.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePendonorHariIni.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePendonorHariIni.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePendonorHariIni.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePendonorHariIni.setHorizontalHeaderItem(6, item)
        self.verticalLayout_9.addWidget(self.tablePendonorHariIni)
        self.verticalLayout_2.addWidget(self.framePendonorHariIni)
        self.stackedWidget.addWidget(self.dashboardPage)
        self.verticalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.btnValidasi.clicked.connect(self.buka_validasi)
        self.btnLaporan.clicked.connect(self.buka_laporan)
        self.btnStok.clicked.connect(self.buka_stok)
        self.btnTransaksi.clicked.connect(self.buka_transaksi)


        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
    def load_pendaftaran_pending(self):
        data = get_pendaftaran_pending()
        self.tablePendonorHariIni.setRowCount(0)

        for row_idx, row in enumerate(data):
            id_daftar, nama, nik, gol, waktu, status = row
            self.tablePendonorHariIni.insertRow(row_idx)

            self.tablePendonorHariIni.setItem(row_idx, 0, QtWidgets.QTableWidgetItem(str(row_idx + 1)))
            self.tablePendonorHariIni.setItem(row_idx, 1, QtWidgets.QTableWidgetItem(nama))
            self.tablePendonorHariIni.setItem(row_idx, 2, QtWidgets.QTableWidgetItem(nik))
            self.tablePendonorHariIni.setItem(row_idx, 3, QtWidgets.QTableWidgetItem(gol))
            self.tablePendonorHariIni.setItem(row_idx, 4, QtWidgets.QTableWidgetItem(str(waktu)))
            self.tablePendonorHariIni.setItem(row_idx, 5, QtWidgets.QTableWidgetItem(status))

            btn = QtWidgets.QPushButton("Validasi")
            btn.clicked.connect(
                lambda _, pid=id_daftar: self.validasi_donor(pid)
            )
            self.tablePendonorHariIni.setCellWidget(row_idx, 6, btn)
            
            
    def validasi_donor(self, id_daftar):
        msg = QtWidgets.QMessageBox.question(
            self.mainwindow,
            "Konfirmasi",
            "Setujui pendaftaran donor ini?",
            QtWidgets.QMessageBox.Yes | QtWidgets.QMessageBox.No
        )

        if msg == QtWidgets.QMessageBox.Yes:
            terima_pendaftaran(id_daftar)
            self.load_pendaftaran_pending()
        elif msg == QtWidgets.QMessageBox.No:
            update_status_pendaftaran(id_daftar, "ditolak")
        
        self.load_pendaftaran_pending()


        
    def buka_validasi(self):
        import validasi
        self.validasi_window = QtWidgets.QMainWindow()
        self.ui = validasi.Ui_MainWindow()
        self.ui.set_petugas(self.id_petugas)
        self.ui.setupUi(self.validasi_window)
        self.validasi_window.show()
        self.mainwindow.hide()
        
    def buka_laporan(self):
        import laporan
        self.laporan_window = QtWidgets.QMainWindow()
        self.ui = laporan.Ui_MainWindow()
        self.ui.set_petugas(self.id_petugas)
        self.ui.setupUi(self.laporan_window)
        self.laporan_window.show()
        self.mainwindow.hide()
        
    def buka_stok(self):
        import stokdarah
        self.stok_window = QtWidgets.QMainWindow()
        self.ui = stokdarah.Ui_MainWindow()
        self.ui.set_petugas(self.id_petugas)
        self.ui.setupUi(self.stok_window)
        self.stok_window.show()
        self.mainwindow.hide()
        
    def buka_transaksi(self):
        import transaksidarah
        self.transaksi_window = QtWidgets.QMainWindow()
        self.ui = transaksidarah.Ui_MainWindow()
        self.ui.set_petugas(self.id_petugas)
        self.ui.setupUi(self.transaksi_window)
        self.transaksi_window.show()
        self.mainwindow.hide()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dashboard PMI - Donor Darah"))
        self.logoLabel.setText(_translate("MainWindow", "PMI DONOR DARAH"))
        self.btnDashboard.setText(_translate("MainWindow", "Dashboard"))
        self.btnTransaksi.setText(_translate("MainWindow", "Transaksi Darah"))
        self.btnStok.setText(_translate("MainWindow", "Stok Darah"))
        self.btnValidasi.setText(_translate("MainWindow", "Validasi Permintaan"))
        self.btnLaporan.setText(_translate("MainWindow", "Laporan"))
        self.titleLabel.setText(_translate("MainWindow", "Dashboard Statistik"))
        self.iconPendonor.setText(_translate("MainWindow", "👤"))
        self.lblPendonor.setText(_translate("MainWindow", "Total Pendonor Hari Ini"))
        self.valuePendonor.setText(_translate("MainWindow", "47"))
        self.iconKantong.setText(_translate("MainWindow", "💉"))
        self.lblKantong.setText(_translate("MainWindow", "Kantong Darah Terkumpul"))
        self.valueKantong.setText(_translate("MainWindow", "45"))
        self.iconStok.setText(_translate("MainWindow", "📦"))
        self.lblStok.setText(_translate("MainWindow", "Total Stok Darah"))
        self.valueStok.setText(_translate("MainWindow", "328"))
        self.iconPermintaan.setText(_translate("MainWindow", "📋"))
        self.lblPermintaan.setText(_translate("MainWindow", "Permintaan Pending"))
        self.valuePermintaan.setText(_translate("MainWindow", "12"))
        self.lblChartGolongan.setText(_translate("MainWindow", "Stok per Golongan Darah"))
        self.lblA.setText(_translate("MainWindow", "A"))
        self.valueA.setText(_translate("MainWindow", "85 kantong"))
        self.lblB.setText(_translate("MainWindow", "B"))
        self.valueB.setText(_translate("MainWindow", "72 kantong"))
        self.lblO.setText(_translate("MainWindow", "O"))
        self.valueO.setText(_translate("MainWindow", "95 kantong"))
        self.lblAB.setText(_translate("MainWindow", "AB"))
        self.valueAB.setText(_translate("MainWindow", "76 kantong"))
        self.lblChartAktivitas.setText(_translate("MainWindow", "Aktivitas Donor 7 Hari Terakhir"))
        item = self.tableAktivitas.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Hari"))
        item = self.tableAktivitas.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Pendonor"))
        item = self.tableAktivitas.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Kantong"))
        self.lblPendonorHariIni.setText(_translate("MainWindow", "Data Pendonor Hari Ini"))
        item = self.tablePendonorHariIni.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "No"))
        item = self.tablePendonorHariIni.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nama Pendonor"))
        item = self.tablePendonorHariIni.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "NIK"))
        item = self.tablePendonorHariIni.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Golongan Darah"))
        item = self.tablePendonorHariIni.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Waktu Donor"))
        item = self.tablePendonorHariIni.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Status"))
        item = self.tablePendonorHariIni.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Aksi"))
        self.load_pendaftaran_pending()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
