# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dasboardpendonor.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from USER import connect


class Ui_DonorDashboard(object):
    def setupUi(self, DonorDashboard):
        self.id_pendonor = None
        self.window = DonorDashboard
        DonorDashboard.setObjectName("DonorDashboard")
        DonorDashboard.resize(1200, 800)
        DonorDashboard.setStyleSheet("\n"
"QMainWindow {\n"
"    background-color: #f5f5f5;\n"
"}\n"
"QPushButton {\n"
"    border: none;\n"
"    padding: 10px 20px;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    opacity: 0.8;\n"
"}\n"
"QFrame {\n"
"    border-radius: 10px;\n"
"}\n"
"QLabel {\n"
"    color: #333333;\n"
"}\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(DonorDashboard)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.navbar = QtWidgets.QFrame(self.centralwidget)
        self.navbar.setMinimumSize(QtCore.QSize(0, 70))
        self.navbar.setMaximumSize(QtCore.QSize(16777215, 70))
        self.navbar.setStyleSheet("\n"
"QFrame#navbar {\n"
"    background-color: #750003;\n"
"}\n"
"QPushButton {\n"
"    color: white;\n"
"    background-color: transparent;\n"
"    text-align: left;\n"
"    padding: 15px 25px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.1);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 0.2);\n"
"}\n"
"       ")
        self.navbar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.navbar.setObjectName("navbar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.navbar)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logoLabel = QtWidgets.QLabel(self.navbar)
        self.logoLabel.setMinimumSize(QtCore.QSize(200, 0))
        self.logoLabel.setStyleSheet("color: white; font-size: 18px; font-weight: bold; padding-left: 20px;")
        self.logoLabel.setObjectName("logoLabel")
        self.horizontalLayout.addWidget(self.logoLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnDashboard = QtWidgets.QPushButton(self.navbar)
        self.btnDashboard.setMinimumSize(QtCore.QSize(120, 0))
        self.btnDashboard.setObjectName("btnDashboard")
        self.horizontalLayout.addWidget(self.btnDashboard)
        self.btnPendaftaran = QtWidgets.QPushButton(self.navbar)
        self.btnPendaftaran.setMinimumSize(QtCore.QSize(170, 0))
        self.btnPendaftaran.setObjectName("btnPendaftaran")
        self.horizontalLayout.addWidget(self.btnPendaftaran)
        self.btnJadwal = QtWidgets.QPushButton(self.navbar)
        self.btnJadwal.setMinimumSize(QtCore.QSize(130, 0))
        self.btnJadwal.setObjectName("btnJadwal")
        self.horizontalLayout.addWidget(self.btnJadwal)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btnProfil = QtWidgets.QPushButton(self.navbar)
        self.btnProfil.setMinimumSize(QtCore.QSize(50, 50))
        self.btnProfil.setMaximumSize(QtCore.QSize(50, 50))
        self.btnProfil.setStyleSheet("QPushButton {\n"
"    image: url(:/blood/account.png);\n"
"    background-color: white;\n"
"    /* Radius 25px -> Ukuran tombol minimal 50x50 agar jadi lingkaran */\n"
"    border-radius: 25px; \n"
"    \n"
"    /* Atur lebar dan tinggi agar menjadi lingkaran sempurna */\n"
"    min-width: 50px;\n"
"    max-width: 50px;\n"
"    min-height: 50px;\n"
"    max-height: 50px;\n"
"    \n"
"    /* Padding diatur ke 0 seperti permintaan Anda */\n"
"    padding: 0px; \n"
"    font-size: 24px;\n"
"    /* Konten (ikon/teks) default-nya sudah di tengah */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.9);\n"
"}QPushButton {\n"
"    background-color: white;\n"
"    /* Radius 25px -> Ukuran tombol minimal 50x50 agar jadi lingkaran */\n"
"    border-radius: 25px; \n"
"    \n"
"    /* Atur lebar dan tinggi agar menjadi lingkaran sempurna */\n"
"    min-width: 50px;\n"
"    max-width: 50px;\n"
"    min-height: 50px;\n"
"    max-height: 50px;\n"
"    \n"
"    /* Padding diatur ke 0 seperti permintaan Anda */\n"
"    padding: 0px; \n"
"    font-size: 24px;\n"
"    /* Konten (ikon/teks) default-nya sudah di tengah */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.9);\n"
"}")
        self.btnProfil.setText("")
        self.btnProfil.setIconSize(QtCore.QSize(30, 30))
        self.btnProfil.setObjectName("btnProfil")
        self.horizontalLayout.addWidget(self.btnProfil)
        self.verticalLayout.addWidget(self.navbar)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setStyleSheet("QScrollArea { border: none; background-color: #f5f5f5; }")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollContent = QtWidgets.QWidget()
        self.scrollContent.setGeometry(QtCore.QRect(0, 0, 1187, 833))
        self.scrollContent.setObjectName("scrollContent")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollContent)
        self.verticalLayout_2.setContentsMargins(30, 30, 30, 30)
        self.verticalLayout_2.setSpacing(25)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.welcomeLabel = QtWidgets.QLabel(self.scrollContent)
        self.welcomeLabel.setStyleSheet("font-size: 28px; font-weight: bold; color: #750003;")
        self.welcomeLabel.setObjectName("welcomeLabel")
        self.verticalLayout_2.addWidget(self.welcomeLabel)
        self.profileCard = QtWidgets.QFrame(self.scrollContent)
        self.profileCard.setStyleSheet("\n"
"QFrame#profileCard {\n"
"    background-color: white;\n"
"    border: 2px solid #750003;\n"
"    padding: 20px;\n"
"}\n"
"           ")
        self.profileCard.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.profileCard.setObjectName("profileCard")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.profileCard)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.avatarLabel = QtWidgets.QLabel(self.profileCard)
        self.avatarLabel.setMinimumSize(QtCore.QSize(80, 80))
        self.avatarLabel.setMaximumSize(QtCore.QSize(80, 80))
        self.avatarLabel.setStyleSheet("\n"
"QLabel {\n"
"    background-color: #750003;\n"
"    border-radius: 40px;\n"
"    color: white;\n"
"    font-size: 40px;\n"
"}\n"
"              ")
        self.avatarLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.avatarLabel.setObjectName("avatarLabel")
        self.horizontalLayout_2.addWidget(self.avatarLabel)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.namaLabel = QtWidgets.QLabel(self.profileCard)
        self.namaLabel.setStyleSheet("font-size: 20px; font-weight: bold; color: #750003;")
        self.namaLabel.setObjectName("namaLabel")
        self.verticalLayout_3.addWidget(self.namaLabel)
        self.golDarahLabel = QtWidgets.QLabel(self.profileCard)
        self.golDarahLabel.setStyleSheet("font-size: 16px; color: #666;")
        self.golDarahLabel.setObjectName("golDarahLabel")
        self.verticalLayout_3.addWidget(self.golDarahLabel)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lblStatus = QtWidgets.QLabel(self.profileCard)
        self.lblStatus.setStyleSheet("font-size: 14px; color: #666;")
        self.lblStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.lblStatus.setObjectName("lblStatus")
        self.verticalLayout_4.addWidget(self.lblStatus)
        self.statusDonor = QtWidgets.QLabel(self.profileCard)
        self.statusDonor.setStyleSheet("\n"
"QLabel {\n"
"    background-color: #28a745;\n"
"    color: white;\n"
"    padding: 8px 16px;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"}\n"
"                ")
        self.statusDonor.setAlignment(QtCore.Qt.AlignCenter)
        self.statusDonor.setObjectName("statusDonor")
        self.verticalLayout_4.addWidget(self.statusDonor)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_2.addWidget(self.profileCard)
        self.statsLayout = QtWidgets.QHBoxLayout()
        self.statsLayout.setSpacing(20)
        self.statsLayout.setObjectName("statsLayout")
        self.cardTotalDonor = QtWidgets.QFrame(self.scrollContent)
        self.cardTotalDonor.setStyleSheet("\n"
"QFrame#cardTotalDonor {\n"
"    background-color: white;\n"
"    border: 2px solid #750003;\n"
"}\n"
"             ")
        self.cardTotalDonor.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cardTotalDonor.setObjectName("cardTotalDonor")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.cardTotalDonor)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.iconTotal = QtWidgets.QLabel(self.cardTotalDonor)
        self.iconTotal.setStyleSheet("font-size: 48px; color: #750003;")
        self.iconTotal.setAlignment(QtCore.Qt.AlignCenter)
        self.iconTotal.setObjectName("iconTotal")
        self.verticalLayout_5.addWidget(self.iconTotal)
        self.lblTotal = QtWidgets.QLabel(self.cardTotalDonor)
        self.lblTotal.setStyleSheet("font-size: 14px; color: #666;")
        self.lblTotal.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTotal.setObjectName("lblTotal")
        self.verticalLayout_5.addWidget(self.lblTotal)
        self.valueTotal = QtWidgets.QLabel(self.cardTotalDonor)
        self.valueTotal.setStyleSheet("font-size: 36px; font-weight: bold; color: #750003;")
        self.valueTotal.setAlignment(QtCore.Qt.AlignCenter)
        self.valueTotal.setObjectName("valueTotal")
        self.verticalLayout_5.addWidget(self.valueTotal)
        self.subTotal = QtWidgets.QLabel(self.cardTotalDonor)
        self.subTotal.setStyleSheet("font-size: 12px; color: #999;")
        self.subTotal.setAlignment(QtCore.Qt.AlignCenter)
        self.subTotal.setObjectName("subTotal")
        self.verticalLayout_5.addWidget(self.subTotal)
        self.statsLayout.addWidget(self.cardTotalDonor)
        self.cardJumlahDarah = QtWidgets.QFrame(self.scrollContent)
        self.cardJumlahDarah.setStyleSheet("\n"
"QFrame#cardJumlahDarah {\n"
"    background-color: white;\n"
"    border: 2px solid #750003;\n"
"}\n"
"             ")
        self.cardJumlahDarah.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cardJumlahDarah.setObjectName("cardJumlahDarah")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.cardJumlahDarah)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.iconJumlah = QtWidgets.QLabel(self.cardJumlahDarah)
        self.iconJumlah.setStyleSheet("font-size: 48px; color: #750003;")
        self.iconJumlah.setAlignment(QtCore.Qt.AlignCenter)
        self.iconJumlah.setObjectName("iconJumlah")
        self.verticalLayout_6.addWidget(self.iconJumlah)
        self.lblJumlah = QtWidgets.QLabel(self.cardJumlahDarah)
        self.lblJumlah.setStyleSheet("font-size: 14px; color: #666;")
        self.lblJumlah.setAlignment(QtCore.Qt.AlignCenter)
        self.lblJumlah.setObjectName("lblJumlah")
        self.verticalLayout_6.addWidget(self.lblJumlah)
        self.valueJumlah = QtWidgets.QLabel(self.cardJumlahDarah)
        self.valueJumlah.setStyleSheet("font-size: 36px; font-weight: bold; color: #750003;")
        self.valueJumlah.setAlignment(QtCore.Qt.AlignCenter)
        self.valueJumlah.setObjectName("valueJumlah")
        self.verticalLayout_6.addWidget(self.valueJumlah)
        self.subJumlah = QtWidgets.QLabel(self.cardJumlahDarah)
        self.subJumlah.setStyleSheet("font-size: 12px; color: #999;")
        self.subJumlah.setAlignment(QtCore.Qt.AlignCenter)
        self.subJumlah.setObjectName("subJumlah")
        self.verticalLayout_6.addWidget(self.subJumlah)
        self.statsLayout.addWidget(self.cardJumlahDarah)
        self.cardTerakhir = QtWidgets.QFrame(self.scrollContent)
        self.cardTerakhir.setStyleSheet("\n"
"QFrame#cardTerakhir {\n"
"    background-color: white;\n"
"    border: 2px solid #750003;\n"
"}\n"
"             ")
        self.cardTerakhir.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cardTerakhir.setObjectName("cardTerakhir")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.cardTerakhir)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.iconTerakhir = QtWidgets.QLabel(self.cardTerakhir)
        self.iconTerakhir.setStyleSheet("font-size: 48px; color: #750003;")
        self.iconTerakhir.setAlignment(QtCore.Qt.AlignCenter)
        self.iconTerakhir.setObjectName("iconTerakhir")
        self.verticalLayout_7.addWidget(self.iconTerakhir)
        self.lblTerakhir = QtWidgets.QLabel(self.cardTerakhir)
        self.lblTerakhir.setStyleSheet("font-size: 14px; color: #666;")
        self.lblTerakhir.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTerakhir.setObjectName("lblTerakhir")
        self.verticalLayout_7.addWidget(self.lblTerakhir)
        self.valueTerakhir = QtWidgets.QLabel(self.cardTerakhir)
        self.valueTerakhir.setStyleSheet("font-size: 20px; font-weight: bold; color: #750003;")
        self.valueTerakhir.setAlignment(QtCore.Qt.AlignCenter)
        self.valueTerakhir.setObjectName("valueTerakhir")
        self.verticalLayout_7.addWidget(self.valueTerakhir)
        self.subTerakhir = QtWidgets.QLabel(self.cardTerakhir)
        self.subTerakhir.setStyleSheet("font-size: 12px; color: #999;")
        self.subTerakhir.setAlignment(QtCore.Qt.AlignCenter)
        self.subTerakhir.setObjectName("subTerakhir")
        self.verticalLayout_7.addWidget(self.subTerakhir)
        self.statsLayout.addWidget(self.cardTerakhir)
        self.cardBerikutnya = QtWidgets.QFrame(self.scrollContent)
        self.cardBerikutnya.setStyleSheet("\n"
"QFrame#cardBerikutnya {\n"
"    background-color: white;\n"
"    border: 2px solid #750003;\n"
"}\n"
"             ")
        self.cardBerikutnya.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cardBerikutnya.setObjectName("cardBerikutnya")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.cardBerikutnya)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.iconBerikutnya = QtWidgets.QLabel(self.cardBerikutnya)
        self.iconBerikutnya.setStyleSheet("font-size: 48px; color: #750003;")
        self.iconBerikutnya.setAlignment(QtCore.Qt.AlignCenter)
        self.iconBerikutnya.setObjectName("iconBerikutnya")
        self.verticalLayout_8.addWidget(self.iconBerikutnya)
        self.lblBerikutnya = QtWidgets.QLabel(self.cardBerikutnya)
        self.lblBerikutnya.setStyleSheet("font-size: 14px; color: #666;")
        self.lblBerikutnya.setAlignment(QtCore.Qt.AlignCenter)
        self.lblBerikutnya.setObjectName("lblBerikutnya")
        self.verticalLayout_8.addWidget(self.lblBerikutnya)
        self.valueBerikutnya = QtWidgets.QLabel(self.cardBerikutnya)
        self.valueBerikutnya.setStyleSheet("font-size: 20px; font-weight: bold; color: #750003;")
        self.valueBerikutnya.setAlignment(QtCore.Qt.AlignCenter)
        self.valueBerikutnya.setObjectName("valueBerikutnya")
        self.verticalLayout_8.addWidget(self.valueBerikutnya)
        self.subBerikutnya = QtWidgets.QLabel(self.cardBerikutnya)
        self.subBerikutnya.setStyleSheet("font-size: 12px; color: #28a745; font-weight: bold;")
        self.subBerikutnya.setAlignment(QtCore.Qt.AlignCenter)
        self.subBerikutnya.setObjectName("subBerikutnya")
        self.verticalLayout_8.addWidget(self.subBerikutnya)
        self.statsLayout.addWidget(self.cardBerikutnya)
        self.verticalLayout_2.addLayout(self.statsLayout)
        self.contentLayout = QtWidgets.QHBoxLayout()
        self.contentLayout.setSpacing(20)
        self.contentLayout.setObjectName("contentLayout")
        self.riwayatFrame = QtWidgets.QFrame(self.scrollContent)
        self.riwayatFrame.setStyleSheet("\n"
"QFrame#riwayatFrame {\n"
"    background-color: white;\n"
"    border: 1px solid #ddd;\n"
"}\n"
"             ")
        self.riwayatFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.riwayatFrame.setObjectName("riwayatFrame")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.riwayatFrame)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.lblRiwayat = QtWidgets.QLabel(self.riwayatFrame)
        self.lblRiwayat.setStyleSheet("font-size: 18px; font-weight: bold; color: #750003;")
        self.lblRiwayat.setObjectName("lblRiwayat")
        self.verticalLayout_9.addWidget(self.lblRiwayat)
        self.tableRiwayat = QtWidgets.QTableWidget(self.riwayatFrame)
        self.tableRiwayat.setStyleSheet("\n"
"QTableWidget {\n"
"    border: none;\n"
"    background-color: white;\n"
"    gridline-color: #f0f0f0;\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #750003;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    border: none;\n"
"    font-weight: bold;\n"
"}\n"
"QTableWidget::item {\n"
"    padding: 10px;\n"
"}\n"
"                ")
        self.tableRiwayat.setObjectName("tableRiwayat")
        self.tableRiwayat.setColumnCount(4)
        self.tableRiwayat.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableRiwayat.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableRiwayat.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableRiwayat.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableRiwayat.setHorizontalHeaderItem(3, item)
        self.verticalLayout_9.addWidget(self.tableRiwayat)
        self.contentLayout.addWidget(self.riwayatFrame)
        self.pencapaianFrame = QtWidgets.QFrame(self.scrollContent)
        self.pencapaianFrame.setMinimumSize(QtCore.QSize(350, 0))
        self.pencapaianFrame.setMaximumSize(QtCore.QSize(350, 16777215))
        self.pencapaianFrame.setStyleSheet("\n"
"QFrame#pencapaianFrame {\n"
"    background-color: white;\n"
"    border: 1px solid #ddd;\n"
"}\n"
"             ")
        self.pencapaianFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pencapaianFrame.setObjectName("pencapaianFrame")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.pencapaianFrame)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.lblPencapaian = QtWidgets.QLabel(self.pencapaianFrame)
        self.lblPencapaian.setStyleSheet("font-size: 18px; font-weight: bold; color: #750003;")
        self.lblPencapaian.setObjectName("lblPencapaian")
        self.verticalLayout_10.addWidget(self.lblPencapaian)
        self.badgeFrame1 = QtWidgets.QFrame(self.pencapaianFrame)
        self.badgeFrame1.setStyleSheet("\n"
"QFrame {\n"
"    background-color: #fff8e1;\n"
"    border: 2px solid #ffc107;\n"
"    border-radius: 8px;\n"
"    padding: 10px;\n"
"}\n"
"                ")
        self.badgeFrame1.setObjectName("badgeFrame1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.badgeFrame1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.badgeIcon1 = QtWidgets.QLabel(self.badgeFrame1)
        self.badgeIcon1.setStyleSheet("font-size: 40px; border: none;")
        self.badgeIcon1.setObjectName("badgeIcon1")
        self.horizontalLayout_3.addWidget(self.badgeIcon1)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.badgeTitle1 = QtWidgets.QLabel(self.badgeFrame1)
        self.badgeTitle1.setStyleSheet("font-size: 14px; font-weight: bold; color: #333; border: none;")
        self.badgeTitle1.setObjectName("badgeTitle1")
        self.verticalLayout_11.addWidget(self.badgeTitle1)
        self.badgeDesc1 = QtWidgets.QLabel(self.badgeFrame1)
        self.badgeDesc1.setStyleSheet("font-size: 12px; color: #666; border: none;")
        self.badgeDesc1.setObjectName("badgeDesc1")
        self.verticalLayout_11.addWidget(self.badgeDesc1)
        self.horizontalLayout_3.addLayout(self.verticalLayout_11)
        self.verticalLayout_10.addWidget(self.badgeFrame1)
        self.badgeFrame2 = QtWidgets.QFrame(self.pencapaianFrame)
        self.badgeFrame2.setStyleSheet("\n"
"QFrame {\n"
"    background-color: #e8f5e9;\n"
"    border: 2px solid #4caf50;\n"
"    border-radius: 8px;\n"
"    padding: 10px;\n"
"}\n"
"                ")
        self.badgeFrame2.setObjectName("badgeFrame2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.badgeFrame2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.badgeIcon2 = QtWidgets.QLabel(self.badgeFrame2)
        self.badgeIcon2.setStyleSheet("font-size: 40px; border: none;")
        self.badgeIcon2.setObjectName("badgeIcon2")
        self.horizontalLayout_4.addWidget(self.badgeIcon2)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.badgeTitle2 = QtWidgets.QLabel(self.badgeFrame2)
        self.badgeTitle2.setStyleSheet("font-size: 14px; font-weight: bold; color: #333; border: none;")
        self.badgeTitle2.setObjectName("badgeTitle2")
        self.verticalLayout_12.addWidget(self.badgeTitle2)
        self.badgeDesc2 = QtWidgets.QLabel(self.badgeFrame2)
        self.badgeDesc2.setStyleSheet("font-size: 12px; color: #666; border: none;")
        self.badgeDesc2.setObjectName("badgeDesc2")
        self.verticalLayout_12.addWidget(self.badgeDesc2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_12)
        self.verticalLayout_10.addWidget(self.badgeFrame2)
        self.lblProgress = QtWidgets.QLabel(self.pencapaianFrame)
        self.lblProgress.setStyleSheet("font-size: 14px; font-weight: bold; color: #750003; margin-top: 10px;")
        self.lblProgress.setObjectName("lblProgress")
        self.verticalLayout_10.addWidget(self.lblProgress)
        self.progressTitle = QtWidgets.QLabel(self.pencapaianFrame)
        self.progressTitle.setStyleSheet("font-size: 13px; color: #666;")
        self.progressTitle.setObjectName("progressTitle")
        self.verticalLayout_10.addWidget(self.progressTitle)
        self.progressBadge = QtWidgets.QProgressBar(self.pencapaianFrame)
        self.progressBadge.setStyleSheet("\n"
"QProgressBar {\n"
"    border: 2px solid #ddd;\n"
"    border-radius: 5px;\n"
"    text-align: center;\n"
"    background-color: #f0f0f0;\n"
"    height: 25px;\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: #750003;\n"
"    border-radius: 3px;\n"
"}\n"
"                ")
        self.progressBadge.setProperty("value", 80)
        self.progressBadge.setObjectName("progressBadge")
        self.verticalLayout_10.addWidget(self.progressBadge)
        self.contentLayout.addWidget(self.pencapaianFrame)
        self.verticalLayout_2.addLayout(self.contentLayout)
        self.scrollArea.setWidget(self.scrollContent)
        self.verticalLayout.addWidget(self.scrollArea)
        DonorDashboard.setCentralWidget(self.centralwidget)
        self.btnPendaftaran.clicked.connect(self.masuk_pendaftaran_donor)
        self.btnJadwal.clicked.connect(self.masuk_jadwal_donor)
        self.btnPendaftaran.clicked.connect(self.masuk_pendaftaran_donor)

        self.retranslateUi(DonorDashboard)
        QtCore.QMetaObject.connectSlotsByName(DonorDashboard)
        
    def set_pendonor(self, id_pendonor):
        self.id_pendonor = id_pendonor
        self.load_data()

    def load_data(self):
        if not self.id_pendonor:
            return
    
        db = connect()
        cursor = db.cursor()
        cursor.execute("""
            SELECT COUNT(*)
            FROM pendaftaran_donor
            WHERE id_pendonor = %s
              AND status = 'selesai'
        """, (self.id_pendonor,))
        total = cursor.fetchone()[0]
        self.valueTotal.setText(str(total))


        cursor.execute("""
            SELECT nama_pendonor, gol_darah, nik
            FROM pendonor
            WHERE id_pendonor = %s
        """, (self.id_pendonor,))

        data = cursor.fetchone()
        if not data:
            return

        nama, gol, nik = data

        self.namaLabel.setText(nama)
        self.welcomeLabel.setText(f"Selamat Datang, {nama}!")
        self.golDarahLabel.setText(f"Golongan Darah: {gol} | NIK: {nik}")
        
        
    def masuk_pendaftaran_donor(self):
        import daftar_mau_donor
        self.donor_daftar_window = QtWidgets.QMainWindow()
        self.donor_daftar_ui = daftar_mau_donor.Ui_PendaftaranDonor()
        self.donor_daftar_ui.setupUi(self.donor_daftar_window)
        self.donor_daftar_ui.set_pendonor(self.id_pendonor)
        self.donor_daftar_window.show()
        self.window.hide()
        
    def masuk_jadwal_donor(self):
        import jadwal
        self.jadwal_window = QtWidgets.QMainWindow()
        self.jadwal_ui = jadwal.Ui_JadwalDonor()
        self.jadwal_ui.setupUi(self.jadwal_window)
        self.jadwal_ui.set_pendonor(self.id_pendonor)
        self.jadwal_window.show()
        self.window.close()
        
    def retranslateUi(self, DonorDashboard):
        _translate = QtCore.QCoreApplication.translate
        DonorDashboard.setWindowTitle(_translate("DonorDashboard", "Dashboard Pendonor - PMI"))
        self.logoLabel.setText(_translate("DonorDashboard", "PMI DONOR DARAH"))
        self.btnDashboard.setText(_translate("DonorDashboard", "Dashboard"))
        self.btnPendaftaran.setText(_translate("DonorDashboard", "Pendaftaran Donor"))
        self.btnJadwal.setText(_translate("DonorDashboard", "Jadwal Donor"))
        self.welcomeLabel.setText(_translate("DonorDashboard", "Selamat Datang, Donor Hero!"))
        self.avatarLabel.setText(_translate("DonorDashboard", "👤"))
        self.namaLabel.setText(_translate("DonorDashboard", "-"))
        self.golDarahLabel.setText(_translate("DonorDashboard", "-"))
        self.lblStatus.setText(_translate("DonorDashboard", "Status Donor"))
        self.statusDonor.setText(_translate("DonorDashboard", "Aktif"))
        self.iconTotal.setText(_translate("DonorDashboard", "💉"))
        self.lblTotal.setText(_translate("DonorDashboard", "Total Donor"))
        self.valueTotal.setText(_translate("DonorDashboard", "12"))
        self.subTotal.setText(_translate("DonorDashboard", "kali"))
        self.iconJumlah.setText(_translate("DonorDashboard", "🩸"))
        self.lblJumlah.setText(_translate("DonorDashboard", "Total Darah Terdonasi"))
        self.valueJumlah.setText(_translate("DonorDashboard", "6000"))
        self.subJumlah.setText(_translate("DonorDashboard", "ml"))
        self.iconTerakhir.setText(_translate("DonorDashboard", "📅"))
        self.lblTerakhir.setText(_translate("DonorDashboard", "Donor Terakhir"))
        self.valueTerakhir.setText(_translate("DonorDashboard", "15 Agu 2024"))
        self.subTerakhir.setText(_translate("DonorDashboard", "103 hari yang lalu"))
        self.iconBerikutnya.setText(_translate("DonorDashboard", "⏰"))
        self.lblBerikutnya.setText(_translate("DonorDashboard", "Donor Berikutnya"))
        self.valueBerikutnya.setText(_translate("DonorDashboard", "26 Nov 2024"))
        self.subBerikutnya.setText(_translate("DonorDashboard", "Siap donor!"))
        self.lblRiwayat.setText(_translate("DonorDashboard", "Riwayat Donor"))
        item = self.tableRiwayat.horizontalHeaderItem(0)
        item.setText(_translate("DonorDashboard", "Tanggal"))
        item = self.tableRiwayat.horizontalHeaderItem(1)
        item.setText(_translate("DonorDashboard", "Lokasi"))
        item = self.tableRiwayat.horizontalHeaderItem(2)
        item.setText(_translate("DonorDashboard", "Volume (ml)"))
        item = self.tableRiwayat.horizontalHeaderItem(3)
        item.setText(_translate("DonorDashboard", "Status"))
        self.lblPencapaian.setText(_translate("DonorDashboard", "Pencapaian"))
        self.badgeIcon1.setText(_translate("DonorDashboard", "🏆"))
        self.badgeTitle1.setText(_translate("DonorDashboard", "Donor Sejati"))
        self.badgeDesc1.setText(_translate("DonorDashboard", "10+ kali donor"))
        self.badgeIcon2.setText(_translate("DonorDashboard", "⭐"))
        self.badgeTitle2.setText(_translate("DonorDashboard", "Pahlawan Kehidupan"))
        self.badgeDesc2.setText(_translate("DonorDashboard", "5+ liter darah"))
        self.lblProgress.setText(_translate("DonorDashboard", "Progress Berikutnya"))
        self.progressTitle.setText(_translate("DonorDashboard", "Donor Champion (15 kali)"))
        self.progressBadge.setFormat(_translate("DonorDashboard", "12/15"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DonorDashboard = QtWidgets.QMainWindow()
    ui = Ui_DonorDashboard()
    ui.setupUi(DonorDashboard)
    DonorDashboard.show()
    sys.exit(app.exec_())
