# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dashboardrumahsakit.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def set_petugas(self, id_user):
        self.id_petugas = id_user
        
    def setupUi(self, MainWindow):
        self.mainwindow = MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        MainWindow.setStyleSheet("\n"
"QMainWindow {\n"
"    background-color: #f5f5f5;\n"
"}\n"
"QPushButton {\n"
"    border: none;\n"
"    padding: 10px 20px;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    opacity: 0.8;\n"
"}\n"
"QFrame {\n"
"    border-radius: 10px;\n"
"}\n"
"QLabel {\n"
"    color: #333333;\n"
"}\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.navbar = QtWidgets.QFrame(self.centralwidget)
        self.navbar.setMinimumSize(QtCore.QSize(0, 70))
        self.navbar.setMaximumSize(QtCore.QSize(16777215, 70))
        self.navbar.setStyleSheet("\n"
"QFrame#navbar {\n"
"    background-color: #750003;\n"
"}\n"
"QPushButton {\n"
"    color: white;\n"
"    background-color: transparent;\n"
"    text-align: left;\n"
"    padding: 15px 25px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.1);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 0.2);\n"
"}\n"
"       ")
        self.navbar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.navbar.setObjectName("navbar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.navbar)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logoLabel = QtWidgets.QLabel(self.navbar)
        self.logoLabel.setMinimumSize(QtCore.QSize(250, 0))
        self.logoLabel.setStyleSheet("color: white; font-size: 18px; font-weight: bold; padding-left: 20px;")
        self.logoLabel.setObjectName("logoLabel")
        self.horizontalLayout.addWidget(self.logoLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnDashboard = QtWidgets.QPushButton(self.navbar)
        self.btnDashboard.setMinimumSize(QtCore.QSize(120, 0))
        self.btnDashboard.setObjectName("btnDashboard")
        self.horizontalLayout.addWidget(self.btnDashboard)
        self.btnStok = QtWidgets.QPushButton(self.navbar)
        self.btnStok.setMinimumSize(QtCore.QSize(120, 0))
        self.btnStok.setObjectName("btnStok")
        self.horizontalLayout.addWidget(self.btnStok)
        self.btnPermintaan = QtWidgets.QPushButton(self.navbar)
        self.btnPermintaan.setMinimumSize(QtCore.QSize(150, 0))
        self.btnPermintaan.setObjectName("btnPermintaan")
        self.horizontalLayout.addWidget(self.btnPermintaan)
        self.btnRiwayat = QtWidgets.QPushButton(self.navbar)
        self.btnRiwayat.setMinimumSize(QtCore.QSize(100, 0))
        self.btnRiwayat.setObjectName("btnRiwayat")
        self.horizontalLayout.addWidget(self.btnRiwayat)
        self.btnLaporan = QtWidgets.QPushButton(self.navbar)
        self.btnLaporan.setMinimumSize(QtCore.QSize(100, 0))
        self.btnLaporan.setObjectName("btnLaporan")
        self.horizontalLayout.addWidget(self.btnLaporan)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.navbar)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.dashboardPage = QtWidgets.QWidget()
        self.dashboardPage.setObjectName("dashboardPage")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dashboardPage)
        self.verticalLayout_2.setContentsMargins(30, 30, 30, 30)
        self.verticalLayout_2.setSpacing(20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.headerLayout = QtWidgets.QHBoxLayout()
        self.headerLayout.setObjectName("headerLayout")
        self.titleLabel = QtWidgets.QLabel(self.dashboardPage)
        self.titleLabel.setStyleSheet("font-size: 24px; font-weight: bold; color: #750003;")
        self.titleLabel.setObjectName("titleLabel")
        self.headerLayout.addWidget(self.titleLabel)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.headerLayout.addItem(spacerItem2)
        self.btnPermintaanBaru = QtWidgets.QPushButton(self.dashboardPage)
        self.btnPermintaanBaru.setMinimumSize(QtCore.QSize(180, 40))
        self.btnPermintaanBaru.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: #750003;\n"
"    color: white;\n"
"    font-size: 14px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #a00004;\n"
"}\n"
"             ")
        self.btnPermintaanBaru.setObjectName("btnPermintaanBaru")
        self.headerLayout.addWidget(self.btnPermintaanBaru)
        self.verticalLayout_2.addLayout(self.headerLayout)
        self.statsLayout = QtWidgets.QHBoxLayout()
        self.statsLayout.setSpacing(20)
        self.statsLayout.setObjectName("statsLayout")
        self.cardPermintaanAktif = QtWidgets.QFrame(self.dashboardPage)
        self.cardPermintaanAktif.setStyleSheet("\n"
"QFrame#cardPermintaanAktif {\n"
"    background-color: white;\n"
"    border: 2px solid #750003;\n"
"}\n"
"             ")
        self.cardPermintaanAktif.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cardPermintaanAktif.setObjectName("cardPermintaanAktif")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.cardPermintaanAktif)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.iconPermintaanAktif = QtWidgets.QLabel(self.cardPermintaanAktif)
        self.iconPermintaanAktif.setStyleSheet("font-size: 48px; color: #750003;")
        self.iconPermintaanAktif.setAlignment(QtCore.Qt.AlignCenter)
        self.iconPermintaanAktif.setObjectName("iconPermintaanAktif")
        self.verticalLayout_3.addWidget(self.iconPermintaanAktif)
        self.lblPermintaanAktif = QtWidgets.QLabel(self.cardPermintaanAktif)
        self.lblPermintaanAktif.setStyleSheet("font-size: 14px; color: #666;")
        self.lblPermintaanAktif.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPermintaanAktif.setObjectName("lblPermintaanAktif")
        self.verticalLayout_3.addWidget(self.lblPermintaanAktif)
        self.valuePermintaanAktif = QtWidgets.QLabel(self.cardPermintaanAktif)
        self.valuePermintaanAktif.setStyleSheet("font-size: 36px; font-weight: bold; color: #750003;")
        self.valuePermintaanAktif.setAlignment(QtCore.Qt.AlignCenter)
        self.valuePermintaanAktif.setObjectName("valuePermintaanAktif")
        self.verticalLayout_3.addWidget(self.valuePermintaanAktif)
        self.statsLayout.addWidget(self.cardPermintaanAktif)
        self.cardMenunggu = QtWidgets.QFrame(self.dashboardPage)
        self.cardMenunggu.setStyleSheet("\n"
"QFrame#cardMenunggu {\n"
"    background-color: white;\n"
"    border: 2px solid #750003;\n"
"}\n"
"             ")
        self.cardMenunggu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cardMenunggu.setObjectName("cardMenunggu")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.cardMenunggu)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.iconMenunggu = QtWidgets.QLabel(self.cardMenunggu)
        self.iconMenunggu.setStyleSheet("font-size: 48px; color: #750003;")
        self.iconMenunggu.setAlignment(QtCore.Qt.AlignCenter)
        self.iconMenunggu.setObjectName("iconMenunggu")
        self.verticalLayout_4.addWidget(self.iconMenunggu)
        self.lblMenunggu = QtWidgets.QLabel(self.cardMenunggu)
        self.lblMenunggu.setStyleSheet("font-size: 14px; color: #666;")
        self.lblMenunggu.setAlignment(QtCore.Qt.AlignCenter)
        self.lblMenunggu.setObjectName("lblMenunggu")
        self.verticalLayout_4.addWidget(self.lblMenunggu)
        self.valueMenunggu = QtWidgets.QLabel(self.cardMenunggu)
        self.valueMenunggu.setStyleSheet("font-size: 36px; font-weight: bold; color: #750003;")
        self.valueMenunggu.setAlignment(QtCore.Qt.AlignCenter)
        self.valueMenunggu.setObjectName("valueMenunggu")
        self.verticalLayout_4.addWidget(self.valueMenunggu)
        self.statsLayout.addWidget(self.cardMenunggu)
        self.cardDiterima = QtWidgets.QFrame(self.dashboardPage)
        self.cardDiterima.setStyleSheet("\n"
"QFrame#cardDiterima {\n"
"    background-color: white;\n"
"    border: 2px solid #750003;\n"
"}\n"
"             ")
        self.cardDiterima.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cardDiterima.setObjectName("cardDiterima")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.cardDiterima)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.iconDiterima = QtWidgets.QLabel(self.cardDiterima)
        self.iconDiterima.setStyleSheet("font-size: 48px; color: #750003;")
        self.iconDiterima.setAlignment(QtCore.Qt.AlignCenter)
        self.iconDiterima.setObjectName("iconDiterima")
        self.verticalLayout_5.addWidget(self.iconDiterima)
        self.lblDiterima = QtWidgets.QLabel(self.cardDiterima)
        self.lblDiterima.setStyleSheet("font-size: 14px; color: #666;")
        self.lblDiterima.setAlignment(QtCore.Qt.AlignCenter)
        self.lblDiterima.setObjectName("lblDiterima")
        self.verticalLayout_5.addWidget(self.lblDiterima)
        self.valueDiterima = QtWidgets.QLabel(self.cardDiterima)
        self.valueDiterima.setStyleSheet("font-size: 36px; font-weight: bold; color: #750003;")
        self.valueDiterima.setAlignment(QtCore.Qt.AlignCenter)
        self.valueDiterima.setObjectName("valueDiterima")
        self.verticalLayout_5.addWidget(self.valueDiterima)
        self.statsLayout.addWidget(self.cardDiterima)
        self.cardDitolak = QtWidgets.QFrame(self.dashboardPage)
        self.cardDitolak.setStyleSheet("\n"
"QFrame#cardDitolak {\n"
"    background-color: white;\n"
"    border: 2px solid #750003;\n"
"}\n"
"             ")
        self.cardDitolak.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cardDitolak.setObjectName("cardDitolak")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.cardDitolak)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.iconDitolak = QtWidgets.QLabel(self.cardDitolak)
        self.iconDitolak.setStyleSheet("font-size: 48px; color: #750003;")
        self.iconDitolak.setAlignment(QtCore.Qt.AlignCenter)
        self.iconDitolak.setObjectName("iconDitolak")
        self.verticalLayout_6.addWidget(self.iconDitolak)
        self.lblDitolak = QtWidgets.QLabel(self.cardDitolak)
        self.lblDitolak.setStyleSheet("font-size: 14px; color: #666;")
        self.lblDitolak.setAlignment(QtCore.Qt.AlignCenter)
        self.lblDitolak.setObjectName("lblDitolak")
        self.verticalLayout_6.addWidget(self.lblDitolak)
        self.valueDitolak = QtWidgets.QLabel(self.cardDitolak)
        self.valueDitolak.setStyleSheet("font-size: 36px; font-weight: bold; color: #750003;")
        self.valueDitolak.setAlignment(QtCore.Qt.AlignCenter)
        self.valueDitolak.setObjectName("valueDitolak")
        self.verticalLayout_6.addWidget(self.valueDitolak)
        self.statsLayout.addWidget(self.cardDitolak)
        self.verticalLayout_2.addLayout(self.statsLayout)
        self.contentLayout = QtWidgets.QHBoxLayout()
        self.contentLayout.setSpacing(20)
        self.contentLayout.setObjectName("contentLayout")
        self.framePermintaanTerbaru = QtWidgets.QFrame(self.dashboardPage)
        self.framePermintaanTerbaru.setStyleSheet("\n"
"QFrame#framePermintaanTerbaru {\n"
"    background-color: white;\n"
"    border: 1px solid #ddd;\n"
"}\n"
"             ")
        self.framePermintaanTerbaru.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framePermintaanTerbaru.setObjectName("framePermintaanTerbaru")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.framePermintaanTerbaru)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.lblPermintaanTerbaru = QtWidgets.QLabel(self.framePermintaanTerbaru)
        self.lblPermintaanTerbaru.setStyleSheet("font-size: 16px; font-weight: bold; color: #750003;")
        self.lblPermintaanTerbaru.setObjectName("lblPermintaanTerbaru")
        self.verticalLayout_7.addWidget(self.lblPermintaanTerbaru)
        self.tablePermintaan = QtWidgets.QTableWidget(self.framePermintaanTerbaru)
        self.tablePermintaan.setStyleSheet("\n"
"QTableWidget {\n"
"    border: none;\n"
"    background-color: white;\n"
"    gridline-color: #f0f0f0;\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #750003;\n"
"    color: white;\n"
"    padding: 8px;\n"
"    border: none;\n"
"    font-weight: bold;\n"
"}\n"
"QTableWidget::item {\n"
"    padding: 8px;\n"
"}\n"
"                ")
        self.tablePermintaan.setObjectName("tablePermintaan")
        self.tablePermintaan.setColumnCount(5)
        self.tablePermintaan.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablePermintaan.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePermintaan.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePermintaan.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePermintaan.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePermintaan.setHorizontalHeaderItem(4, item)
        self.verticalLayout_7.addWidget(self.tablePermintaan)
        self.contentLayout.addWidget(self.framePermintaanTerbaru)
        self.frameStokCepat = QtWidgets.QFrame(self.dashboardPage)
        self.frameStokCepat.setMinimumSize(QtCore.QSize(350, 0))
        self.frameStokCepat.setMaximumSize(QtCore.QSize(350, 16777215))
        self.frameStokCepat.setStyleSheet("\n"
"QFrame#frameStokCepat {\n"
"    background-color: white;\n"
"    border: 1px solid #ddd;\n"
"}\n"
"             ")
        self.frameStokCepat.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameStokCepat.setObjectName("frameStokCepat")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frameStokCepat)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.lblStokCepat = QtWidgets.QLabel(self.frameStokCepat)
        self.lblStokCepat.setStyleSheet("font-size: 16px; font-weight: bold; color: #750003;")
        self.lblStokCepat.setObjectName("lblStokCepat")
        self.verticalLayout_8.addWidget(self.lblStokCepat)
        self.gridStok = QtWidgets.QGridLayout()
        self.gridStok.setObjectName("gridStok")
        self.lblGolA = QtWidgets.QLabel(self.frameStokCepat)
        self.lblGolA.setStyleSheet("font-size: 14px; font-weight: bold;")
        self.lblGolA.setObjectName("lblGolA")
        self.gridStok.addWidget(self.lblGolA, 0, 0, 1, 1)
        self.valueGolA = QtWidgets.QLabel(self.frameStokCepat)
        self.valueGolA.setStyleSheet("font-size: 18px; font-weight: bold; color: #750003;")
        self.valueGolA.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.valueGolA.setObjectName("valueGolA")
        self.gridStok.addWidget(self.valueGolA, 0, 1, 1, 1)
        self.lblGolB = QtWidgets.QLabel(self.frameStokCepat)
        self.lblGolB.setStyleSheet("font-size: 14px; font-weight: bold;")
        self.lblGolB.setObjectName("lblGolB")
        self.gridStok.addWidget(self.lblGolB, 1, 0, 1, 1)
        self.valueGolB = QtWidgets.QLabel(self.frameStokCepat)
        self.valueGolB.setStyleSheet("font-size: 18px; font-weight: bold; color: #750003;")
        self.valueGolB.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.valueGolB.setObjectName("valueGolB")
        self.gridStok.addWidget(self.valueGolB, 1, 1, 1, 1)
        self.lblGolO = QtWidgets.QLabel(self.frameStokCepat)
        self.lblGolO.setStyleSheet("font-size: 14px; font-weight: bold;")
        self.lblGolO.setObjectName("lblGolO")
        self.gridStok.addWidget(self.lblGolO, 2, 0, 1, 1)
        self.valueGolO = QtWidgets.QLabel(self.frameStokCepat)
        self.valueGolO.setStyleSheet("font-size: 18px; font-weight: bold; color: #750003;")
        self.valueGolO.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.valueGolO.setObjectName("valueGolO")
        self.gridStok.addWidget(self.valueGolO, 2, 1, 1, 1)
        self.lblGolAB = QtWidgets.QLabel(self.frameStokCepat)
        self.lblGolAB.setStyleSheet("font-size: 14px; font-weight: bold;")
        self.lblGolAB.setObjectName("lblGolAB")
        self.gridStok.addWidget(self.lblGolAB, 3, 0, 1, 1)
        self.valueGolAB = QtWidgets.QLabel(self.frameStokCepat)
        self.valueGolAB.setStyleSheet("font-size: 18px; font-weight: bold; color: #750003;")
        self.valueGolAB.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.valueGolAB.setObjectName("valueGolAB")
        self.gridStok.addWidget(self.valueGolAB, 3, 1, 1, 1)
        self.verticalLayout_8.addLayout(self.gridStok)
        self.line = QtWidgets.QFrame(self.frameStokCepat)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_8.addWidget(self.line)
        self.lblNotifikasi = QtWidgets.QLabel(self.frameStokCepat)
        self.lblNotifikasi.setStyleSheet("font-size: 14px; font-weight: bold; color: #750003; margin-top: 10px;")
        self.lblNotifikasi.setObjectName("lblNotifikasi")
        self.verticalLayout_8.addWidget(self.lblNotifikasi)
        self.valueNotifikasi = QtWidgets.QLabel(self.frameStokCepat)
        self.valueNotifikasi.setStyleSheet("font-size: 12px; color: #666; padding: 10px; background-color: #fff5f5; border-radius: 5px;")
        self.valueNotifikasi.setWordWrap(True)
        self.valueNotifikasi.setObjectName("valueNotifikasi")
        self.verticalLayout_8.addWidget(self.valueNotifikasi)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem3)
        self.contentLayout.addWidget(self.frameStokCepat)
        self.verticalLayout_2.addLayout(self.contentLayout)
        self.stackedWidget.addWidget(self.dashboardPage)
        self.verticalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.btnLaporan.clicked.connect(self.tampil_page_laporan)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
    def tampil_page_laporan(self):
        import laporan
        self.laporan_window = QtWidgets.QMainWindow()
        self.ui = laporan.Ui_MainWindow()
        self.ui.setupUi(self.laporan_window)
        self.laporan_window.show()
        self.mainwindow.hide()
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dashboard Rumah Sakit - PMI Donor Darah"))
        self.logoLabel.setText(_translate("MainWindow", "🏥 RUMAH SAKIT - PMI"))
        self.btnDashboard.setText(_translate("MainWindow", "Dashboard"))
        self.btnStok.setText(_translate("MainWindow", "Stok Darah"))
        self.btnPermintaan.setText(_translate("MainWindow", "Permintaan Darah"))
        self.btnRiwayat.setText(_translate("MainWindow", "Riwayat"))
        self.btnLaporan.setText(_translate("MainWindow", "Laporan"))
        self.titleLabel.setText(_translate("MainWindow", "Dashboard Rumah Sakit"))
        self.btnPermintaanBaru.setText(_translate("MainWindow", "+ Buat Permintaan Baru"))
        self.iconPermintaanAktif.setText(_translate("MainWindow", "🩸"))
        self.lblPermintaanAktif.setText(_translate("MainWindow", "Permintaan Aktif"))
        self.valuePermintaanAktif.setText(_translate("MainWindow", "8"))
        self.iconMenunggu.setText(_translate("MainWindow", "⏳"))
        self.lblMenunggu.setText(_translate("MainWindow", "Menunggu Validasi"))
        self.valueMenunggu.setText(_translate("MainWindow", "5"))
        self.iconDiterima.setText(_translate("MainWindow", "✅"))
        self.lblDiterima.setText(_translate("MainWindow", "Diterima Bulan Ini"))
        self.valueDiterima.setText(_translate("MainWindow", "142"))
        self.iconDitolak.setText(_translate("MainWindow", "❌"))
        self.lblDitolak.setText(_translate("MainWindow", "Ditolak Bulan Ini"))
        self.valueDitolak.setText(_translate("MainWindow", "3"))
        self.lblPermintaanTerbaru.setText(_translate("MainWindow", "Permintaan Terbaru"))
        item = self.tablePermintaan.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "No. Permintaan"))
        item = self.tablePermintaan.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Golongan"))
        item = self.tablePermintaan.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Jumlah"))
        item = self.tablePermintaan.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Status"))
        item = self.tablePermintaan.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Tanggal"))
        self.lblStokCepat.setText(_translate("MainWindow", "Stok Darah Tersedia"))
        self.lblGolA.setText(_translate("MainWindow", "A+"))
        self.valueGolA.setText(_translate("MainWindow", "42 kantong"))
        self.lblGolB.setText(_translate("MainWindow", "B+"))
        self.valueGolB.setText(_translate("MainWindow", "38 kantong"))
        self.lblGolO.setText(_translate("MainWindow", "O+"))
        self.valueGolO.setText(_translate("MainWindow", "56 kantong"))
        self.lblGolAB.setText(_translate("MainWindow", "AB+"))
        self.valueGolAB.setText(_translate("MainWindow", "29 kantong"))
        self.lblNotifikasi.setText(_translate("MainWindow", "Notifikasi Penting"))
        self.valueNotifikasi.setText(_translate("MainWindow", "⚠️ Stok golongan AB+ menipis!\n"
"Segera ajukan permintaan."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
