# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jadwal.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


#from USER import connect
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from LOG_JADWAL import get_jadwal_donor



class Ui_JadwalDonor(object):
    def setupUi(self, JadwalDonor):
        self.window = JadwalDonor
        self.id_pendonor = None
        JadwalDonor.setObjectName("JadwalDonor")
        JadwalDonor.resize(1200, 800)
        JadwalDonor.setStyleSheet("\n"
"QMainWindow {\n"
"    background-color: #f5f5f5;\n"
"}\n"
"QPushButton {\n"
"    border: none;\n"
"    padding: 10px 20px;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    opacity: 0.8;\n"
"}\n"
"QFrame {\n"
"    border-radius: 10px;\n"
"}\n"
"QLabel {\n"
"    color: #333333;\n"
"}\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(JadwalDonor)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.navbar = QtWidgets.QFrame(self.centralwidget)
        self.navbar.setMinimumSize(QtCore.QSize(0, 70))
        self.navbar.setMaximumSize(QtCore.QSize(16777215, 70))
        self.navbar.setStyleSheet("\n"
"QFrame#navbar {\n"
"    background-color: #750003;\n"
"}\n"
"QPushButton {\n"
"    color: white;\n"
"    background-color: transparent;\n"
"    text-align: left;\n"
"    padding: 15px 25px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.1);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 0.2);\n"
"}\n"
"       ")
        self.navbar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.navbar.setObjectName("navbar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.navbar)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logoLabel = QtWidgets.QLabel(self.navbar)
        self.logoLabel.setMinimumSize(QtCore.QSize(200, 0))
        self.logoLabel.setStyleSheet("color: white; font-size: 18px; font-weight: bold; padding-left: 20px;")
        self.logoLabel.setObjectName("logoLabel")
        self.horizontalLayout.addWidget(self.logoLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnDashboard = QtWidgets.QPushButton(self.navbar)
        self.btnDashboard.setMinimumSize(QtCore.QSize(120, 0))
        self.btnDashboard.setObjectName("btnDashboard")
        self.horizontalLayout.addWidget(self.btnDashboard)
        self.btnPendaftaran = QtWidgets.QPushButton(self.navbar)
        self.btnPendaftaran.setMinimumSize(QtCore.QSize(170, 0))
        self.btnPendaftaran.setObjectName("btnPendaftaran")
        self.horizontalLayout.addWidget(self.btnPendaftaran)
        self.btnJadwal = QtWidgets.QPushButton(self.navbar)
        self.btnJadwal.setMinimumSize(QtCore.QSize(130, 0))
        self.btnJadwal.setStyleSheet("background-color: rgba(255, 255, 255, 0.2);")
        self.btnJadwal.setObjectName("btnJadwal")
        self.horizontalLayout.addWidget(self.btnJadwal)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btnProfil = QtWidgets.QPushButton(self.navbar)
        self.btnProfil.setMinimumSize(QtCore.QSize(50, 50))
        self.btnProfil.setMaximumSize(QtCore.QSize(50, 50))
        self.btnProfil.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: white;\n"
"    border-radius: 25px;\n"
"    min-width: 50px;\n"
"    max-width: 50px;\n"
"    min-height: 50px;\n"
"    max-height: 50px;\n"
"    padding: 0px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.9);\n"
"}\n"
"          ")
        self.btnProfil.setObjectName("btnProfil")
        self.horizontalLayout.addWidget(self.btnProfil)
        self.verticalLayout.addWidget(self.navbar)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setStyleSheet("QScrollArea { border: none; background-color: #f5f5f5; }")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollContent = QtWidgets.QWidget()
        self.scrollContent.setGeometry(QtCore.QRect(0, 0, 1187, 700))
        self.scrollContent.setObjectName("scrollContent")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollContent)
        self.verticalLayout_2.setContentsMargins(30, 30, 30, 30)
        self.verticalLayout_2.setSpacing(25)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pageTitle = QtWidgets.QLabel(self.scrollContent)
        self.pageTitle.setStyleSheet("font-size: 28px; font-weight: bold; color: #750003;")
        self.pageTitle.setObjectName("pageTitle")
        self.verticalLayout_2.addWidget(self.pageTitle)
        self.filterCard = QtWidgets.QFrame(self.scrollContent)
        self.filterCard.setStyleSheet("\n"
"QFrame#filterCard {\n"
"    background-color: white;\n"
"    border: 2px solid #750003;\n"
"    padding: 15px;\n"
"}\n"
"           ")
        self.filterCard.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.filterCard.setObjectName("filterCard")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.filterCard)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblFilter = QtWidgets.QLabel(self.filterCard)
        self.lblFilter.setStyleSheet("font-size: 14px; font-weight: bold; color: #750003;")
        self.lblFilter.setObjectName("lblFilter")
        self.horizontalLayout_2.addWidget(self.lblFilter)
        self.comboLokasi = QtWidgets.QComboBox(self.filterCard)
        self.comboLokasi.setMinimumSize(QtCore.QSize(200, 35))
        self.comboLokasi.setStyleSheet("\n"
"QComboBox {\n"
"    border: 2px solid #ddd;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"    background-color: white;\n"
"}\n"
"QComboBox:hover {\n"
"    border-color: #750003;\n"
"}\n"
"              ")
        self.comboLokasi.setObjectName("comboLokasi")
        self.comboLokasi.addItem("")
        self.comboLokasi.addItem("")
        self.comboLokasi.addItem("")
        self.comboLokasi.addItem("")
        self.horizontalLayout_2.addWidget(self.comboLokasi)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.btnRefresh = QtWidgets.QPushButton(self.filterCard)
        self.btnRefresh.setMinimumSize(QtCore.QSize(120, 35))
        self.btnRefresh.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: #750003;\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 8px 16px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5a0002;\n"
"}\n"
"              ")
        self.btnRefresh.setObjectName("btnRefresh")
        self.horizontalLayout_2.addWidget(self.btnRefresh)
        self.verticalLayout_2.addWidget(self.filterCard)
        self.jadwalFrame = QtWidgets.QFrame(self.scrollContent)
        self.jadwalFrame.setStyleSheet("\n"
"QFrame#jadwalFrame {\n"
"    background-color: white;\n"
"    border: 1px solid #ddd;\n"
"}\n"
"           ")
        self.jadwalFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.jadwalFrame.setObjectName("jadwalFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.jadwalFrame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lblJadwal = QtWidgets.QLabel(self.jadwalFrame)
        self.lblJadwal.setStyleSheet("font-size: 18px; font-weight: bold; color: #750003;")
        self.lblJadwal.setObjectName("lblJadwal")
        self.verticalLayout_3.addWidget(self.lblJadwal)
        self.tableJadwal = QtWidgets.QTableWidget(self.jadwalFrame)
        self.tableJadwal.setStyleSheet("\n"
"QTableWidget {\n"
"    border: none;\n"
"    background-color: white;\n"
"    gridline-color: #f0f0f0;\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #750003;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    border: none;\n"
"    font-weight: bold;\n"
"}\n"
"QTableWidget::item {\n"
"    padding: 10px;\n"
"}\n"
"              ")
        self.tableJadwal.setObjectName("tableJadwal")
        self.tableJadwal.setColumnCount(6)
        self.tableJadwal.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableJadwal.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableJadwal.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableJadwal.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableJadwal.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableJadwal.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableJadwal.setHorizontalHeaderItem(5, item)
        self.verticalLayout_3.addWidget(self.tableJadwal)
        self.verticalLayout_2.addWidget(self.jadwalFrame)
        self.infoCard = QtWidgets.QFrame(self.scrollContent)
        self.infoCard.setStyleSheet("\n"
"QFrame#infoCard {\n"
"    background-color: #e8f5e9;\n"
"    border: 2px solid #4caf50;\n"
"    padding: 15px;\n"
"}\n"
"           ")
        self.infoCard.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.infoCard.setObjectName("infoCard")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.infoCard)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.iconInfo = QtWidgets.QLabel(self.infoCard)
        self.iconInfo.setStyleSheet("font-size: 32px; border: none;")
        self.iconInfo.setObjectName("iconInfo")
        self.horizontalLayout_3.addWidget(self.iconInfo)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lblInfoTitle = QtWidgets.QLabel(self.infoCard)
        self.lblInfoTitle.setStyleSheet("font-size: 14px; font-weight: bold; color: #333; border: none;")
        self.lblInfoTitle.setObjectName("lblInfoTitle")
        self.verticalLayout_4.addWidget(self.lblInfoTitle)
        self.lblInfoDesc = QtWidgets.QLabel(self.infoCard)
        self.lblInfoDesc.setStyleSheet("font-size: 12px; color: #666; border: none;")
        self.lblInfoDesc.setWordWrap(True)
        self.lblInfoDesc.setObjectName("lblInfoDesc")
        self.verticalLayout_4.addWidget(self.lblInfoDesc)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_2.addWidget(self.infoCard)
        self.scrollArea.setWidget(self.scrollContent)
        self.verticalLayout.addWidget(self.scrollArea)
        JadwalDonor.setCentralWidget(self.centralwidget)
        self.btnDashboard.clicked.connect(self.balik_dashboard)
        self.btnPendaftaran.clicked.connect(self.masuk_pendaftaran_donor)

        self.retranslateUi(JadwalDonor)
        QtCore.QMetaObject.connectSlotsByName(JadwalDonor)
        
    def set_pendonor(self, id_pendonor):
        self.id_pendonor = id_pendonor
        
    def masuk_pendaftaran_donor(self):
        import daftar_mau_donor
        self.donor_daftar_window = QtWidgets.QMainWindow()
        self.donor_daftar_ui = daftar_mau_donor.Ui_PendaftaranDonor()
        self.donor_daftar_ui.setupUi(self.donor_daftar_window)
        self.donor_daftar_ui.set_pendonor(self.id_pendonor)
        self.donor_daftar_window.show()
        self.window.hide()
        
    def balik_dashboard(self):
        import dasboardpendonor
        self.dashboardwindow = QtWidgets.QMainWindow()
        self.dashboard_ui = dasboardpendonor.Ui_DonorDashboard()
        self.dashboard_ui.setupUi(self.dashboardwindow)
        self.dashboard_ui.set_pendonor(self.id_pendonor)
        self.dashboardwindow.show()
        self.window.close()
        
    def load_jadwal(self):
        data = get_jadwal_donor()
        self.tableJadwal.setRowCount(0)

        for row_idx, row in enumerate(data):
            id_jadwal, nama, gol, tanggal, waktu, lokasi, status = row

            self.tableJadwal.insertRow(row_idx)
            self.tableJadwal.setItem(row_idx, 0, QtWidgets.QTableWidgetItem(str(row_idx + 1)))
            self.tableJadwal.setItem(row_idx, 1, QtWidgets.QTableWidgetItem(nama))
            self.tableJadwal.setItem(row_idx, 2, QtWidgets.QTableWidgetItem(gol))
            self.tableJadwal.setItem(row_idx, 3, QtWidgets.QTableWidgetItem(str(tanggal)))
            self.tableJadwal.setItem(row_idx, 4, QtWidgets.QTableWidgetItem(str(waktu)))
            self.tableJadwal.setItem(row_idx, 5, QtWidgets.QTableWidgetItem(lokasi))
            self.tableJadwal.setItem(row_idx, 6, QtWidgets.QTableWidgetItem(status))


    def retranslateUi(self, JadwalDonor):
        _translate = QtCore.QCoreApplication.translate
        JadwalDonor.setWindowTitle(_translate("JadwalDonor", "Jadwal Donor - PMI"))
        self.logoLabel.setText(_translate("JadwalDonor", "PMI DONOR DARAH"))
        self.btnDashboard.setText(_translate("JadwalDonor", "Dashboard"))
        self.btnPendaftaran.setText(_translate("JadwalDonor", "Pendaftaran Donor"))
        self.btnJadwal.setText(_translate("JadwalDonor", "Jadwal Donor"))
        self.btnProfil.setText(_translate("JadwalDonor", "👤"))
        self.pageTitle.setText(_translate("JadwalDonor", "Jadwal Donor Darah"))
        self.lblFilter.setText(_translate("JadwalDonor", "Filter Lokasi:"))
        self.comboLokasi.setItemText(0, _translate("JadwalDonor", "Semua Lokasi"))
        self.comboLokasi.setItemText(1, _translate("JadwalDonor", "PMI Kota Malang"))
        self.comboLokasi.setItemText(2, _translate("JadwalDonor", "RS Saiful Anwar"))
        self.comboLokasi.setItemText(3, _translate("JadwalDonor", "Mall Olympic Garden"))
        self.btnRefresh.setText(_translate("JadwalDonor", "🔄 Refresh"))
        self.lblJadwal.setText(_translate("JadwalDonor", "Jadwal Donor Tersedia"))
        item = self.tableJadwal.horizontalHeaderItem(0)
        item.setText(_translate("JadwalDonor", "Tanggal"))
        item = self.tableJadwal.horizontalHeaderItem(1)
        item.setText(_translate("JadwalDonor", "Waktu"))
        item = self.tableJadwal.horizontalHeaderItem(2)
        item.setText(_translate("JadwalDonor", "Lokasi"))
        item = self.tableJadwal.horizontalHeaderItem(3)
        item.setText(_translate("JadwalDonor", "Kuota"))
        item = self.tableJadwal.horizontalHeaderItem(4)
        item.setText(_translate("JadwalDonor", "Status"))
        item = self.tableJadwal.horizontalHeaderItem(5)
        item.setText(_translate("JadwalDonor", "Aksi"))
        self.iconInfo.setText(_translate("JadwalDonor", "ℹ️"))
        self.lblInfoTitle.setText(_translate("JadwalDonor", "Informasi Penting"))
        self.lblInfoDesc.setText(_translate("JadwalDonor", "Pastikan Anda sudah istirahat cukup, makan bergizi, dan dalam kondisi sehat sebelum donor darah."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    JadwalDonor = QtWidgets.QMainWindow()
    ui = Ui_JadwalDonor()
    ui.setupUi(JadwalDonor)
    JadwalDonor.show()
    sys.exit(app.exec_())
