# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'laporan.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidgetItem
from DARAH import *


class Ui_MainWindow(object):
    def set_petugas(self, id_user):
        self.id_petugas = id_user
        
    def setupUi(self, MainWindow):
        self.Mainwindow = MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        MainWindow.setStyleSheet("\n"
"QMainWindow {\n"
"    background-color: #f5f5f5;\n"
"}\n"
"QPushButton {\n"
"    border: none;\n"
"    padding: 10px 20px;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    opacity: 0.8;\n"
"}\n"
"QFrame {\n"
"    border-radius: 10px;\n"
"}\n"
"QLabel {\n"
"    color: #333333;\n"
"}\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.navbar = QtWidgets.QFrame(self.centralwidget)
        self.navbar.setMinimumSize(QtCore.QSize(0, 70))
        self.navbar.setMaximumSize(QtCore.QSize(16777215, 70))
        self.navbar.setStyleSheet("\n"
"QFrame#navbar {\n"
"    background-color: #750003;\n"
"}\n"
"QPushButton {\n"
"    color: white;\n"
"    background-color: transparent;\n"
"    text-align: left;\n"
"    padding: 15px 25px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.1);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 0.2);\n"
"}\n"
"       ")
        self.navbar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.navbar.setObjectName("navbar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.navbar)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logoLabel = QtWidgets.QLabel(self.navbar)
        self.logoLabel.setMinimumSize(QtCore.QSize(200, 0))
        self.logoLabel.setStyleSheet("color: white; font-size: 18px; font-weight: bold; padding-left: 20px;")
        self.logoLabel.setObjectName("logoLabel")
        self.horizontalLayout.addWidget(self.logoLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnDashboard = QtWidgets.QPushButton(self.navbar)
        self.btnDashboard.setMinimumSize(QtCore.QSize(120, 0))
        self.btnDashboard.setObjectName("btnDashboard")
        self.horizontalLayout.addWidget(self.btnDashboard)
        self.btnTransaksi = QtWidgets.QPushButton(self.navbar)
        self.btnTransaksi.setMinimumSize(QtCore.QSize(150, 0))
        self.btnTransaksi.setObjectName("btnTransaksi")
        self.horizontalLayout.addWidget(self.btnTransaksi)
        self.btnStok = QtWidgets.QPushButton(self.navbar)
        self.btnStok.setMinimumSize(QtCore.QSize(100, 0))
        self.btnStok.setObjectName("btnStok")
        self.horizontalLayout.addWidget(self.btnStok)
        self.btnValidasi = QtWidgets.QPushButton(self.navbar)
        self.btnValidasi.setMinimumSize(QtCore.QSize(180, 0))
        self.btnValidasi.setObjectName("btnValidasi")
        self.horizontalLayout.addWidget(self.btnValidasi)
        self.btnLaporan = QtWidgets.QPushButton(self.navbar)
        self.btnLaporan.setMinimumSize(QtCore.QSize(100, 0))
        self.btnLaporan.setObjectName("btnLaporan")
        self.horizontalLayout.addWidget(self.btnLaporan)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.navbar)
        self.stokPage = QtWidgets.QWidget(self.centralwidget)
        self.stokPage.setObjectName("stokPage")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.stokPage)
        self.verticalLayout_2.setContentsMargins(30, 30, 30, 30)
        self.verticalLayout_2.setSpacing(20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.headerLayout = QtWidgets.QHBoxLayout()
        self.headerLayout.setObjectName("headerLayout")
        self.titleLabel = QtWidgets.QLabel(self.stokPage)
        self.titleLabel.setStyleSheet("font-size: 24px; font-weight: bold; color: #750003;")
        self.titleLabel.setObjectName("titleLabel")
        self.headerLayout.addWidget(self.titleLabel)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.headerLayout.addItem(spacerItem2)
        self.btnRefresh = QtWidgets.QPushButton(self.stokPage)
        self.btnRefresh.setMinimumSize(QtCore.QSize(120, 40))
        self.btnRefresh.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: #750003;\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 10px 20px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #8b0003;\n"
"}\n"
"            ")
        self.btnRefresh.setObjectName("btnRefresh")
        self.headerLayout.addWidget(self.btnRefresh)
        self.verticalLayout_2.addLayout(self.headerLayout)
        self.summaryLayout = QtWidgets.QHBoxLayout()
        self.summaryLayout.setSpacing(20)
        self.summaryLayout.setObjectName("summaryLayout")
        self.cardTotalStok = QtWidgets.QFrame(self.stokPage)
        self.cardTotalStok.setStyleSheet("\n"
"QFrame#cardTotalStok {\n"
"    background-color: white;\n"
"    border: 2px solid #750003;\n"
"}\n"
"            ")
        self.cardTotalStok.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cardTotalStok.setObjectName("cardTotalStok")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.cardTotalStok)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.iconTotal = QtWidgets.QLabel(self.cardTotalStok)
        self.iconTotal.setStyleSheet("font-size: 48px; color: #750003;")
        self.iconTotal.setAlignment(QtCore.Qt.AlignCenter)
        self.iconTotal.setObjectName("iconTotal")
        self.verticalLayout_3.addWidget(self.iconTotal)
        self.lblTotalStok = QtWidgets.QLabel(self.cardTotalStok)
        self.lblTotalStok.setStyleSheet("font-size: 14px; color: #666;")
        self.lblTotalStok.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTotalStok.setObjectName("lblTotalStok")
        self.verticalLayout_3.addWidget(self.lblTotalStok)
        self.valueTotalStok = QtWidgets.QLabel(self.cardTotalStok)
        self.valueTotalStok.setStyleSheet("font-size: 36px; font-weight: bold; color: #750003;")
        self.valueTotalStok.setAlignment(QtCore.Qt.AlignCenter)
        self.valueTotalStok.setObjectName("valueTotalStok")
        self.verticalLayout_3.addWidget(self.valueTotalStok)
        self.lblKantong = QtWidgets.QLabel(self.cardTotalStok)
        self.lblKantong.setStyleSheet("font-size: 12px; color: #999;")
        self.lblKantong.setAlignment(QtCore.Qt.AlignCenter)
        self.lblKantong.setObjectName("lblKantong")
        self.verticalLayout_3.addWidget(self.lblKantong)
        self.summaryLayout.addWidget(self.cardTotalStok)
        self.cardStokAman = QtWidgets.QFrame(self.stokPage)
        self.cardStokAman.setStyleSheet("\n"
"QFrame#cardStokAman {\n"
"    background-color: white;\n"
"    border: 2px solid #4CAF50;\n"
"}\n"
"            ")
        self.cardStokAman.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cardStokAman.setObjectName("cardStokAman")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.cardStokAman)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.iconAman = QtWidgets.QLabel(self.cardStokAman)
        self.iconAman.setStyleSheet("font-size: 48px; color: #4CAF50;")
        self.iconAman.setAlignment(QtCore.Qt.AlignCenter)
        self.iconAman.setObjectName("iconAman")
        self.verticalLayout_4.addWidget(self.iconAman)
        self.lblStokAman = QtWidgets.QLabel(self.cardStokAman)
        self.lblStokAman.setStyleSheet("font-size: 14px; color: #666;")
        self.lblStokAman.setAlignment(QtCore.Qt.AlignCenter)
        self.lblStokAman.setObjectName("lblStokAman")
        self.verticalLayout_4.addWidget(self.lblStokAman)
        self.valueStokAman = QtWidgets.QLabel(self.cardStokAman)
        self.valueStokAman.setStyleSheet("font-size: 36px; font-weight: bold; color: #4CAF50;")
        self.valueStokAman.setAlignment(QtCore.Qt.AlignCenter)
        self.valueStokAman.setObjectName("valueStokAman")
        self.verticalLayout_4.addWidget(self.valueStokAman)
        self.lblGolAman = QtWidgets.QLabel(self.cardStokAman)
        self.lblGolAman.setStyleSheet("font-size: 12px; color: #999;")
        self.lblGolAman.setAlignment(QtCore.Qt.AlignCenter)
        self.lblGolAman.setObjectName("lblGolAman")
        self.verticalLayout_4.addWidget(self.lblGolAman)
        self.summaryLayout.addWidget(self.cardStokAman)
        self.cardStokKritis = QtWidgets.QFrame(self.stokPage)
        self.cardStokKritis.setStyleSheet("\n"
"QFrame#cardStokKritis {\n"
"    background-color: white;\n"
"    border: 2px solid #FF9800;\n"
"}\n"
"            ")
        self.cardStokKritis.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cardStokKritis.setObjectName("cardStokKritis")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.cardStokKritis)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.iconKritis = QtWidgets.QLabel(self.cardStokKritis)
        self.iconKritis.setStyleSheet("font-size: 48px; color: #FF9800;")
        self.iconKritis.setAlignment(QtCore.Qt.AlignCenter)
        self.iconKritis.setObjectName("iconKritis")
        self.verticalLayout_5.addWidget(self.iconKritis)
        self.lblStokKritis = QtWidgets.QLabel(self.cardStokKritis)
        self.lblStokKritis.setStyleSheet("font-size: 14px; color: #666;")
        self.lblStokKritis.setAlignment(QtCore.Qt.AlignCenter)
        self.lblStokKritis.setObjectName("lblStokKritis")
        self.verticalLayout_5.addWidget(self.lblStokKritis)
        self.valueStokKritis = QtWidgets.QLabel(self.cardStokKritis)
        self.valueStokKritis.setStyleSheet("font-size: 36px; font-weight: bold; color: #FF9800;")
        self.valueStokKritis.setAlignment(QtCore.Qt.AlignCenter)
        self.valueStokKritis.setObjectName("valueStokKritis")
        self.verticalLayout_5.addWidget(self.valueStokKritis)
        self.lblGolKritis = QtWidgets.QLabel(self.cardStokKritis)
        self.lblGolKritis.setStyleSheet("font-size: 12px; color: #999;")
        self.lblGolKritis.setAlignment(QtCore.Qt.AlignCenter)
        self.lblGolKritis.setObjectName("lblGolKritis")
        self.verticalLayout_5.addWidget(self.lblGolKritis)
        self.summaryLayout.addWidget(self.cardStokKritis)
        self.cardKadaluarsa = QtWidgets.QFrame(self.stokPage)
        self.cardKadaluarsa.setStyleSheet("\n"
"QFrame#cardKadaluarsa {\n"
"    background-color: white;\n"
"    border: 2px solid #F44336;\n"
"}\n"
"            ")
        self.cardKadaluarsa.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cardKadaluarsa.setObjectName("cardKadaluarsa")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.cardKadaluarsa)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.iconKadaluarsa = QtWidgets.QLabel(self.cardKadaluarsa)
        self.iconKadaluarsa.setStyleSheet("font-size: 48px; color: #F44336;")
        self.iconKadaluarsa.setAlignment(QtCore.Qt.AlignCenter)
        self.iconKadaluarsa.setObjectName("iconKadaluarsa")
        self.verticalLayout_6.addWidget(self.iconKadaluarsa)
        self.lblKadaluarsa = QtWidgets.QLabel(self.cardKadaluarsa)
        self.lblKadaluarsa.setStyleSheet("font-size: 14px; color: #666;")
        self.lblKadaluarsa.setAlignment(QtCore.Qt.AlignCenter)
        self.lblKadaluarsa.setObjectName("lblKadaluarsa")
        self.verticalLayout_6.addWidget(self.lblKadaluarsa)
        self.valueKadaluarsa = QtWidgets.QLabel(self.cardKadaluarsa)
        self.valueKadaluarsa.setStyleSheet("font-size: 36px; font-weight: bold; color: #F44336;")
        self.valueKadaluarsa.setAlignment(QtCore.Qt.AlignCenter)
        self.valueKadaluarsa.setObjectName("valueKadaluarsa")
        self.verticalLayout_6.addWidget(self.valueKadaluarsa)
        self.lblKantongKadaluarsa = QtWidgets.QLabel(self.cardKadaluarsa)
        self.lblKantongKadaluarsa.setStyleSheet("font-size: 12px; color: #999;")
        self.lblKantongKadaluarsa.setAlignment(QtCore.Qt.AlignCenter)
        self.lblKantongKadaluarsa.setObjectName("lblKantongKadaluarsa")
        self.verticalLayout_6.addWidget(self.lblKantongKadaluarsa)
        self.summaryLayout.addWidget(self.cardKadaluarsa)
        self.verticalLayout_2.addLayout(self.summaryLayout)
        self.frameStokDetail = QtWidgets.QFrame(self.stokPage)
        self.frameStokDetail.setStyleSheet("\n"
"QFrame#frameStokDetail {\n"
"    background-color: white;\n"
"    border: 1px solid #ddd;\n"
"}\n"
"          ")
        self.frameStokDetail.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameStokDetail.setObjectName("frameStokDetail")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frameStokDetail)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.lblDetailStok = QtWidgets.QLabel(self.frameStokDetail)
        self.lblDetailStok.setStyleSheet("font-size: 18px; font-weight: bold; color: #750003; padding: 10px;")
        self.lblDetailStok.setObjectName("lblDetailStok")
        self.verticalLayout_7.addWidget(self.lblDetailStok)
        self.tableStok = QtWidgets.QTableWidget(self.frameStokDetail)
        self.tableStok.setStyleSheet("\n"
"QTableWidget {\n"
"    border: none;\n"
"    background-color: white;\n"
"    gridline-color: #f0f0f0;\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #750003;\n"
"    color: white;\n"
"    padding: 12px;\n"
"    border: none;\n"
"    font-weight: bold;\n"
"    font-size: 13px;\n"
"}\n"
"QTableWidget::item {\n"
"    padding: 10px;\n"
"    border-bottom: 1px solid #f0f0f0;\n"
"}\n"
"QTableWidget::item:selected {\n"
"    background-color: #fff0f0;\n"
"    color: #750003;\n"
"}\n"
"             ")
        self.tableStok.setAlternatingRowColors(True)
        self.tableStok.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableStok.setObjectName("tableStok")
        self.tableStok.setColumnCount(6)
        self.tableStok.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableStok.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableStok.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableStok.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableStok.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableStok.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableStok.setHorizontalHeaderItem(5, item)
        self.verticalLayout_7.addWidget(self.tableStok)
        self.verticalLayout_2.addWidget(self.frameStokDetail)
        self.verticalLayout.addWidget(self.stokPage)
        MainWindow.setCentralWidget(self.centralwidget)
        self.btnRefresh.clicked.connect(self.load_stok_data)
        self.btnValidasi.clicked.connect(self.tampilkan_validasi)
        self.btnTransaksi.clicked.connect(self.tampil_transaksi)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
    def load_stok_data(self):
        self.valueTotalStok.setText(f"{get_total_stok()} Kantong")
        self.valueKadaluarsa.setText(f"{get_stok_kadaluarsa()} Kantong")
        self.valueStokKritis.setText(f"{get_stok_kritis()} Golongan")
        items = laporan_darah()
        self.tableStok.setRowCount(0)
        for row_number, row_data in enumerate(items):
            self.tableStok.insertRow(row_number)
            for column_number, data in enumerate(row_data):
                self.tableStok.setItem(row_number, column_number, QTableWidgetItem(str(data)))
                
                
    def tampilkan_validasi(self):
        import validasi 
        self.validasiWindow = QtWidgets.QMainWindow()
        self.validasiUI = validasi.Ui_MainWindow()
        self.validasiUI.setupUi(self.validasiWindow)
        self.validasiWindow.show()
        self.Mainwindow.hide()
        
    def tampil_transaksi(self):
        import transaksidarah
        self.transaksiWindow = QtWidgets.QMainWindow
        self.transaksiUI = transaksidarah.Ui_MainWindow()
        self.transaksiUI.setupUi(self.transaksiWindow)
        self.transaksiWindow.show()
        
    def balik_dashboard(self):
        import dasboardpetugas
        self.dashboardwindow = QtWidgets.QMainWindow()
        self.ui = dasboardpetugas.Ui_MainWindow()
        self.ui.set_petugas(self.id_petugas)
        self.ui.setupUi(self.dashboardwindow)
        self.dashboardwindow.show()
        self.Mainwindow.close()


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dashboard PMI - Stok Darah"))
        self.logoLabel.setText(_translate("MainWindow", "PMI DONOR DARAH"))
        self.btnDashboard.setText(_translate("MainWindow", "Dashboard"))
        self.btnTransaksi.setText(_translate("MainWindow", "Transaksi Darah"))
        self.btnStok.setText(_translate("MainWindow", "Stok Darah"))
        self.btnValidasi.setText(_translate("MainWindow", "Validasi Permintaan"))
        self.btnLaporan.setText(_translate("MainWindow", "Laporan"))
        self.titleLabel.setText(_translate("MainWindow", "Stok Darah"))
        self.btnRefresh.setText(_translate("MainWindow", "🔄 Refresh"))
        self.iconTotal.setText(_translate("MainWindow", "📦"))
        self.lblTotalStok.setText(_translate("MainWindow", "Total Stok"))
        self.valueTotalStok.setText(_translate("MainWindow", "328"))
        self.lblKantong.setText(_translate("MainWindow", "kantong darah"))
        self.iconAman.setText(_translate("MainWindow", "✓"))
        self.lblStokAman.setText(_translate("MainWindow", "Stok Aman"))
        self.valueStokAman.setText(_translate("MainWindow", "3"))
        self.lblGolAman.setText(_translate("MainWindow", "golongan darah"))
        self.iconKritis.setText(_translate("MainWindow", "⚠"))
        self.lblStokKritis.setText(_translate("MainWindow", "Stok Kritis"))
        self.valueStokKritis.setText(_translate("MainWindow", "1"))
        self.lblGolKritis.setText(_translate("MainWindow", "golongan darah"))
        self.iconKadaluarsa.setText(_translate("MainWindow", "⏰"))
        self.lblKadaluarsa.setText(_translate("MainWindow", "Hampir Kadaluarsa"))
        self.valueKadaluarsa.setText(_translate("MainWindow", "8"))
        self.lblKantongKadaluarsa.setText(_translate("MainWindow", "kantong (<7 hari)"))
        self.lblDetailStok.setText(_translate("MainWindow", "Detail Stok per Golongan Darah"))
        item = self.tableStok.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Golongan Darah"))
        item = self.tableStok.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Rhesus"))
        item = self.tableStok.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Jumlah Kantong"))
        item = self.tableStok.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Status"))
        item = self.tableStok.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Kadaluarsa <7 Hari"))
        item = self.tableStok.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Terakhir Update"))
        self.load_stok_data()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
