# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(568, 740)
        Dialog.setStyleSheet("/* ====== GLOBAL ====== */\n"
"QWidget {\n"
"    font-family: \'Segoe UI\';\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"/* ====== LABEL ====== */\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"    font-size: 17px;\n"
"    font-weight: 500;\n"
"}\n"
"\n"
"/* Hilangkan underline & warna biru pada QLabel */\n"
"QLabel {\n"
"    text-decoration: none;\n"
"    color: white;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background: rgba(255,255,255,0.9);\n"
"    border: 2px solid transparent;\n"
"    border-radius: 12px;\n"
"    padding: 10px 14px;\n"
"    font-size: 16px;\n"
"\n"
"    /* simple shadow */\n"
"    box-shadow: 0px 4px 12px rgba(0,0,0,0.35);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #D50000;\n"
"    background: rgba(255,255,255,1);\n"
"    box-shadow: 0px 6px 18px rgba(0,0,0,0.45);\n"
"}\n"
"\n"
"/* ====== PUSH BUTTON (Login, Daftar, dll) ====== */\n"
"QPushButton {\n"
"    background-color: #D50000;\n"
"    color: white;\n"
"    border-radius: 14px;\n"
"    padding: 12px 20px;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"\n"
"    /* Drop shadow simple */\n"
"    box-shadow: 0px 4px 10px rgba(0,0,0,0.35);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #b40000;\n"
"    box-shadow: 0px 6px 14px rgba(0,0,0,0.45);\n"
"}\n"
"#pushButton {\n"
"    background-color: #D50000;\n"
"    color: white;\n"
"    border-radius: 14px;\n"
"    padding: 12px 20px;\n"
"    border: none;\n"
"    font-size: 17px;\n"
"    font-weight: bold;\n"
"\n"
"    /* Shadow */\n"
"    box-shadow: 0px 5px 16px rgba(0,0,0,0.40);\n"
"}\n"
"\n"
"#pushButton:hover {\n"
"    background-color: #b40000;\n"
"    box-shadow: 0px 7px 20px rgba(0,0,0,0.50);\n"
"    letter-spacing: 1px; /* efek modern */\n"
"}\n"
"\n"
"#pushButton:pressed {\n"
"    background-color: #8e0000;\n"
"    box-shadow: 0px 3px 10px rgba(0,0,0,0.30);\n"
"    padding-top: 14px;\n"
"    padding-bottom: 10px;\n"
"}\n"
"\n"
"#pushButton_2 {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: #1E88E5;\n"
"    font-size: 16px;\n"
"    text-decoration: underline;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"#pushButton_2:hover {\n"
"    color: #64B5F6;\n"
"    cursor: pointer;\n"
"    text-decoration: underline;\n"
"    letter-spacing: 0.5px;\n"
"}\n"
"\n"
"#pushButton_2:pressed {\n"
"    color: #0D47A1;\n"
"}\n"
"")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(5, 5, 566, 691))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(5, 0, 526, 676))
        self.label.setStyleSheet("QLabel {\n"
"    background-color: rgba(0, 0, 0, 150);\n"
"    border-radius: 20px;\n"
"}\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(5, 0, 526, 676))
        self.label_2.setStyleSheet("QLabel {\n"
"    \n"
"    border-image: url(:/gambar/pexels-charliehelenrobinson-4531306.jpg);\n"
"    background-color: rgba(220, 0, 0, 60);\n"
"    border-radius: 20px;\n"
"}\n"
"")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(5, 0, 526, 676))
        self.label_3.setStyleSheet("QLabel {\n"
"    background-color: rgba(60, 0, 0, 110);\n"
"    border-radius: 20px;\n"
"}\n"
"")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(160, 70, 231, 96))
        self.label_4.setStyleSheet("border-image: url(:/blood/pngtree-indonesian-red-cross-pmi-logo-vector-png-image_12258331.png);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(230, 175, 96, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(87)
        font.setStrikeOut(False)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("#label_5 {\n"
"    color: #FFFFFF;\n"
"    font-size: 28px;\n"
"    font-weight: 700;\n"
"    letter-spacing: 1px;\n"
"    text-transform: uppercase;\n"
"\n"
"    /* Shadow agar terlihat jelas di background */\n"
"    text-shadow: 0px 4px 12px rgba(0, 0, 0, 0.45);\n"
"}\n"
"")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(90, 245, 96, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(62)
        font.setStrikeOut(False)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setGeometry(QtCore.QRect(100, 280, 361, 41))
        self.lineEdit.setStyleSheet("background-color: rgba(0, 0, 0, 0.50);")
        self.lineEdit.setObjectName("lineEdit")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(85, 345, 96, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(62)
        font.setStrikeOut(False)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(90, 460, 361, 46))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(165, 510, 161, 26))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(62)
        font.setStrikeOut(False)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(305, 500, 96, 46))
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_3.setGeometry(QtCore.QRect(95, 275, 361, 41))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setGeometry(QtCore.QRect(100, 380, 361, 41))
        self.lineEdit_2.setStyleSheet("background-color: rgba(0, 0, 0, 0.50);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_4.setGeometry(QtCore.QRect(95, 375, 361, 41))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_2.raise_()
        self.label.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.lineEdit.raise_()
        self.label_7.raise_()
        self.pushButton.raise_()
        self.label_8.raise_()
        self.pushButton_2.raise_()
        self.lineEdit_3.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit_4.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_5.setText(_translate("Dialog", "LOGIN"))
        self.label_6.setText(_translate("Dialog", "Username:"))
        self.label_7.setText(_translate("Dialog", "Password:"))
        self.pushButton.setText(_translate("Dialog", "Login"))
        self.label_8.setText(_translate("Dialog", "Belum Punya akun?"))
        self.pushButton_2.setText(_translate("Dialog", "Daftar"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
