# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login1.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from USER import login_user




class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        self.loginWindow = LoginWindow
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(1000, 758)
        LoginWindow.setStyleSheet("\n"
"QMainWindow {\n"
"    background-color: #f5f5f5;\n"
"}\n"
"QPushButton {\n"
"    border: none;\n"
"    padding: 10px 20px;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    opacity: 0.8;\n"
"}\n"
"QFrame {\n"
"    border-radius: 10px;\n"
"}\n"
"QLabel {\n"
"    color: #333333;\n"
"}\n"
"QLineEdit {\n"
"    padding: 12px 15px;\n"
"    border: 2px solid #ddd;\n"
"    border-radius: 8px;\n"
"    font-size: 14px;\n"
"    background-color: white;\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #750003;\n"
"}\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.mainLayout.setContentsMargins(0, 0, 0, 0)
        self.mainLayout.setSpacing(0)
        self.mainLayout.setObjectName("mainLayout")
        self.leftPanel = QtWidgets.QFrame(self.centralwidget)
        self.leftPanel.setMinimumSize(QtCore.QSize(500, 0))
        self.leftPanel.setStyleSheet("\n"
"QFrame#leftPanel {\n"
"    background-color: #750003;\n"
"}\n"
"QLabel {\n"
"    color: white;\n"
"}\n"
"       ")
        self.leftPanel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftPanel.setObjectName("leftPanel")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.leftPanel)
        self.verticalLayout.setContentsMargins(50, 80, 50, 80)
        self.verticalLayout.setSpacing(30)
        self.verticalLayout.setObjectName("verticalLayout")
        self.logoIcon = QtWidgets.QLabel(self.leftPanel)
        self.logoIcon.setStyleSheet("font-size: 80px;")
        self.logoIcon.setAlignment(QtCore.Qt.AlignCenter)
        self.logoIcon.setObjectName("logoIcon")
        self.verticalLayout.addWidget(self.logoIcon)
        self.appTitle = QtWidgets.QLabel(self.leftPanel)
        self.appTitle.setStyleSheet("font-size: 32px; font-weight: bold;")
        self.appTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.appTitle.setObjectName("appTitle")
        self.verticalLayout.addWidget(self.appTitle)
        self.tagline = QtWidgets.QLabel(self.leftPanel)
        self.tagline.setStyleSheet("font-size: 18px; color: rgba(255, 255, 255, 0.9);")
        self.tagline.setAlignment(QtCore.Qt.AlignCenter)
        self.tagline.setWordWrap(True)
        self.tagline.setObjectName("tagline")
        self.verticalLayout.addWidget(self.tagline)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.infoText = QtWidgets.QLabel(self.leftPanel)
        self.infoText.setStyleSheet("font-size: 14px; color: rgba(255, 255, 255, 0.8); line-height: 1.6;")
        self.infoText.setAlignment(QtCore.Qt.AlignCenter)
        self.infoText.setWordWrap(True)
        self.infoText.setObjectName("infoText")
        self.verticalLayout.addWidget(self.infoText)
        self.mainLayout.addWidget(self.leftPanel)
        self.rightPanel = QtWidgets.QFrame(self.centralwidget)
        self.rightPanel.setStyleSheet("\n"
"QFrame#rightPanel {\n"
"    background-color: white;\n"
"}\n"
"       ")
        self.rightPanel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rightPanel.setObjectName("rightPanel")
        self.welcomeLabel = QtWidgets.QLabel(self.rightPanel)
        self.welcomeLabel.setGeometry(QtCore.QRect(60, 80, 252, 44))
        self.welcomeLabel.setStyleSheet("font-size: 28px; font-weight: bold; color: #750003; margin-bottom: 10px;")
        self.welcomeLabel.setObjectName("welcomeLabel")
        self.subtitleLabel = QtWidgets.QLabel(self.rightPanel)
        self.subtitleLabel.setGeometry(QtCore.QRect(60, 124, 290, 57))
        self.subtitleLabel.setStyleSheet("font-size: 14px; color: #666; margin-bottom: 40px;")
        self.subtitleLabel.setObjectName("subtitleLabel")
        self.lblNIK = QtWidgets.QLabel(self.rightPanel)
        self.lblNIK.setGeometry(QtCore.QRect(60, 181, 168, 45))
        self.lblNIK.setStyleSheet("font-size: 14px; font-weight: bold; color: #333; margin-top: 20px; margin-bottom: 8px;")
        self.lblNIK.setObjectName("lblNIK")
        self.inputNIK = QtWidgets.QLineEdit(self.rightPanel)
        self.inputNIK.setGeometry(QtCore.QRect(60, 226, 386, 47))
        self.inputNIK.setObjectName("inputNIK")
        self.lblPassword = QtWidgets.QLabel(self.rightPanel)
        self.lblPassword.setGeometry(QtCore.QRect(60, 273, 76, 45))
        self.lblPassword.setStyleSheet("font-size: 14px; font-weight: bold; color: #333; margin-top: 20px; margin-bottom: 8px;")
        self.lblPassword.setObjectName("lblPassword")
        self.inputPassword = QtWidgets.QLineEdit(self.rightPanel)
        self.inputPassword.setGeometry(QtCore.QRect(60, 318, 386, 47))
        self.inputPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.inputPassword.setObjectName("inputPassword")
        self.btnLogin = QtWidgets.QPushButton(self.rightPanel)
        self.btnLogin.setGeometry(QtCore.QRect(60, 407, 380, 81))
        self.btnLogin.setMinimumSize(QtCore.QSize(0, 45))
        self.btnLogin.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: #750003;\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    margin-top: 25px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #a00004;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #5a0002;\n"
"}\n"
"          ")
        self.btnLogin.setObjectName("btnLogin")
        self.registerFrame = QtWidgets.QFrame(self.rightPanel)
        self.registerFrame.setGeometry(QtCore.QRect(65, 530, 380, 156))
        self.registerFrame.setStyleSheet("\n"
"QFrame {\n"
"    background-color: #f9f9f9;\n"
"    border: 1px solid #e0e0e0;\n"
"    border-radius: 8px;\n"
"    padding: 20px;\n"
"}\n"
"          ")
        self.registerFrame.setObjectName("registerFrame")
        self.lblBelumPunya = QtWidgets.QLabel(self.registerFrame)
        self.lblBelumPunya.setGeometry(QtCore.QRect(27, 27, 326, 58))
        self.lblBelumPunya.setStyleSheet("font-size: 13px; color: #666; text-align: center;")
        self.lblBelumPunya.setAlignment(QtCore.Qt.AlignCenter)
        self.lblBelumPunya.setObjectName("lblBelumPunya")
        self.btnDaftar = QtWidgets.QPushButton(self.registerFrame)
        self.btnDaftar.setGeometry(QtCore.QRect(27, 89, 326, 61))
        self.btnDaftar.setMinimumSize(QtCore.QSize(0, 40))
        self.btnDaftar.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: white;\n"
"    color: #750003;\n"
"    border: 2px solid #750003;\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"    margin-top: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #750003;\n"
"    color: white;\n"
"}\n"
"             ")
        self.btnDaftar.setObjectName("btnDaftar")
        self.layoutWidget = QtWidgets.QWidget(self.rightPanel)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 365, 386, 42))
        self.layoutWidget.setObjectName("layoutWidget")
        self.optionsLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.optionsLayout.setContentsMargins(0, 15, 0, 0)
        self.optionsLayout.setObjectName("optionsLayout")
        self.checkRemember = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkRemember.setStyleSheet("\n"
"QCheckBox {\n"
"    font-size: 13px;\n"
"    color: #666;\n"
"}\n"
"QCheckBox::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border: 2px solid #ddd;\n"
"    border-radius: 4px;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #750003;\n"
"    border-color: #750003;\n"
"}\n"
"            ")
        self.checkRemember.setObjectName("checkRemember")
        self.optionsLayout.addWidget(self.checkRemember)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.optionsLayout.addItem(spacerItem1)
        self.btnLupaPassword = QtWidgets.QPushButton(self.layoutWidget)
        self.btnLupaPassword.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: transparent;\n"
"    color: #750003;\n"
"    text-decoration: underline;\n"
"    font-size: 13px;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    color: #a00004;\n"
"}\n"
"            ")
        self.btnLupaPassword.setObjectName("btnLupaPassword")
        self.optionsLayout.addWidget(self.btnLupaPassword)
        self.mainLayout.addWidget(self.rightPanel)
        LoginWindow.setCentralWidget(self.centralwidget)
        self.btnLogin.clicked.connect(self.login)
        self.btnDaftar.clicked.connect(self.open_registrasi)
        self.btnLupaPassword.clicked.connect(self.open_registrasi)


        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)
        
    def open_registrasi(self):
        import daftar_akun_pendonor
        self.registrasiWindow = QtWidgets.QMainWindow()
        self.registrasiUI = daftar_akun_pendonor.Ui_SignUpWindow()
        self.registrasiUI.setupUi(self.registrasiWindow)
        self.registrasiWindow.show()
        self.loginWindow.close()
        
    
    def login(self):
        nik = self.inputNIK.text()
        password = self.inputPassword.text()

        success, result = login_user(nik, password)

        if success:
            role = result['role_id']
            id_user = result['id_pendonor']

            if role == 1:  # pendonor
                self.open_dashboard(id_user)
            elif role == 3:  # petugas PMI
                self.open_dashboard_petugas_pmi(id_user)
            elif role == 2:
                from USER import get_id_rs_by_pengguna
                id_rs = get_id_rs_by_pengguna(id_user)
                
                if id_rs is None:
                    QMessageBox.warning(
                        self.loginWindow,
                        "Error",
                        "Akun belum terdaftar sebagai Rumah Sakit"
                    )
                    return
            
                self.open_dashboard_petugas_rs(id_user)
            else:
                 QMessageBox.warning(self.loginWindow, "Gagal", result)

                
    def open_dashboard(self, id_user):
        import dasboardpendonor
        self.dashboardWindow = QtWidgets.QMainWindow()
        self.dashboardUI = dasboardpendonor.Ui_DonorDashboard()
        self.dashboardUI.setupUi(self.dashboardWindow)

        # kirim data login
        self.dashboardUI.set_pendonor(id_user)

        self.dashboardWindow.show()
        self.loginWindow.close()
        
    def open_dashboard_petugas_pmi(self, id_user):
        import dasboardpetugas
        self.dashboardWindow = QtWidgets.QMainWindow()
        self.dashboardUI = dasboardpetugas.Ui_MainWindow()
        self.dashboardUI.setupUi(self.dashboardWindow)
        self.dashboardUI.set_petugas(id_user)
        self.dashboardWindow.show()
        self.loginWindow.close()
        
    def open_dashboard_petugas_rs(self, id_user):
        import dashboardrumahsakit
        self.dashboardWindow = QtWidgets.QMainWindow()
        self.dashboardUI = dashboardrumahsakit.Ui_MainWindow()
        self.dashboardUI.setupUi(self.dashboardWindow)
        self.dashboardUI.set_petugas(id_user)
        self.dashboardWindow.show()
        self.loginWindow.close()


        
    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "Login - PMI Donor Darah"))
        self.logoIcon.setText(_translate("LoginWindow", "🩸"))
        self.appTitle.setText(_translate("LoginWindow", "PMI DONOR DARAH"))
        self.tagline.setText(_translate("LoginWindow", "Setetes Darahmu, Sejuta Harapan"))
        self.infoText.setText(_translate("LoginWindow", "Bergabunglah dengan ribuan donor yang telah menyelamatkan nyawa. Bersama kita wujudkan Indonesia sehat."))
        self.welcomeLabel.setText(_translate("LoginWindow", "Selamat Datang!"))
        self.subtitleLabel.setText(_translate("LoginWindow", "Masuk untuk melanjutkan ke dashboard Anda"))
        self.lblNIK.setText(_translate("LoginWindow", "NIK / Nomor Identitas"))
        self.inputNIK.setPlaceholderText(_translate("LoginWindow", "Masukkan NIK Anda"))
        self.lblPassword.setText(_translate("LoginWindow", "Password"))
        self.inputPassword.setPlaceholderText(_translate("LoginWindow", "Masukkan password Anda"))
        self.checkRemember.setText(_translate("LoginWindow", "Ingat saya"))
        self.btnLupaPassword.setText(_translate("LoginWindow", "Lupa Password?"))
        self.btnLogin.setText(_translate("LoginWindow", "Masuk"))
        self.lblBelumPunya.setText(_translate("LoginWindow", "Belum punya akun?"))
        self.btnDaftar.setText(_translate("LoginWindow", "Daftar Sekarang"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginWindow = QtWidgets.QMainWindow()
    ui = Ui_LoginWindow()
    ui.setupUi(LoginWindow)
    LoginWindow.show()
    sys.exit(app.exec_())
