# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login1.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from USER import login_pendonor
from dasboardpendonor import Ui_DonorDashboard


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        self.loginWindow = LoginWindow
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(1000, 650)
        LoginWindow.setStyleSheet("\n"
"QMainWindow {\n"
"    background-color: #f5f5f5;\n"
"}\n"
"QPushButton {\n"
"    border: none;\n"
"    padding: 10px 20px;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    opacity: 0.8;\n"
"}\n"
"QFrame {\n"
"    border-radius: 10px;\n"
"}\n"
"QLabel {\n"
"    color: #333333;\n"
"}\n"
"QLineEdit {\n"
"    padding: 12px 15px;\n"
"    border: 2px solid #ddd;\n"
"    border-radius: 8px;\n"
"    font-size: 14px;\n"
"    background-color: white;\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #750003;\n"
"}\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.mainLayout.setContentsMargins(0, 0, 0, 0)
        self.mainLayout.setSpacing(0)
        self.mainLayout.setObjectName("mainLayout")
        self.leftPanel = QtWidgets.QFrame(self.centralwidget)
        self.leftPanel.setMinimumSize(QtCore.QSize(500, 0))
        self.leftPanel.setStyleSheet("\n"
"QFrame#leftPanel {\n"
"    background-color: #750003;\n"
"}\n"
"QLabel {\n"
"    color: white;\n"
"}\n"
"       ")
        self.leftPanel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftPanel.setObjectName("leftPanel")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.leftPanel)
        self.verticalLayout.setContentsMargins(50, 80, 50, 80)
        self.verticalLayout.setSpacing(30)
        self.verticalLayout.setObjectName("verticalLayout")
        self.logoIcon = QtWidgets.QLabel(self.leftPanel)
        self.logoIcon.setStyleSheet("font-size: 80px;")
        self.logoIcon.setAlignment(QtCore.Qt.AlignCenter)
        self.logoIcon.setObjectName("logoIcon")
        self.verticalLayout.addWidget(self.logoIcon)
        self.appTitle = QtWidgets.QLabel(self.leftPanel)
        self.appTitle.setStyleSheet("font-size: 32px; font-weight: bold;")
        self.appTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.appTitle.setObjectName("appTitle")
        self.verticalLayout.addWidget(self.appTitle)
        self.tagline = QtWidgets.QLabel(self.leftPanel)
        self.tagline.setStyleSheet("font-size: 18px; color: rgba(255, 255, 255, 0.9);")
        self.tagline.setAlignment(QtCore.Qt.AlignCenter)
        self.tagline.setWordWrap(True)
        self.tagline.setObjectName("tagline")
        self.verticalLayout.addWidget(self.tagline)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.infoText = QtWidgets.QLabel(self.leftPanel)
        self.infoText.setStyleSheet("font-size: 14px; color: rgba(255, 255, 255, 0.8); line-height: 1.6;")
        self.infoText.setAlignment(QtCore.Qt.AlignCenter)
        self.infoText.setWordWrap(True)
        self.infoText.setObjectName("infoText")
        self.verticalLayout.addWidget(self.infoText)
        self.mainLayout.addWidget(self.leftPanel)
        self.rightPanel = QtWidgets.QFrame(self.centralwidget)
        self.rightPanel.setStyleSheet("\n"
"QFrame#rightPanel {\n"
"    background-color: white;\n"
"}\n"
"       ")
        self.rightPanel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rightPanel.setObjectName("rightPanel")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.rightPanel)
        self.verticalLayout_2.setContentsMargins(60, 80, 60, 80)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.welcomeLabel = QtWidgets.QLabel(self.rightPanel)
        self.welcomeLabel.setStyleSheet("font-size: 28px; font-weight: bold; color: #750003; margin-bottom: 10px;")
        self.welcomeLabel.setObjectName("welcomeLabel")
        self.verticalLayout_2.addWidget(self.welcomeLabel)
        self.subtitleLabel = QtWidgets.QLabel(self.rightPanel)
        self.subtitleLabel.setStyleSheet("font-size: 14px; color: #666; margin-bottom: 40px;")
        self.subtitleLabel.setObjectName("subtitleLabel")
        self.verticalLayout_2.addWidget(self.subtitleLabel)
        self.lblNIK = QtWidgets.QLabel(self.rightPanel)
        self.lblNIK.setStyleSheet("font-size: 14px; font-weight: bold; color: #333; margin-top: 20px; margin-bottom: 8px;")
        self.lblNIK.setObjectName("lblNIK")
        self.verticalLayout_2.addWidget(self.lblNIK)
        self.inputNIK = QtWidgets.QLineEdit(self.rightPanel)
        self.inputNIK.setObjectName("inputNIK")
        self.verticalLayout_2.addWidget(self.inputNIK)
        self.lblPassword = QtWidgets.QLabel(self.rightPanel)
        self.lblPassword.setStyleSheet("font-size: 14px; font-weight: bold; color: #333; margin-top: 20px; margin-bottom: 8px;")
        self.lblPassword.setObjectName("lblPassword")
        self.verticalLayout_2.addWidget(self.lblPassword)
        self.inputPassword = QtWidgets.QLineEdit(self.rightPanel)
        self.inputPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.inputPassword.setObjectName("inputPassword")
        self.verticalLayout_2.addWidget(self.inputPassword)
        self.optionsLayout = QtWidgets.QHBoxLayout()
        self.optionsLayout.setContentsMargins(-1, 15, -1, -1)
        self.optionsLayout.setObjectName("optionsLayout")
        self.checkRemember = QtWidgets.QCheckBox(self.rightPanel)
        self.checkRemember.setStyleSheet("\n"
"QCheckBox {\n"
"    font-size: 13px;\n"
"    color: #666;\n"
"}\n"
"QCheckBox::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border: 2px solid #ddd;\n"
"    border-radius: 4px;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #750003;\n"
"    border-color: #750003;\n"
"}\n"
"            ")
        self.checkRemember.setObjectName("checkRemember")
        self.optionsLayout.addWidget(self.checkRemember)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.optionsLayout.addItem(spacerItem1)
        self.btnLupaPassword = QtWidgets.QPushButton(self.rightPanel)
        self.btnLupaPassword.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: transparent;\n"
"    color: #750003;\n"
"    text-decoration: underline;\n"
"    font-size: 13px;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    color: #a00004;\n"
"}\n"
"            ")
        self.btnLupaPassword.setObjectName("btnLupaPassword")
        self.optionsLayout.addWidget(self.btnLupaPassword)
        self.verticalLayout_2.addLayout(self.optionsLayout)
        self.btnLogin = QtWidgets.QPushButton(self.rightPanel)
        self.btnLogin.setMinimumSize(QtCore.QSize(0, 45))
        self.btnLogin.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: #750003;\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    margin-top: 25px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #a00004;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #5a0002;\n"
"}\n"
"          ")
        self.btnLogin.setObjectName("btnLogin")
        self.verticalLayout_2.addWidget(self.btnLogin)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.registerFrame = QtWidgets.QFrame(self.rightPanel)
        self.registerFrame.setStyleSheet("\n"
"QFrame {\n"
"    background-color: #f9f9f9;\n"
"    border: 1px solid #e0e0e0;\n"
"    border-radius: 8px;\n"
"    padding: 20px;\n"
"}\n"
"          ")
        self.registerFrame.setObjectName("registerFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.registerFrame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lblBelumPunya = QtWidgets.QLabel(self.registerFrame)
        self.lblBelumPunya.setStyleSheet("font-size: 13px; color: #666; text-align: center;")
        self.lblBelumPunya.setAlignment(QtCore.Qt.AlignCenter)
        self.lblBelumPunya.setObjectName("lblBelumPunya")
        self.verticalLayout_3.addWidget(self.lblBelumPunya)
        self.btnDaftar = QtWidgets.QPushButton(self.registerFrame)
        self.btnDaftar.setMinimumSize(QtCore.QSize(0, 40))
        self.btnDaftar.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: white;\n"
"    color: #750003;\n"
"    border: 2px solid #750003;\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"    margin-top: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #750003;\n"
"    color: white;\n"
"}\n"
"             ")
        self.btnDaftar.setObjectName("btnDaftar")
        self.verticalLayout_3.addWidget(self.btnDaftar)
        self.verticalLayout_2.addWidget(self.registerFrame)
        self.mainLayout.addWidget(self.rightPanel)
        LoginWindow.setCentralWidget(self.centralwidget)
        self.btnLogin.clicked.connect(self.login)


        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)
        
    def login(self):
        nik = self.inputNIK.text()
        password = self.inputPassword.text()
        success, result = login_pendonor(nik, password)
        if success:
            QMessageBox.information(self.loginWindow, "Sukses", "Login berhasil!")
            self.open_dashboard(result)
        else:
            QMessageBox.warning(self.loginWindow, "Gagal", result)
                
    def open_dashboard(self, id_pendonor):
        self.dashboardWindow = QtWidgets.QMainWindow()
        self.dashboardUI = Ui_DonorDashboard()
        self.dashboardUI.setupUi(self.dashboardWindow)

        # kirim data login
        self.dashboardUI.set_pendonor(id_pendonor)

        self.dashboardWindow.show()
        self.loginWindow.close()


        
    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "Login - PMI Donor Darah"))
        self.logoIcon.setText(_translate("LoginWindow", "🩸"))
        self.appTitle.setText(_translate("LoginWindow", "PMI DONOR DARAH"))
        self.tagline.setText(_translate("LoginWindow", "Setetes Darahmu, Sejuta Harapan"))
        self.infoText.setText(_translate("LoginWindow", "Bergabunglah dengan ribuan donor yang telah menyelamatkan nyawa. Bersama kita wujudkan Indonesia sehat."))
        self.welcomeLabel.setText(_translate("LoginWindow", "Selamat Datang!"))
        self.subtitleLabel.setText(_translate("LoginWindow", "Masuk untuk melanjutkan ke dashboard Anda"))
        self.lblNIK.setText(_translate("LoginWindow", "NIK / Nomor Identitas"))
        self.inputNIK.setPlaceholderText(_translate("LoginWindow", "Masukkan NIK Anda"))
        self.lblPassword.setText(_translate("LoginWindow", "Password"))
        self.inputPassword.setPlaceholderText(_translate("LoginWindow", "Masukkan password Anda"))
        self.checkRemember.setText(_translate("LoginWindow", "Ingat saya"))
        self.btnLupaPassword.setText(_translate("LoginWindow", "Lupa Password?"))
        self.btnLogin.setText(_translate("LoginWindow", "Masuk"))
        self.lblBelumPunya.setText(_translate("LoginWindow", "Belum punya akun?"))
        self.btnDaftar.setText(_translate("LoginWindow", "Daftar Sekarang"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginWindow = QtWidgets.QMainWindow()
    ui = Ui_LoginWindow()
    ui.setupUi(LoginWindow)
    LoginWindow.show()
    sys.exit(app.exec_())
