# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mintadarah.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        MainWindow.setStyleSheet("\n"
"QMainWindow {\n"
"    background-color: #f5f5f5;\n"
"}\n"
"QPushButton {\n"
"    border: none;\n"
"    padding: 10px 20px;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    opacity: 0.8;\n"
"}\n"
"QFrame {\n"
"    border-radius: 10px;\n"
"}\n"
"QLabel {\n"
"    color: #333333;\n"
"}\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.navbar = QtWidgets.QFrame(self.centralwidget)
        self.navbar.setMinimumSize(QtCore.QSize(0, 70))
        self.navbar.setMaximumSize(QtCore.QSize(16777215, 70))
        self.navbar.setStyleSheet("\n"
"QFrame#navbar {\n"
"    background-color: #750003;\n"
"}\n"
"QPushButton {\n"
"    color: white;\n"
"    background-color: transparent;\n"
"    text-align: left;\n"
"    padding: 15px 25px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.1);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 0.2);\n"
"}\n"
"       ")
        self.navbar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.navbar.setObjectName("navbar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.navbar)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logoLabel = QtWidgets.QLabel(self.navbar)
        self.logoLabel.setMinimumSize(QtCore.QSize(250, 0))
        self.logoLabel.setStyleSheet("color: white; font-size: 18px; font-weight: bold; padding-left: 20px;")
        self.logoLabel.setObjectName("logoLabel")
        self.horizontalLayout.addWidget(self.logoLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnDashboard = QtWidgets.QPushButton(self.navbar)
        self.btnDashboard.setMinimumSize(QtCore.QSize(120, 0))
        self.btnDashboard.setObjectName("btnDashboard")
        self.horizontalLayout.addWidget(self.btnDashboard)
        self.btnStok = QtWidgets.QPushButton(self.navbar)
        self.btnStok.setMinimumSize(QtCore.QSize(120, 0))
        self.btnStok.setObjectName("btnStok")
        self.horizontalLayout.addWidget(self.btnStok)
        self.btnPermintaan = QtWidgets.QPushButton(self.navbar)
        self.btnPermintaan.setMinimumSize(QtCore.QSize(150, 0))
        self.btnPermintaan.setObjectName("btnPermintaan")
        self.horizontalLayout.addWidget(self.btnPermintaan)
        self.btnRiwayat = QtWidgets.QPushButton(self.navbar)
        self.btnRiwayat.setMinimumSize(QtCore.QSize(100, 0))
        self.btnRiwayat.setObjectName("btnRiwayat")
        self.horizontalLayout.addWidget(self.btnRiwayat)
        self.btnLaporan = QtWidgets.QPushButton(self.navbar)
        self.btnLaporan.setMinimumSize(QtCore.QSize(100, 0))
        self.btnLaporan.setObjectName("btnLaporan")
        self.horizontalLayout.addWidget(self.btnLaporan)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.navbar)
        self.contentWidget = QtWidgets.QWidget(self.centralwidget)
        self.contentWidget.setObjectName("contentWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.contentWidget)
        self.verticalLayout_2.setContentsMargins(30, 30, 30, 30)
        self.verticalLayout_2.setSpacing(20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.headerLayout = QtWidgets.QHBoxLayout()
        self.headerLayout.setObjectName("headerLayout")
        self.titleLabel = QtWidgets.QLabel(self.contentWidget)
        self.titleLabel.setStyleSheet("font-size: 24px; font-weight: bold; color: #750003;")
        self.titleLabel.setObjectName("titleLabel")
        self.headerLayout.addWidget(self.titleLabel)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.headerLayout.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.headerLayout)
        self.formFrame = QtWidgets.QFrame(self.contentWidget)
        self.formFrame.setStyleSheet("\n"
"QFrame#formFrame {\n"
"    background-color: white;\n"
"    border: 1px solid #ddd;\n"
"}\n"
"QLineEdit, QComboBox, QSpinBox, QTextEdit {\n"
"    padding: 8px;\n"
"    border: 1px solid #ddd;\n"
"    border-radius: 5px;\n"
"    background-color: white;\n"
"}\n"
"QLineEdit:focus, QComboBox:focus, QSpinBox:focus, QTextEdit:focus {\n"
"    border: 2px solid #750003;\n"
"}\n"
"          ")
        self.formFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.formFrame.setObjectName("formFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.formFrame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lblFormTitle = QtWidgets.QLabel(self.formFrame)
        self.lblFormTitle.setStyleSheet("font-size: 18px; font-weight: bold; color: #750003; margin-bottom: 10px;")
        self.lblFormTitle.setObjectName("lblFormTitle")
        self.verticalLayout_3.addWidget(self.lblFormTitle)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(20)
        self.gridLayout.setVerticalSpacing(15)
        self.gridLayout.setObjectName("gridLayout")
        self.lblNomorPermintaan = QtWidgets.QLabel(self.formFrame)
        self.lblNomorPermintaan.setObjectName("lblNomorPermintaan")
        self.gridLayout.addWidget(self.lblNomorPermintaan, 0, 0, 1, 1)
        self.txtNomorPermintaan = QtWidgets.QLineEdit(self.formFrame)
        self.txtNomorPermintaan.setObjectName("txtNomorPermintaan")
        self.gridLayout.addWidget(self.txtNomorPermintaan, 0, 1, 1, 1)
        self.lblGolonganDarah = QtWidgets.QLabel(self.formFrame)
        self.lblGolonganDarah.setObjectName("lblGolonganDarah")
        self.gridLayout.addWidget(self.lblGolonganDarah, 1, 0, 1, 1)
        self.cmbGolonganDarah = QtWidgets.QComboBox(self.formFrame)
        self.cmbGolonganDarah.setObjectName("cmbGolonganDarah")
        self.cmbGolonganDarah.addItem("")
        self.cmbGolonganDarah.addItem("")
        self.cmbGolonganDarah.addItem("")
        self.cmbGolonganDarah.addItem("")
        self.cmbGolonganDarah.addItem("")
        self.cmbGolonganDarah.addItem("")
        self.cmbGolonganDarah.addItem("")
        self.cmbGolonganDarah.addItem("")
        self.cmbGolonganDarah.addItem("")
        self.gridLayout.addWidget(self.cmbGolonganDarah, 1, 1, 1, 1)
        self.lblJumlah = QtWidgets.QLabel(self.formFrame)
        self.lblJumlah.setObjectName("lblJumlah")
        self.gridLayout.addWidget(self.lblJumlah, 2, 0, 1, 1)
        self.spinJumlah = QtWidgets.QSpinBox(self.formFrame)
        self.spinJumlah.setMinimum(1)
        self.spinJumlah.setMaximum(100)
        self.spinJumlah.setObjectName("spinJumlah")
        self.gridLayout.addWidget(self.spinJumlah, 2, 1, 1, 1)
        self.lblKeperluan = QtWidgets.QLabel(self.formFrame)
        self.lblKeperluan.setObjectName("lblKeperluan")
        self.gridLayout.addWidget(self.lblKeperluan, 3, 0, 1, 1)
        self.txtKeperluan = QtWidgets.QTextEdit(self.formFrame)
        self.txtKeperluan.setMaximumSize(QtCore.QSize(16777215, 80))
        self.txtKeperluan.setObjectName("txtKeperluan")
        self.gridLayout.addWidget(self.txtKeperluan, 3, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonLayout.addItem(spacerItem3)
        self.btnSimpan = QtWidgets.QPushButton(self.formFrame)
        self.btnSimpan.setMinimumSize(QtCore.QSize(120, 40))
        self.btnSimpan.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: #750003;\n"
"    color: white;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #a00004;\n"
"}\n"
"               ")
        self.btnSimpan.setObjectName("btnSimpan")
        self.buttonLayout.addWidget(self.btnSimpan)
        self.btnBatal = QtWidgets.QPushButton(self.formFrame)
        self.btnBatal.setMinimumSize(QtCore.QSize(120, 40))
        self.btnBatal.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: #6c757d;\n"
"    color: white;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5a6268;\n"
"}\n"
"               ")
        self.btnBatal.setObjectName("btnBatal")
        self.buttonLayout.addWidget(self.btnBatal)
        self.verticalLayout_3.addLayout(self.buttonLayout)
        self.verticalLayout_2.addWidget(self.formFrame)
        self.tableFrame = QtWidgets.QFrame(self.contentWidget)
        self.tableFrame.setStyleSheet("\n"
"QFrame#tableFrame {\n"
"    background-color: white;\n"
"    border: 1px solid #ddd;\n"
"}\n"
"          ")
        self.tableFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableFrame.setObjectName("tableFrame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tableFrame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tableHeaderLayout = QtWidgets.QHBoxLayout()
        self.tableHeaderLayout.setObjectName("tableHeaderLayout")
        self.lblTableTitle = QtWidgets.QLabel(self.tableFrame)
        self.lblTableTitle.setStyleSheet("font-size: 18px; font-weight: bold; color: #750003;")
        self.lblTableTitle.setObjectName("lblTableTitle")
        self.tableHeaderLayout.addWidget(self.lblTableTitle)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.tableHeaderLayout.addItem(spacerItem4)
        self.txtCari = QtWidgets.QLineEdit(self.tableFrame)
        self.txtCari.setMinimumSize(QtCore.QSize(250, 35))
        self.txtCari.setObjectName("txtCari")
        self.tableHeaderLayout.addWidget(self.txtCari)
        self.verticalLayout_4.addLayout(self.tableHeaderLayout)
        self.tablePermintaan = QtWidgets.QTableWidget(self.tableFrame)
        self.tablePermintaan.setStyleSheet("\n"
"QTableWidget {\n"
"    border: none;\n"
"    background-color: white;\n"
"    gridline-color: #f0f0f0;\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #750003;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    border: none;\n"
"    font-weight: bold;\n"
"}\n"
"QTableWidget::item {\n"
"    padding: 10px;\n"
"}\n"
"QTableWidget::item:selected {\n"
"    background-color: #fff5f5;\n"
"    color: #750003;\n"
"}\n"
"             ")
        self.tablePermintaan.setObjectName("tablePermintaan")
        self.tablePermintaan.setColumnCount(6)
        self.tablePermintaan.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablePermintaan.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePermintaan.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePermintaan.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePermintaan.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePermintaan.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePermintaan.setHorizontalHeaderItem(5, item)
        self.verticalLayout_4.addWidget(self.tablePermintaan)
        self.verticalLayout_2.addWidget(self.tableFrame)
        self.verticalLayout.addWidget(self.contentWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Permintaan Stok Darah - PMI"))
        self.logoLabel.setText(_translate("MainWindow", "🏥 RUMAH SAKIT - PMI"))
        self.btnDashboard.setText(_translate("MainWindow", "Dashboard"))
        self.btnStok.setText(_translate("MainWindow", "Stok Darah"))
        self.btnPermintaan.setText(_translate("MainWindow", "Permintaan Darah"))
        self.btnRiwayat.setText(_translate("MainWindow", "Riwayat"))
        self.btnLaporan.setText(_translate("MainWindow", "Laporan"))
        self.titleLabel.setText(_translate("MainWindow", "Kelola Permintaan Stok Darah"))
        self.lblFormTitle.setText(_translate("MainWindow", "Form Permintaan Darah"))
        self.lblNomorPermintaan.setText(_translate("MainWindow", "No. Permintaan:"))
        self.txtNomorPermintaan.setPlaceholderText(_translate("MainWindow", "Contoh: REQ-2024-001"))
        self.lblGolonganDarah.setText(_translate("MainWindow", "Golongan Darah:"))
        self.cmbGolonganDarah.setItemText(0, _translate("MainWindow", "-- Pilih Golongan Darah --"))
        self.cmbGolonganDarah.setItemText(1, _translate("MainWindow", "A+"))
        self.cmbGolonganDarah.setItemText(2, _translate("MainWindow", "A-"))
        self.cmbGolonganDarah.setItemText(3, _translate("MainWindow", "B+"))
        self.cmbGolonganDarah.setItemText(4, _translate("MainWindow", "B-"))
        self.cmbGolonganDarah.setItemText(5, _translate("MainWindow", "AB+"))
        self.cmbGolonganDarah.setItemText(6, _translate("MainWindow", "AB-"))
        self.cmbGolonganDarah.setItemText(7, _translate("MainWindow", "O+"))
        self.cmbGolonganDarah.setItemText(8, _translate("MainWindow", "O-"))
        self.lblJumlah.setText(_translate("MainWindow", "Jumlah (kantong):"))
        self.lblKeperluan.setText(_translate("MainWindow", "Keperluan:"))
        self.txtKeperluan.setPlaceholderText(_translate("MainWindow", "Jelaskan keperluan permintaan darah..."))
        self.btnSimpan.setText(_translate("MainWindow", "💾 Simpan"))
        self.btnBatal.setText(_translate("MainWindow", "✖ Batal"))
        self.lblTableTitle.setText(_translate("MainWindow", "Daftar Permintaan"))
        self.txtCari.setPlaceholderText(_translate("MainWindow", "🔍 Cari permintaan..."))
        item = self.tablePermintaan.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "No. Permintaan"))
        item = self.tablePermintaan.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Golongan Darah"))
        item = self.tablePermintaan.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Jumlah"))
        item = self.tablePermintaan.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Keperluan"))
        item = self.tablePermintaan.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Status"))
        item = self.tablePermintaan.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Aksi"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
