# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'riwayatpermintaan.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        MainWindow.setStyleSheet("\n"
"QMainWindow {\n"
"    background-color: #f5f5f5;\n"
"}\n"
"QPushButton {\n"
"    border: none;\n"
"    padding: 10px 20px;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    opacity: 0.8;\n"
"}\n"
"QFrame {\n"
"    border-radius: 10px;\n"
"}\n"
"QLabel {\n"
"    color: #333333;\n"
"}\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.navbar = QtWidgets.QFrame(self.centralwidget)
        self.navbar.setMinimumSize(QtCore.QSize(0, 70))
        self.navbar.setMaximumSize(QtCore.QSize(16777215, 70))
        self.navbar.setStyleSheet("\n"
"QFrame#navbar {\n"
"    background-color: #750003;\n"
"}\n"
"QPushButton {\n"
"    color: white;\n"
"    background-color: transparent;\n"
"    text-align: left;\n"
"    padding: 15px 25px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.1);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 0.2);\n"
"}\n"
"       ")
        self.navbar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.navbar.setObjectName("navbar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.navbar)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logoLabel = QtWidgets.QLabel(self.navbar)
        self.logoLabel.setMinimumSize(QtCore.QSize(250, 0))
        self.logoLabel.setStyleSheet("color: white; font-size: 18px; font-weight: bold; padding-left: 20px;")
        self.logoLabel.setObjectName("logoLabel")
        self.horizontalLayout.addWidget(self.logoLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnDashboard = QtWidgets.QPushButton(self.navbar)
        self.btnDashboard.setMinimumSize(QtCore.QSize(120, 0))
        self.btnDashboard.setObjectName("btnDashboard")
        self.horizontalLayout.addWidget(self.btnDashboard)
        self.btnStok = QtWidgets.QPushButton(self.navbar)
        self.btnStok.setMinimumSize(QtCore.QSize(120, 0))
        self.btnStok.setObjectName("btnStok")
        self.horizontalLayout.addWidget(self.btnStok)
        self.btnPermintaan = QtWidgets.QPushButton(self.navbar)
        self.btnPermintaan.setMinimumSize(QtCore.QSize(150, 0))
        self.btnPermintaan.setObjectName("btnPermintaan")
        self.horizontalLayout.addWidget(self.btnPermintaan)
        self.btnRiwayat = QtWidgets.QPushButton(self.navbar)
        self.btnRiwayat.setMinimumSize(QtCore.QSize(100, 0))
        self.btnRiwayat.setObjectName("btnRiwayat")
        self.horizontalLayout.addWidget(self.btnRiwayat)
        self.btnLaporan = QtWidgets.QPushButton(self.navbar)
        self.btnLaporan.setMinimumSize(QtCore.QSize(100, 0))
        self.btnLaporan.setObjectName("btnLaporan")
        self.horizontalLayout.addWidget(self.btnLaporan)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.navbar)
        self.contentWidget = QtWidgets.QWidget(self.centralwidget)
        self.contentWidget.setObjectName("contentWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.contentWidget)
        self.verticalLayout_2.setContentsMargins(30, 30, 30, 30)
        self.verticalLayout_2.setSpacing(20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.headerLayout = QtWidgets.QHBoxLayout()
        self.headerLayout.setObjectName("headerLayout")
        self.titleLabel = QtWidgets.QLabel(self.contentWidget)
        self.titleLabel.setStyleSheet("font-size: 24px; font-weight: bold; color: #750003;")
        self.titleLabel.setObjectName("titleLabel")
        self.headerLayout.addWidget(self.titleLabel)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.headerLayout.addItem(spacerItem2)
        self.btnExport = QtWidgets.QPushButton(self.contentWidget)
        self.btnExport.setMinimumSize(QtCore.QSize(150, 40))
        self.btnExport.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: #750003;\n"
"    color: white;\n"
"    font-size: 14px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #a00004;\n"
"}\n"
"            ")
        self.btnExport.setObjectName("btnExport")
        self.headerLayout.addWidget(self.btnExport)
        self.verticalLayout_2.addLayout(self.headerLayout)
        self.filterFrame = QtWidgets.QFrame(self.contentWidget)
        self.filterFrame.setStyleSheet("\n"
"QFrame#filterFrame {\n"
"    background-color: white;\n"
"    border: 1px solid #ddd;\n"
"}\n"
"QLineEdit, QComboBox, QDateEdit {\n"
"    padding: 8px;\n"
"    border: 1px solid #ddd;\n"
"    border-radius: 5px;\n"
"    background-color: white;\n"
"}\n"
"QLineEdit:focus, QComboBox:focus, QDateEdit:focus {\n"
"    border: 2px solid #750003;\n"
"}\n"
"          ")
        self.filterFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.filterFrame.setObjectName("filterFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.filterFrame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lblFilter = QtWidgets.QLabel(self.filterFrame)
        self.lblFilter.setStyleSheet("font-size: 16px; font-weight: bold; color: #750003;")
        self.lblFilter.setObjectName("lblFilter")
        self.verticalLayout_3.addWidget(self.lblFilter)
        self.filterLayout = QtWidgets.QHBoxLayout()
        self.filterLayout.setSpacing(15)
        self.filterLayout.setObjectName("filterLayout")
        self.txtCari = QtWidgets.QLineEdit(self.filterFrame)
        self.txtCari.setMinimumSize(QtCore.QSize(250, 35))
        self.txtCari.setObjectName("txtCari")
        self.filterLayout.addWidget(self.txtCari)
        self.cmbStatus = QtWidgets.QComboBox(self.filterFrame)
        self.cmbStatus.setMinimumSize(QtCore.QSize(150, 35))
        self.cmbStatus.setObjectName("cmbStatus")
        self.cmbStatus.addItem("")
        self.cmbStatus.addItem("")
        self.cmbStatus.addItem("")
        self.cmbStatus.addItem("")
        self.filterLayout.addWidget(self.cmbStatus)
        self.cmbGolongan = QtWidgets.QComboBox(self.filterFrame)
        self.cmbGolongan.setMinimumSize(QtCore.QSize(120, 35))
        self.cmbGolongan.setObjectName("cmbGolongan")
        self.cmbGolongan.addItem("")
        self.cmbGolongan.addItem("")
        self.cmbGolongan.addItem("")
        self.cmbGolongan.addItem("")
        self.cmbGolongan.addItem("")
        self.cmbGolongan.addItem("")
        self.cmbGolongan.addItem("")
        self.cmbGolongan.addItem("")
        self.cmbGolongan.addItem("")
        self.filterLayout.addWidget(self.cmbGolongan)
        self.dateFrom = QtWidgets.QDateEdit(self.filterFrame)
        self.dateFrom.setMinimumSize(QtCore.QSize(130, 35))
        self.dateFrom.setCalendarPopup(True)
        self.dateFrom.setObjectName("dateFrom")
        self.filterLayout.addWidget(self.dateFrom)
        self.lblSampai = QtWidgets.QLabel(self.filterFrame)
        self.lblSampai.setObjectName("lblSampai")
        self.filterLayout.addWidget(self.lblSampai)
        self.dateTo = QtWidgets.QDateEdit(self.filterFrame)
        self.dateTo.setMinimumSize(QtCore.QSize(130, 35))
        self.dateTo.setCalendarPopup(True)
        self.dateTo.setObjectName("dateTo")
        self.filterLayout.addWidget(self.dateTo)
        self.btnFilter = QtWidgets.QPushButton(self.filterFrame)
        self.btnFilter.setMinimumSize(QtCore.QSize(100, 35))
        self.btnFilter.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: #750003;\n"
"    color: white;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #a00004;\n"
"}\n"
"               ")
        self.btnFilter.setObjectName("btnFilter")
        self.filterLayout.addWidget(self.btnFilter)
        self.btnReset = QtWidgets.QPushButton(self.filterFrame)
        self.btnReset.setMinimumSize(QtCore.QSize(80, 35))
        self.btnReset.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: #6c757d;\n"
"    color: white;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5a6268;\n"
"}\n"
"               ")
        self.btnReset.setObjectName("btnReset")
        self.filterLayout.addWidget(self.btnReset)
        self.verticalLayout_3.addLayout(self.filterLayout)
        self.verticalLayout_2.addWidget(self.filterFrame)
        self.statsFrame = QtWidgets.QFrame(self.contentWidget)
        self.statsFrame.setMinimumSize(QtCore.QSize(0, 100))
        self.statsFrame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.statsFrame.setStyleSheet("\n"
"QFrame#statsFrame {\n"
"    background-color: white;\n"
"    border: 1px solid #ddd;\n"
"}\n"
"          ")
        self.statsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.statsFrame.setObjectName("statsFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.statsFrame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lblTotalPermintaan = QtWidgets.QLabel(self.statsFrame)
        self.lblTotalPermintaan.setStyleSheet("font-size: 14px; color: #666;")
        self.lblTotalPermintaan.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTotalPermintaan.setObjectName("lblTotalPermintaan")
        self.verticalLayout_4.addWidget(self.lblTotalPermintaan)
        self.valueTotalPermintaan = QtWidgets.QLabel(self.statsFrame)
        self.valueTotalPermintaan.setStyleSheet("font-size: 28px; font-weight: bold; color: #750003;")
        self.valueTotalPermintaan.setAlignment(QtCore.Qt.AlignCenter)
        self.valueTotalPermintaan.setObjectName("valueTotalPermintaan")
        self.verticalLayout_4.addWidget(self.valueTotalPermintaan)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.line = QtWidgets.QFrame(self.statsFrame)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lblDisetujui = QtWidgets.QLabel(self.statsFrame)
        self.lblDisetujui.setStyleSheet("font-size: 14px; color: #666;")
        self.lblDisetujui.setAlignment(QtCore.Qt.AlignCenter)
        self.lblDisetujui.setObjectName("lblDisetujui")
        self.verticalLayout_5.addWidget(self.lblDisetujui)
        self.valueDisetujui = QtWidgets.QLabel(self.statsFrame)
        self.valueDisetujui.setStyleSheet("font-size: 28px; font-weight: bold; color: #28a745;")
        self.valueDisetujui.setAlignment(QtCore.Qt.AlignCenter)
        self.valueDisetujui.setObjectName("valueDisetujui")
        self.verticalLayout_5.addWidget(self.valueDisetujui)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.line_2 = QtWidgets.QFrame(self.statsFrame)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_2.addWidget(self.line_2)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lblDitolak = QtWidgets.QLabel(self.statsFrame)
        self.lblDitolak.setStyleSheet("font-size: 14px; color: #666;")
        self.lblDitolak.setAlignment(QtCore.Qt.AlignCenter)
        self.lblDitolak.setObjectName("lblDitolak")
        self.verticalLayout_6.addWidget(self.lblDitolak)
        self.valueDitolak = QtWidgets.QLabel(self.statsFrame)
        self.valueDitolak.setStyleSheet("font-size: 28px; font-weight: bold; color: #dc3545;")
        self.valueDitolak.setAlignment(QtCore.Qt.AlignCenter)
        self.valueDitolak.setObjectName("valueDitolak")
        self.verticalLayout_6.addWidget(self.valueDitolak)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.line_3 = QtWidgets.QFrame(self.statsFrame)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_2.addWidget(self.line_3)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.lblTotalKantong = QtWidgets.QLabel(self.statsFrame)
        self.lblTotalKantong.setStyleSheet("font-size: 14px; color: #666;")
        self.lblTotalKantong.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTotalKantong.setObjectName("lblTotalKantong")
        self.verticalLayout_7.addWidget(self.lblTotalKantong)
        self.valueTotalKantong = QtWidgets.QLabel(self.statsFrame)
        self.valueTotalKantong.setStyleSheet("font-size: 28px; font-weight: bold; color: #750003;")
        self.valueTotalKantong.setAlignment(QtCore.Qt.AlignCenter)
        self.valueTotalKantong.setObjectName("valueTotalKantong")
        self.verticalLayout_7.addWidget(self.valueTotalKantong)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.verticalLayout_2.addWidget(self.statsFrame)
        self.tableFrame = QtWidgets.QFrame(self.contentWidget)
        self.tableFrame.setStyleSheet("\n"
"QFrame#tableFrame {\n"
"    background-color: white;\n"
"    border: 1px solid #ddd;\n"
"}\n"
"          ")
        self.tableFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableFrame.setObjectName("tableFrame")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tableFrame)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.tableRiwayat = QtWidgets.QTableWidget(self.tableFrame)
        self.tableRiwayat.setStyleSheet("\n"
"QTableWidget {\n"
"    border: none;\n"
"    background-color: white;\n"
"    gridline-color: #f0f0f0;\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #750003;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    border: none;\n"
"    font-weight: bold;\n"
"}\n"
"QTableWidget::item {\n"
"    padding: 10px;\n"
"}\n"
"QTableWidget::item:selected {\n"
"    background-color: #fff5f5;\n"
"    color: #750003;\n"
"}\n"
"             ")
        self.tableRiwayat.setObjectName("tableRiwayat")
        self.tableRiwayat.setColumnCount(7)
        self.tableRiwayat.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableRiwayat.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableRiwayat.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableRiwayat.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableRiwayat.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableRiwayat.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableRiwayat.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableRiwayat.setHorizontalHeaderItem(6, item)
        self.verticalLayout_8.addWidget(self.tableRiwayat)
        self.verticalLayout_2.addWidget(self.tableFrame)
        self.verticalLayout.addWidget(self.contentWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Riwayat Permintaan - PMI"))
        self.logoLabel.setText(_translate("MainWindow", "🏥 RUMAH SAKIT - PMI"))
        self.btnDashboard.setText(_translate("MainWindow", "Dashboard"))
        self.btnStok.setText(_translate("MainWindow", "Stok Darah"))
        self.btnPermintaan.setText(_translate("MainWindow", "Permintaan Darah"))
        self.btnRiwayat.setText(_translate("MainWindow", "Riwayat"))
        self.btnLaporan.setText(_translate("MainWindow", "Laporan"))
        self.titleLabel.setText(_translate("MainWindow", "Riwayat Permintaan Darah"))
        self.btnExport.setText(_translate("MainWindow", "📊 Export Data"))
        self.lblFilter.setText(_translate("MainWindow", "Filter Riwayat"))
        self.txtCari.setPlaceholderText(_translate("MainWindow", "🔍 Cari nomor permintaan..."))
        self.cmbStatus.setItemText(0, _translate("MainWindow", "Semua Status"))
        self.cmbStatus.setItemText(1, _translate("MainWindow", "Disetujui"))
        self.cmbStatus.setItemText(2, _translate("MainWindow", "Ditolak"))
        self.cmbStatus.setItemText(3, _translate("MainWindow", "Selesai"))
        self.cmbGolongan.setItemText(0, _translate("MainWindow", "Semua Golongan"))
        self.cmbGolongan.setItemText(1, _translate("MainWindow", "A+"))
        self.cmbGolongan.setItemText(2, _translate("MainWindow", "A-"))
        self.cmbGolongan.setItemText(3, _translate("MainWindow", "B+"))
        self.cmbGolongan.setItemText(4, _translate("MainWindow", "B-"))
        self.cmbGolongan.setItemText(5, _translate("MainWindow", "AB+"))
        self.cmbGolongan.setItemText(6, _translate("MainWindow", "AB-"))
        self.cmbGolongan.setItemText(7, _translate("MainWindow", "O+"))
        self.cmbGolongan.setItemText(8, _translate("MainWindow", "O-"))
        self.lblSampai.setText(_translate("MainWindow", "s/d"))
        self.btnFilter.setText(_translate("MainWindow", "Terapkan"))
        self.btnReset.setText(_translate("MainWindow", "Reset"))
        self.lblTotalPermintaan.setText(_translate("MainWindow", "Total Permintaan"))
        self.valueTotalPermintaan.setText(_translate("MainWindow", "256"))
        self.lblDisetujui.setText(_translate("MainWindow", "Disetujui"))
        self.valueDisetujui.setText(_translate("MainWindow", "234"))
        self.lblDitolak.setText(_translate("MainWindow", "Ditolak"))
        self.valueDitolak.setText(_translate("MainWindow", "22"))
        self.lblTotalKantong.setText(_translate("MainWindow", "Total Kantong Diterima"))
        self.valueTotalKantong.setText(_translate("MainWindow", "1,847"))
        item = self.tableRiwayat.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "No. Permintaan"))
        item = self.tableRiwayat.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Tanggal"))
        item = self.tableRiwayat.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Golongan"))
        item = self.tableRiwayat.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Jumlah"))
        item = self.tableRiwayat.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Status"))
        item = self.tableRiwayat.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Keterangan"))
        item = self.tableRiwayat.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Aksi"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
