# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stokdarahrs.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        MainWindow.setStyleSheet("\n"
"QMainWindow {\n"
"    background-color: #f5f5f5;\n"
"}\n"
"QPushButton {\n"
"    border: none;\n"
"    padding: 10px 20px;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    opacity: 0.8;\n"
"}\n"
"QFrame {\n"
"    border-radius: 10px;\n"
"}\n"
"QLabel {\n"
"    color: #333333;\n"
"}\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.navbar = QtWidgets.QFrame(self.centralwidget)
        self.navbar.setMinimumSize(QtCore.QSize(0, 70))
        self.navbar.setMaximumSize(QtCore.QSize(16777215, 70))
        self.navbar.setStyleSheet("\n"
"QFrame#navbar {\n"
"    background-color: #750003;\n"
"}\n"
"QPushButton {\n"
"    color: white;\n"
"    background-color: transparent;\n"
"    text-align: left;\n"
"    padding: 15px 25px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.1);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 0.2);\n"
"}\n"
"       ")
        self.navbar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.navbar.setObjectName("navbar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.navbar)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logoLabel = QtWidgets.QLabel(self.navbar)
        self.logoLabel.setMinimumSize(QtCore.QSize(250, 0))
        self.logoLabel.setStyleSheet("color: white; font-size: 18px; font-weight: bold; padding-left: 20px;")
        self.logoLabel.setObjectName("logoLabel")
        self.horizontalLayout.addWidget(self.logoLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnDashboard = QtWidgets.QPushButton(self.navbar)
        self.btnDashboard.setMinimumSize(QtCore.QSize(120, 0))
        self.btnDashboard.setObjectName("btnDashboard")
        self.horizontalLayout.addWidget(self.btnDashboard)
        self.btnStok = QtWidgets.QPushButton(self.navbar)
        self.btnStok.setMinimumSize(QtCore.QSize(120, 0))
        self.btnStok.setObjectName("btnStok")
        self.horizontalLayout.addWidget(self.btnStok)
        self.btnPermintaan = QtWidgets.QPushButton(self.navbar)
        self.btnPermintaan.setMinimumSize(QtCore.QSize(150, 0))
        self.btnPermintaan.setObjectName("btnPermintaan")
        self.horizontalLayout.addWidget(self.btnPermintaan)
        self.btnRiwayat = QtWidgets.QPushButton(self.navbar)
        self.btnRiwayat.setMinimumSize(QtCore.QSize(100, 0))
        self.btnRiwayat.setObjectName("btnRiwayat")
        self.horizontalLayout.addWidget(self.btnRiwayat)
        self.btnLaporan = QtWidgets.QPushButton(self.navbar)
        self.btnLaporan.setMinimumSize(QtCore.QSize(100, 0))
        self.btnLaporan.setObjectName("btnLaporan")
        self.horizontalLayout.addWidget(self.btnLaporan)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.navbar)
        self.stokDarahPage = QtWidgets.QWidget(self.centralwidget)
        self.stokDarahPage.setObjectName("stokDarahPage")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.stokDarahPage)
        self.verticalLayout_2.setContentsMargins(30, 30, 30, 30)
        self.verticalLayout_2.setSpacing(20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.titleLabel = QtWidgets.QLabel(self.stokDarahPage)
        self.titleLabel.setStyleSheet("font-size: 24px; font-weight: bold; color: #750003;")
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout_2.addWidget(self.titleLabel)
        self.gridStokCards = QtWidgets.QGridLayout()
        self.gridStokCards.setSpacing(20)
        self.gridStokCards.setObjectName("gridStokCards")
        self.cardA = QtWidgets.QFrame(self.stokDarahPage)
        self.cardA.setStyleSheet("\n"
"QFrame#cardA {\n"
"    background-color: white;\n"
"    border: 2px solid #750003;\n"
"}\n"
"            ")
        self.cardA.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cardA.setObjectName("cardA")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.cardA)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lblGolA = QtWidgets.QLabel(self.cardA)
        self.lblGolA.setStyleSheet("font-size: 48px; font-weight: bold; color: #750003;")
        self.lblGolA.setAlignment(QtCore.Qt.AlignCenter)
        self.lblGolA.setObjectName("lblGolA")
        self.verticalLayout_3.addWidget(self.lblGolA)
        self.valueA = QtWidgets.QLabel(self.cardA)
        self.valueA.setStyleSheet("font-size: 36px; font-weight: bold; color: #750003;")
        self.valueA.setAlignment(QtCore.Qt.AlignCenter)
        self.valueA.setObjectName("valueA")
        self.verticalLayout_3.addWidget(self.valueA)
        self.lblUnitA = QtWidgets.QLabel(self.cardA)
        self.lblUnitA.setStyleSheet("font-size: 14px; color: #666;")
        self.lblUnitA.setAlignment(QtCore.Qt.AlignCenter)
        self.lblUnitA.setObjectName("lblUnitA")
        self.verticalLayout_3.addWidget(self.lblUnitA)
        self.gridStokCards.addWidget(self.cardA, 0, 0, 1, 1)
        self.cardB = QtWidgets.QFrame(self.stokDarahPage)
        self.cardB.setStyleSheet("\n"
"QFrame#cardB {\n"
"    background-color: white;\n"
"    border: 2px solid #750003;\n"
"}\n"
"            ")
        self.cardB.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cardB.setObjectName("cardB")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.cardB)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lblGolB = QtWidgets.QLabel(self.cardB)
        self.lblGolB.setStyleSheet("font-size: 48px; font-weight: bold; color: #750003;")
        self.lblGolB.setAlignment(QtCore.Qt.AlignCenter)
        self.lblGolB.setObjectName("lblGolB")
        self.verticalLayout_4.addWidget(self.lblGolB)
        self.valueB = QtWidgets.QLabel(self.cardB)
        self.valueB.setStyleSheet("font-size: 36px; font-weight: bold; color: #750003;")
        self.valueB.setAlignment(QtCore.Qt.AlignCenter)
        self.valueB.setObjectName("valueB")
        self.verticalLayout_4.addWidget(self.valueB)
        self.lblUnitB = QtWidgets.QLabel(self.cardB)
        self.lblUnitB.setStyleSheet("font-size: 14px; color: #666;")
        self.lblUnitB.setAlignment(QtCore.Qt.AlignCenter)
        self.lblUnitB.setObjectName("lblUnitB")
        self.verticalLayout_4.addWidget(self.lblUnitB)
        self.gridStokCards.addWidget(self.cardB, 0, 1, 1, 1)
        self.cardO = QtWidgets.QFrame(self.stokDarahPage)
        self.cardO.setStyleSheet("\n"
"QFrame#cardO {\n"
"    background-color: white;\n"
"    border: 2px solid #750003;\n"
"}\n"
"            ")
        self.cardO.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cardO.setObjectName("cardO")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.cardO)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lblGolO = QtWidgets.QLabel(self.cardO)
        self.lblGolO.setStyleSheet("font-size: 48px; font-weight: bold; color: #750003;")
        self.lblGolO.setAlignment(QtCore.Qt.AlignCenter)
        self.lblGolO.setObjectName("lblGolO")
        self.verticalLayout_5.addWidget(self.lblGolO)
        self.valueO = QtWidgets.QLabel(self.cardO)
        self.valueO.setStyleSheet("font-size: 36px; font-weight: bold; color: #750003;")
        self.valueO.setAlignment(QtCore.Qt.AlignCenter)
        self.valueO.setObjectName("valueO")
        self.verticalLayout_5.addWidget(self.valueO)
        self.lblUnitO = QtWidgets.QLabel(self.cardO)
        self.lblUnitO.setStyleSheet("font-size: 14px; color: #666;")
        self.lblUnitO.setAlignment(QtCore.Qt.AlignCenter)
        self.lblUnitO.setObjectName("lblUnitO")
        self.verticalLayout_5.addWidget(self.lblUnitO)
        self.gridStokCards.addWidget(self.cardO, 0, 2, 1, 1)
        self.cardAB = QtWidgets.QFrame(self.stokDarahPage)
        self.cardAB.setStyleSheet("\n"
"QFrame#cardAB {\n"
"    background-color: white;\n"
"    border: 2px solid #750003;\n"
"}\n"
"            ")
        self.cardAB.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cardAB.setObjectName("cardAB")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.cardAB)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lblGolAB = QtWidgets.QLabel(self.cardAB)
        self.lblGolAB.setStyleSheet("font-size: 48px; font-weight: bold; color: #750003;")
        self.lblGolAB.setAlignment(QtCore.Qt.AlignCenter)
        self.lblGolAB.setObjectName("lblGolAB")
        self.verticalLayout_6.addWidget(self.lblGolAB)
        self.valueAB = QtWidgets.QLabel(self.cardAB)
        self.valueAB.setStyleSheet("font-size: 36px; font-weight: bold; color: #750003;")
        self.valueAB.setAlignment(QtCore.Qt.AlignCenter)
        self.valueAB.setObjectName("valueAB")
        self.verticalLayout_6.addWidget(self.valueAB)
        self.lblUnitAB = QtWidgets.QLabel(self.cardAB)
        self.lblUnitAB.setStyleSheet("font-size: 14px; color: #666;")
        self.lblUnitAB.setAlignment(QtCore.Qt.AlignCenter)
        self.lblUnitAB.setObjectName("lblUnitAB")
        self.verticalLayout_6.addWidget(self.lblUnitAB)
        self.gridStokCards.addWidget(self.cardAB, 0, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridStokCards)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(20)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frameRiwayatStok = QtWidgets.QFrame(self.stokDarahPage)
        self.frameRiwayatStok.setStyleSheet("\n"
"QFrame#frameRiwayatStok {\n"
"    background-color: white;\n"
"    border: 1px solid #ddd;\n"
"}\n"
"            ")
        self.frameRiwayatStok.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameRiwayatStok.setObjectName("frameRiwayatStok")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frameRiwayatStok)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.lblRiwayatStok = QtWidgets.QLabel(self.frameRiwayatStok)
        self.lblRiwayatStok.setStyleSheet("font-size: 16px; font-weight: bold; color: #750003;")
        self.lblRiwayatStok.setObjectName("lblRiwayatStok")
        self.verticalLayout_7.addWidget(self.lblRiwayatStok)
        self.tableRiwayatStok = QtWidgets.QTableWidget(self.frameRiwayatStok)
        self.tableRiwayatStok.setStyleSheet("\n"
"QTableWidget {\n"
"    border: none;\n"
"    background-color: white;\n"
"    gridline-color: #f0f0f0;\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #750003;\n"
"    color: white;\n"
"    padding: 8px;\n"
"    border: none;\n"
"    font-weight: bold;\n"
"}\n"
"QTableWidget::item {\n"
"    padding: 8px;\n"
"}\n"
"               ")
        self.tableRiwayatStok.setObjectName("tableRiwayatStok")
        self.tableRiwayatStok.setColumnCount(5)
        self.tableRiwayatStok.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableRiwayatStok.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableRiwayatStok.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableRiwayatStok.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableRiwayatStok.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableRiwayatStok.setHorizontalHeaderItem(4, item)
        self.verticalLayout_7.addWidget(self.tableRiwayatStok)
        self.horizontalLayout_2.addWidget(self.frameRiwayatStok)
        self.frameInfo = QtWidgets.QFrame(self.stokDarahPage)
        self.frameInfo.setMinimumSize(QtCore.QSize(300, 0))
        self.frameInfo.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frameInfo.setStyleSheet("\n"
"QFrame#frameInfo {\n"
"    background-color: white;\n"
"    border: 1px solid #ddd;\n"
"}\n"
"            ")
        self.frameInfo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameInfo.setObjectName("frameInfo")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frameInfo)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.lblInfoStok = QtWidgets.QLabel(self.frameInfo)
        self.lblInfoStok.setStyleSheet("font-size: 16px; font-weight: bold; color: #750003;")
        self.lblInfoStok.setObjectName("lblInfoStok")
        self.verticalLayout_8.addWidget(self.lblInfoStok)
        self.frameAlert = QtWidgets.QFrame(self.frameInfo)
        self.frameAlert.setStyleSheet("\n"
"QFrame#frameAlert {\n"
"    background-color: #fff5f5;\n"
"    border: 1px solid #750003;\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"}\n"
"               ")
        self.frameAlert.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameAlert.setObjectName("frameAlert")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frameAlert)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.lblAlert = QtWidgets.QLabel(self.frameAlert)
        self.lblAlert.setStyleSheet("font-size: 14px; font-weight: bold; color: #750003;")
        self.lblAlert.setObjectName("lblAlert")
        self.verticalLayout_9.addWidget(self.lblAlert)
        self.valueAlert = QtWidgets.QLabel(self.frameAlert)
        self.valueAlert.setStyleSheet("font-size: 12px; color: #666;")
        self.valueAlert.setWordWrap(True)
        self.valueAlert.setObjectName("valueAlert")
        self.verticalLayout_9.addWidget(self.valueAlert)
        self.verticalLayout_8.addWidget(self.frameAlert)
        self.lblTotalStok = QtWidgets.QLabel(self.frameInfo)
        self.lblTotalStok.setStyleSheet("font-size: 14px; font-weight: bold; color: #750003; margin-top: 15px;")
        self.lblTotalStok.setObjectName("lblTotalStok")
        self.verticalLayout_8.addWidget(self.lblTotalStok)
        self.valueTotalStok = QtWidgets.QLabel(self.frameInfo)
        self.valueTotalStok.setStyleSheet("font-size: 32px; font-weight: bold; color: #750003;")
        self.valueTotalStok.setAlignment(QtCore.Qt.AlignCenter)
        self.valueTotalStok.setObjectName("valueTotalStok")
        self.verticalLayout_8.addWidget(self.valueTotalStok)
        self.line = QtWidgets.QFrame(self.frameInfo)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_8.addWidget(self.line)
        self.lblUpdateTerakhir = QtWidgets.QLabel(self.frameInfo)
        self.lblUpdateTerakhir.setStyleSheet("font-size: 12px; color: #999;")
        self.lblUpdateTerakhir.setAlignment(QtCore.Qt.AlignCenter)
        self.lblUpdateTerakhir.setObjectName("lblUpdateTerakhir")
        self.verticalLayout_8.addWidget(self.lblUpdateTerakhir)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem2)
        self.horizontalLayout_2.addWidget(self.frameInfo)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.stokDarahPage)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Stok Darah - PMI Donor Darah"))
        self.logoLabel.setText(_translate("MainWindow", "🏥 RUMAH SAKIT - PMI"))
        self.btnDashboard.setText(_translate("MainWindow", "Dashboard"))
        self.btnStok.setText(_translate("MainWindow", "Stok Darah"))
        self.btnPermintaan.setText(_translate("MainWindow", "Permintaan Darah"))
        self.btnRiwayat.setText(_translate("MainWindow", "Riwayat"))
        self.btnLaporan.setText(_translate("MainWindow", "Laporan"))
        self.titleLabel.setText(_translate("MainWindow", "Stok Darah PMI"))
        self.lblGolA.setText(_translate("MainWindow", "A+"))
        self.valueA.setText(_translate("MainWindow", "42"))
        self.lblUnitA.setText(_translate("MainWindow", "kantong tersedia"))
        self.lblGolB.setText(_translate("MainWindow", "B+"))
        self.valueB.setText(_translate("MainWindow", "38"))
        self.lblUnitB.setText(_translate("MainWindow", "kantong tersedia"))
        self.lblGolO.setText(_translate("MainWindow", "O+"))
        self.valueO.setText(_translate("MainWindow", "56"))
        self.lblUnitO.setText(_translate("MainWindow", "kantong tersedia"))
        self.lblGolAB.setText(_translate("MainWindow", "AB+"))
        self.valueAB.setText(_translate("MainWindow", "29"))
        self.lblUnitAB.setText(_translate("MainWindow", "kantong tersedia"))
        self.lblRiwayatStok.setText(_translate("MainWindow", "Riwayat Perubahan Stok"))
        item = self.tableRiwayatStok.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Tanggal"))
        item = self.tableRiwayatStok.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Golongan"))
        item = self.tableRiwayatStok.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Jenis"))
        item = self.tableRiwayatStok.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Jumlah"))
        item = self.tableRiwayatStok.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Keterangan"))
        self.lblInfoStok.setText(_translate("MainWindow", "Informasi Stok"))
        self.lblAlert.setText(_translate("MainWindow", "⚠️ Peringatan Stok"))
        self.valueAlert.setText(_translate("MainWindow", "Golongan AB+ menipis!\n"
"Stok tersisa 29 kantong."))
        self.lblTotalStok.setText(_translate("MainWindow", "Total Stok Keseluruhan"))
        self.valueTotalStok.setText(_translate("MainWindow", "165 kantong"))
        self.lblUpdateTerakhir.setText(_translate("MainWindow", "Update terakhir:\n"
"28 Nov 2025, 14:30 WIB"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
