# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stokdarah.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from DARAH import *
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.id_darah = None
        self.window = MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        MainWindow.setStyleSheet("\n"
"QMainWindow {\n"
"    background-color: #f5f5f5;\n"
"}\n"
"QPushButton {\n"
"    border: none;\n"
"    padding: 10px 20px;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    opacity: 0.8;\n"
"}\n"
"QFrame {\n"
"    border-radius: 10px;\n"
"}\n"
"QLabel {\n"
"    color: #333333;\n"
"}\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.navbar = QtWidgets.QFrame(self.centralwidget)
        self.navbar.setMinimumSize(QtCore.QSize(0, 70))
        self.navbar.setMaximumSize(QtCore.QSize(16777215, 70))
        self.navbar.setStyleSheet("\n"
"QFrame#navbar {\n"
"    background-color: #750003;\n"
"}\n"
"QPushButton {\n"
"    color: white;\n"
"    background-color: transparent;\n"
"    text-align: left;\n"
"    padding: 15px 25px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.1);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 0.2);\n"
"}\n"
"       ")
        self.navbar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.navbar.setObjectName("navbar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.navbar)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logoLabel = QtWidgets.QLabel(self.navbar)
        self.logoLabel.setMinimumSize(QtCore.QSize(200, 0))
        self.logoLabel.setStyleSheet("color: white; font-size: 18px; font-weight: bold; padding-left: 20px;")
        self.logoLabel.setObjectName("logoLabel")
        self.horizontalLayout.addWidget(self.logoLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnDashboard = QtWidgets.QPushButton(self.navbar)
        self.btnDashboard.setMinimumSize(QtCore.QSize(120, 0))
        self.btnDashboard.setObjectName("btnDashboard")
        self.horizontalLayout.addWidget(self.btnDashboard)
        self.btnTransaksi = QtWidgets.QPushButton(self.navbar)
        self.btnTransaksi.setMinimumSize(QtCore.QSize(150, 0))
        self.btnTransaksi.setObjectName("btnTransaksi")
        self.horizontalLayout.addWidget(self.btnTransaksi)
        self.btnStok = QtWidgets.QPushButton(self.navbar)
        self.btnStok.setMinimumSize(QtCore.QSize(100, 0))
        self.btnStok.setObjectName("btnStok")
        self.horizontalLayout.addWidget(self.btnStok)
        self.btnValidasi = QtWidgets.QPushButton(self.navbar)
        self.btnValidasi.setMinimumSize(QtCore.QSize(180, 0))
        self.btnValidasi.setObjectName("btnValidasi")
        self.horizontalLayout.addWidget(self.btnValidasi)
        self.btnLaporan = QtWidgets.QPushButton(self.navbar)
        self.btnLaporan.setMinimumSize(QtCore.QSize(100, 0))
        self.btnLaporan.setObjectName("btnLaporan")
        self.horizontalLayout.addWidget(self.btnLaporan)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.navbar)
        self.stokDarahPage = QtWidgets.QWidget(self.centralwidget)
        self.stokDarahPage.setObjectName("stokDarahPage")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.stokDarahPage)
        self.verticalLayout_2.setContentsMargins(30, 30, 30, 30)
        self.verticalLayout_2.setSpacing(20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.titleLabel = QtWidgets.QLabel(self.stokDarahPage)
        self.titleLabel.setStyleSheet("font-size: 24px; font-weight: bold; color: #750003;")
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout_2.addWidget(self.titleLabel)
        self.filterLayout = QtWidgets.QHBoxLayout()
        self.filterLayout.setSpacing(15)
        self.filterLayout.setObjectName("filterLayout")
        self.filterGolongan = QtWidgets.QComboBox(self.stokDarahPage)
        self.filterGolongan.setMinimumSize(QtCore.QSize(150, 40))
        self.filterGolongan.setStyleSheet("\n"
"QComboBox {\n"
"    background-color: white;\n"
"    border: 2px solid #750003;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"    font-size: 14px;\n"
"}\n"
"QComboBox:hover {\n"
"    border-color: #950005;\n"
"}\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"}\n"
"QComboBox::down-arrow {\n"
"    image: none;\n"
"    border-left: 5px solid transparent;\n"
"    border-right: 5px solid transparent;\n"
"    border-top: 5px solid #750003;\n"
"    margin-right: 10px;\n"
"}\n"
"            ")
        self.filterGolongan.setObjectName("filterGolongan")
        self.filterGolongan.addItem("")
        self.filterGolongan.addItem("")
        self.filterGolongan.addItem("")
        self.filterGolongan.addItem("")
        self.filterGolongan.addItem("")
        self.filterGolongan.addItem("")
        self.filterGolongan.addItem("")
        self.filterGolongan.addItem("")
        self.filterGolongan.addItem("")
        self.filterLayout.addWidget(self.filterGolongan)
        self.filterStatus = QtWidgets.QComboBox(self.stokDarahPage)
        self.filterStatus.setMinimumSize(QtCore.QSize(150, 40))
        self.filterStatus.setStyleSheet("\n"
"QComboBox {\n"
"    background-color: white;\n"
"    border: 2px solid #750003;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"    font-size: 14px;\n"
"}\n"
"QComboBox:hover {\n"
"    border-color: #950005;\n"
"}\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"}\n"
"QComboBox::down-arrow {\n"
"    image: none;\n"
"    border-left: 5px solid transparent;\n"
"    border-right: 5px solid transparent;\n"
"    border-top: 5px solid #750003;\n"
"    margin-right: 10px;\n"
"}\n"
"            ")
        self.filterStatus.setObjectName("filterStatus")
        self.filterStatus.addItem("")
        self.filterStatus.addItem("")
        self.filterStatus.addItem("")
        self.filterStatus.addItem("")
        self.filterLayout.addWidget(self.filterStatus)
        self.searchBox = QtWidgets.QLineEdit(self.stokDarahPage)
        self.searchBox.setMinimumSize(QtCore.QSize(250, 40))
        self.searchBox.setStyleSheet("\n"
"QLineEdit {\n"
"    background-color: white;\n"
"    border: 2px solid #750003;\n"
"    border-radius: 5px;\n"
"    padding: 5px 15px;\n"
"    font-size: 14px;\n"
"}\n"
"QLineEdit:focus {\n"
"    border-color: #950005;\n"
"}\n"
"            ")
        self.searchBox.setObjectName("searchBox")
        self.filterLayout.addWidget(self.searchBox)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.filterLayout.addItem(spacerItem2)
        self.btnRefresh = QtWidgets.QPushButton(self.stokDarahPage)
        self.btnRefresh.setMinimumSize(QtCore.QSize(120, 40))
        self.btnRefresh.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: #750003;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #950005;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #550002;\n"
"}\n"
"            ")
        self.btnRefresh.setObjectName("btnRefresh")
        self.filterLayout.addWidget(self.btnRefresh)
        self.verticalLayout_2.addLayout(self.filterLayout)
        self.summaryLayout = QtWidgets.QHBoxLayout()
        self.summaryLayout.setSpacing(15)
        self.summaryLayout.setObjectName("summaryLayout")
        self.cardTotalStok = QtWidgets.QFrame(self.stokDarahPage)
        self.cardTotalStok.setStyleSheet("\n"
"QFrame#cardTotalStok {\n"
"    background-color: white;\n"
"    border: 2px solid #750003;\n"
"}\n"
"            ")
        self.cardTotalStok.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cardTotalStok.setObjectName("cardTotalStok")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.cardTotalStok)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.iconTotal = QtWidgets.QLabel(self.cardTotalStok)
        self.iconTotal.setStyleSheet("font-size: 36px; color: #750003;")
        self.iconTotal.setObjectName("iconTotal")
        self.horizontalLayout_2.addWidget(self.iconTotal)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lblTotalStok = QtWidgets.QLabel(self.cardTotalStok)
        self.lblTotalStok.setStyleSheet("font-size: 12px; color: #666;")
        self.lblTotalStok.setObjectName("lblTotalStok")
        self.verticalLayout_3.addWidget(self.lblTotalStok)
        self.valueTotalStok = QtWidgets.QLabel(self.cardTotalStok)
        self.valueTotalStok.setStyleSheet("font-size: 24px; font-weight: bold; color: #750003;")
        self.valueTotalStok.setObjectName("valueTotalStok")
        self.verticalLayout_3.addWidget(self.valueTotalStok)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.summaryLayout.addWidget(self.cardTotalStok)
        self.cardKritis = QtWidgets.QFrame(self.stokDarahPage)
        self.cardKritis.setStyleSheet("\n"
"QFrame#cardKritis {\n"
"    background-color: white;\n"
"    border: 2px solid #750003;\n"
"}\n"
"            ")
        self.cardKritis.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cardKritis.setObjectName("cardKritis")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.cardKritis)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.iconKritis = QtWidgets.QLabel(self.cardKritis)
        self.iconKritis.setStyleSheet("font-size: 36px; color: #750003;")
        self.iconKritis.setObjectName("iconKritis")
        self.horizontalLayout_3.addWidget(self.iconKritis)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lblKritis = QtWidgets.QLabel(self.cardKritis)
        self.lblKritis.setStyleSheet("font-size: 12px; color: #666;")
        self.lblKritis.setObjectName("lblKritis")
        self.verticalLayout_4.addWidget(self.lblKritis)
        self.valueKritis = QtWidgets.QLabel(self.cardKritis)
        self.valueKritis.setStyleSheet("font-size: 24px; font-weight: bold; color: #d32f2f;")
        self.valueKritis.setObjectName("valueKritis")
        self.verticalLayout_4.addWidget(self.valueKritis)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.summaryLayout.addWidget(self.cardKritis)
        self.cardKadaluarsa = QtWidgets.QFrame(self.stokDarahPage)
        self.cardKadaluarsa.setStyleSheet("\n"
"QFrame#cardKadaluarsa {\n"
"    background-color: white;\n"
"    border: 2px solid #750003;\n"
"}\n"
"            ")
        self.cardKadaluarsa.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cardKadaluarsa.setObjectName("cardKadaluarsa")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.cardKadaluarsa)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.iconKadaluarsa = QtWidgets.QLabel(self.cardKadaluarsa)
        self.iconKadaluarsa.setStyleSheet("font-size: 36px; color: #750003;")
        self.iconKadaluarsa.setObjectName("iconKadaluarsa")
        self.horizontalLayout_4.addWidget(self.iconKadaluarsa)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lblKadaluarsa = QtWidgets.QLabel(self.cardKadaluarsa)
        self.lblKadaluarsa.setStyleSheet("font-size: 12px; color: #666;")
        self.lblKadaluarsa.setObjectName("lblKadaluarsa")
        self.verticalLayout_5.addWidget(self.lblKadaluarsa)
        self.valueKadaluarsa = QtWidgets.QLabel(self.cardKadaluarsa)
        self.valueKadaluarsa.setStyleSheet("font-size: 24px; font-weight: bold; color: #f57c00;")
        self.valueKadaluarsa.setObjectName("valueKadaluarsa")
        self.verticalLayout_5.addWidget(self.valueKadaluarsa)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.summaryLayout.addWidget(self.cardKadaluarsa)
        self.verticalLayout_2.addLayout(self.summaryLayout)
        self.tableFrame = QtWidgets.QFrame(self.stokDarahPage)
        self.tableFrame.setStyleSheet("\n"
"QFrame#tableFrame {\n"
"    background-color: white;\n"
"    border: 1px solid #ddd;\n"
"}\n"
"          ")
        self.tableFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableFrame.setObjectName("tableFrame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tableFrame)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lblTableTitle = QtWidgets.QLabel(self.tableFrame)
        self.lblTableTitle.setStyleSheet("font-size: 18px; font-weight: bold; color: #750003; padding: 10px;")
        self.lblTableTitle.setObjectName("lblTableTitle")
        self.verticalLayout_6.addWidget(self.lblTableTitle)
        self.tableStok = QtWidgets.QTableWidget(self.tableFrame)
        self.tableStok.setStyleSheet("\n"
"QTableWidget {\n"
"    border: none;\n"
"    background-color: white;\n"
"    gridline-color: #f0f0f0;\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #750003;\n"
"    color: white;\n"
"    padding: 12px;\n"
"    border: none;\n"
"    font-weight: bold;\n"
"    font-size: 13px;\n"
"}\n"
"QTableWidget::item {\n"
"    padding: 10px;\n"
"    border-bottom: 1px solid #f0f0f0;\n"
"}\n"
"QTableWidget::item:selected {\n"
"    background-color: #ffeaea;\n"
"    color: #333333;\n"
"}\n"
"             ")
        self.tableStok.setAlternatingRowColors(True)
        self.tableStok.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableStok.setObjectName("tableStok")
        self.tableStok.setColumnCount(8)
        self.tableStok.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableStok.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableStok.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableStok.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableStok.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableStok.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableStok.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableStok.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableStok.setHorizontalHeaderItem(7, item)
        self.verticalLayout_6.addWidget(self.tableStok)
        self.verticalLayout_2.addWidget(self.tableFrame)
        self.verticalLayout.addWidget(self.stokDarahPage)
        MainWindow.setCentralWidget(self.centralwidget)
        self.btnRefresh.clicked.connect(self.load_stok_data)
        self.load_stok_data()
        


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
    def load_stok_data(self):
        self.valueTotalStok.setText(f"{get_total_stok()} Kantong")
        self.valueKritis.setText(f"{get_stok_kritis()} Golongan")
        self.valueKadaluarsa.setText(f"{get_stok_kadaluarsa()} Kantong")
        rows = get_all_stok()
        self.tableStok.setRowCount(len(rows))
        for i, row in enumerate(rows):
            for j, value in enumerate(row):
                self.tableStok.setItem(i, j, QtWidgets.QTableWidgetItem(str(value)))
        

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dashboard PMI - Donor Darah"))
        self.logoLabel.setText(_translate("MainWindow", "PMI DONOR DARAH"))
        self.btnDashboard.setText(_translate("MainWindow", "Dashboard"))
        self.btnTransaksi.setText(_translate("MainWindow", "Transaksi Darah"))
        self.btnStok.setText(_translate("MainWindow", "Stok Darah"))
        self.btnValidasi.setText(_translate("MainWindow", "Validasi Permintaan"))
        self.btnLaporan.setText(_translate("MainWindow", "Laporan"))
        self.titleLabel.setText(_translate("MainWindow", "Manajemen Stok Darah"))
        self.filterGolongan.setItemText(0, _translate("MainWindow", "Semua Golongan"))
        self.filterGolongan.setItemText(1, _translate("MainWindow", "A+"))
        self.filterGolongan.setItemText(2, _translate("MainWindow", "A-"))
        self.filterGolongan.setItemText(3, _translate("MainWindow", "B+"))
        self.filterGolongan.setItemText(4, _translate("MainWindow", "B-"))
        self.filterGolongan.setItemText(5, _translate("MainWindow", "AB+"))
        self.filterGolongan.setItemText(6, _translate("MainWindow", "AB-"))
        self.filterGolongan.setItemText(7, _translate("MainWindow", "O+"))
        self.filterGolongan.setItemText(8, _translate("MainWindow", "O-"))
        self.filterStatus.setItemText(0, _translate("MainWindow", "Semua Status"))
        self.filterStatus.setItemText(1, _translate("MainWindow", "Tersedia"))
        self.filterStatus.setItemText(2, _translate("MainWindow", "Kritis"))
        self.filterStatus.setItemText(3, _translate("MainWindow", "Segera Kadaluarsa"))
        self.searchBox.setPlaceholderText(_translate("MainWindow", "Cari nomor kantong..."))
        self.btnRefresh.setText(_translate("MainWindow", "🔄 Refresh"))
        self.iconTotal.setText(_translate("MainWindow", "📦"))
        self.lblTotalStok.setText(_translate("MainWindow", "Total Stok"))
        self.valueTotalStok.setText(_translate("MainWindow", "-"))
        self.iconKritis.setText(_translate("MainWindow", "⚠️"))
        self.lblKritis.setText(_translate("MainWindow", "Stok Kritis"))
        self.valueKritis.setText(_translate("MainWindow", "3 Golongan"))
        self.iconKadaluarsa.setText(_translate("MainWindow", "⏰"))
        self.lblKadaluarsa.setText(_translate("MainWindow", "Segera Kadaluarsa"))
        self.valueKadaluarsa.setText(_translate("MainWindow", "12 Kantong"))
        self.lblTableTitle.setText(_translate("MainWindow", "Daftar Stok Darah"))
        item = self.tableStok.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "No. Kantong"))
        item = self.tableStok.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Golongan Darah"))
        item = self.tableStok.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Rhesus"))
        item = self.tableStok.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Tgl Donor"))
        item = self.tableStok.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Tgl Kadaluarsa"))
        item = self.tableStok.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Status"))
        item = self.tableStok.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Lokasi Penyimpanan"))
        item = self.tableStok.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Aksi"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
