# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'transaksidarah.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from DARAH import *
from TRANSAKSI import *


class Ui_MainWindow(object):
    def set_petugas(self, id_user):
        self.id_petugas = id_user

    def setupUi(self, MainWindow):
        self.mainwindow = MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        MainWindow.setStyleSheet("\n"
"QMainWindow {\n"
"    background-color: #f5f5f5;\n"
"}\n"
"QPushButton {\n"
"    border: none;\n"
"    padding: 10px 20px;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    opacity: 0.8;\n"
"}\n"
"QFrame {\n"
"    border-radius: 10px;\n"
"}\n"
"QLabel {\n"
"    color: #333333;\n"
"}\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.navbar = QtWidgets.QFrame(self.centralwidget)
        self.navbar.setMinimumSize(QtCore.QSize(0, 70))
        self.navbar.setMaximumSize(QtCore.QSize(16777215, 70))
        self.navbar.setStyleSheet("\n"
"QFrame#navbar {\n"
"    background-color: #750003;\n"
"}\n"
"QPushButton {\n"
"    color: white;\n"
"    background-color: transparent;\n"
"    text-align: left;\n"
"    padding: 15px 25px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.1);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 0.2);\n"
"}\n"
"       ")
        self.navbar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.navbar.setObjectName("navbar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.navbar)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logoLabel = QtWidgets.QLabel(self.navbar)
        self.logoLabel.setMinimumSize(QtCore.QSize(200, 0))
        self.logoLabel.setStyleSheet("color: white; font-size: 18px; font-weight: bold; padding-left: 20px;")
        self.logoLabel.setObjectName("logoLabel")
        self.horizontalLayout.addWidget(self.logoLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnDashboard = QtWidgets.QPushButton(self.navbar)
        self.btnDashboard.setMinimumSize(QtCore.QSize(120, 0))
        self.btnDashboard.setObjectName("btnDashboard")
        self.horizontalLayout.addWidget(self.btnDashboard)
        self.btnTransaksi = QtWidgets.QPushButton(self.navbar)
        self.btnTransaksi.setMinimumSize(QtCore.QSize(150, 0))
        self.btnTransaksi.setObjectName("btnTransaksi")
        self.horizontalLayout.addWidget(self.btnTransaksi)
        self.btnStok = QtWidgets.QPushButton(self.navbar)
        self.btnStok.setMinimumSize(QtCore.QSize(100, 0))
        self.btnStok.setObjectName("btnStok")
        self.horizontalLayout.addWidget(self.btnStok)
        self.btnValidasi = QtWidgets.QPushButton(self.navbar)
        self.btnValidasi.setMinimumSize(QtCore.QSize(180, 0))
        self.btnValidasi.setObjectName("btnValidasi")
        self.horizontalLayout.addWidget(self.btnValidasi)
        self.btnLaporan = QtWidgets.QPushButton(self.navbar)
        self.btnLaporan.setMinimumSize(QtCore.QSize(100, 0))
        self.btnLaporan.setObjectName("btnLaporan")
        self.horizontalLayout.addWidget(self.btnLaporan)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.navbar)
        self.transaksiPage = QtWidgets.QWidget(self.centralwidget)
        self.transaksiPage.setObjectName("transaksiPage")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.transaksiPage)
        self.verticalLayout_2.setContentsMargins(30, 30, 30, 30)
        self.verticalLayout_2.setSpacing(20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.titleLabel = QtWidgets.QLabel(self.transaksiPage)
        self.titleLabel.setStyleSheet("font-size: 24px; font-weight: bold; color: #750003;")
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout_2.addWidget(self.titleLabel)
        self.actionLayout = QtWidgets.QHBoxLayout()
        self.actionLayout.setSpacing(15)
        self.actionLayout.setObjectName("actionLayout")
        self.btnDonorMasuk = QtWidgets.QPushButton(self.transaksiPage)
        self.btnDonorMasuk.setMinimumSize(QtCore.QSize(150, 40))
        self.btnDonorMasuk.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: #750003;\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"    padding: 10px 20px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #8b0003;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #5a0002;\n"
"}\n"
"            ")
        self.btnDonorMasuk.setObjectName("btnDonorMasuk")
        self.actionLayout.addWidget(self.btnDonorMasuk)
        self.btnDonorKeluar = QtWidgets.QPushButton(self.transaksiPage)
        self.btnDonorKeluar.setMinimumSize(QtCore.QSize(150, 40))
        self.btnDonorKeluar.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: white;\n"
"    color: #750003;\n"
"    border: 2px solid #750003;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"    padding: 10px 20px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #f5f5f5;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #e8e8e8;\n"
"}\n"
"            ")
        self.btnDonorKeluar.setObjectName("btnDonorKeluar")
        self.actionLayout.addWidget(self.btnDonorKeluar)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.actionLayout.addItem(spacerItem2)
        self.searchInput = QtWidgets.QLineEdit(self.transaksiPage)
        self.searchInput.setMinimumSize(QtCore.QSize(250, 40))
        self.searchInput.setStyleSheet("\n"
"QLineEdit {\n"
"    background-color: white;\n"
"    border: 2px solid #ddd;\n"
"    border-radius: 5px;\n"
"    padding: 8px 15px;\n"
"    font-size: 14px;\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #750003;\n"
"}\n"
"            ")
        self.searchInput.setObjectName("searchInput")
        self.actionLayout.addWidget(self.searchInput)
        self.verticalLayout_2.addLayout(self.actionLayout)
        self.statsRowLayout = QtWidgets.QHBoxLayout()
        self.statsRowLayout.setSpacing(15)
        self.statsRowLayout.setObjectName("statsRowLayout")
        self.cardMasuk = QtWidgets.QFrame(self.transaksiPage)
        self.cardMasuk.setStyleSheet("\n"
"QFrame#cardMasuk {\n"
"    background-color: white;\n"
"    border: 2px solid #750003;\n"
"    border-radius: 10px;\n"
"}\n"
"            ")
        self.cardMasuk.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cardMasuk.setObjectName("cardMasuk")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.cardMasuk)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.iconMasuk = QtWidgets.QLabel(self.cardMasuk)
        self.iconMasuk.setMinimumSize(QtCore.QSize(50, 50))
        self.iconMasuk.setStyleSheet("font-size: 32px; color: #750003;")
        self.iconMasuk.setAlignment(QtCore.Qt.AlignCenter)
        self.iconMasuk.setObjectName("iconMasuk")
        self.horizontalLayout_2.addWidget(self.iconMasuk)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lblMasuk = QtWidgets.QLabel(self.cardMasuk)
        self.lblMasuk.setStyleSheet("font-size: 12px; color: #666;")
        self.lblMasuk.setObjectName("lblMasuk")
        self.verticalLayout_3.addWidget(self.lblMasuk)
        self.valueMasuk = QtWidgets.QLabel(self.cardMasuk)
        self.valueMasuk.setStyleSheet("font-size: 24px; font-weight: bold; color: #750003;")
        self.valueMasuk.setObjectName("valueMasuk")
        self.verticalLayout_3.addWidget(self.valueMasuk)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.statsRowLayout.addWidget(self.cardMasuk)
        self.cardKeluar = QtWidgets.QFrame(self.transaksiPage)
        self.cardKeluar.setStyleSheet("\n"
"QFrame#cardKeluar {\n"
"    background-color: white;\n"
"    border: 2px solid #750003;\n"
"    border-radius: 10px;\n"
"}\n"
"            ")
        self.cardKeluar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cardKeluar.setObjectName("cardKeluar")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.cardKeluar)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.iconKeluar = QtWidgets.QLabel(self.cardKeluar)
        self.iconKeluar.setMinimumSize(QtCore.QSize(50, 50))
        self.iconKeluar.setStyleSheet("font-size: 32px; color: #750003;")
        self.iconKeluar.setAlignment(QtCore.Qt.AlignCenter)
        self.iconKeluar.setObjectName("iconKeluar")
        self.horizontalLayout_3.addWidget(self.iconKeluar)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lblKeluar = QtWidgets.QLabel(self.cardKeluar)
        self.lblKeluar.setStyleSheet("font-size: 12px; color: #666;")
        self.lblKeluar.setObjectName("lblKeluar")
        self.verticalLayout_4.addWidget(self.lblKeluar)
        self.valueKeluar = QtWidgets.QLabel(self.cardKeluar)
        self.valueKeluar.setStyleSheet("font-size: 24px; font-weight: bold; color: #750003;")
        self.valueKeluar.setObjectName("valueKeluar")
        self.verticalLayout_4.addWidget(self.valueKeluar)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.statsRowLayout.addWidget(self.cardKeluar)
        self.cardTotal = QtWidgets.QFrame(self.transaksiPage)
        self.cardTotal.setStyleSheet("\n"
"QFrame#cardTotal {\n"
"    background-color: white;\n"
"    border: 2px solid #750003;\n"
"    border-radius: 10px;\n"
"}\n"
"            ")
        self.cardTotal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cardTotal.setObjectName("cardTotal")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.cardTotal)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.iconTotal = QtWidgets.QLabel(self.cardTotal)
        self.iconTotal.setMinimumSize(QtCore.QSize(50, 50))
        self.iconTotal.setStyleSheet("font-size: 32px; color: #750003;")
        self.iconTotal.setAlignment(QtCore.Qt.AlignCenter)
        self.iconTotal.setObjectName("iconTotal")
        self.horizontalLayout_4.addWidget(self.iconTotal)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lblTotal = QtWidgets.QLabel(self.cardTotal)
        self.lblTotal.setStyleSheet("font-size: 12px; color: #666;")
        self.lblTotal.setObjectName("lblTotal")
        self.verticalLayout_5.addWidget(self.lblTotal)
        self.valueTotal = QtWidgets.QLabel(self.cardTotal)
        self.valueTotal.setStyleSheet("font-size: 24px; font-weight: bold; color: #750003;")
        self.valueTotal.setObjectName("valueTotal")
        self.verticalLayout_5.addWidget(self.valueTotal)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.statsRowLayout.addWidget(self.cardTotal)
        self.verticalLayout_2.addLayout(self.statsRowLayout)
        self.tableFrame = QtWidgets.QFrame(self.transaksiPage)
        self.tableFrame.setStyleSheet("\n"
"QFrame#tableFrame {\n"
"    background-color: white;\n"
"    border: 1px solid #ddd;\n"
"    border-radius: 10px;\n"
"}\n"
"          ")
        self.tableFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableFrame.setObjectName("tableFrame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tableFrame)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lblTableTitle = QtWidgets.QLabel(self.tableFrame)
        self.lblTableTitle.setStyleSheet("font-size: 18px; font-weight: bold; color: #750003; padding: 10px;")
        self.lblTableTitle.setObjectName("lblTableTitle")
        self.verticalLayout_6.addWidget(self.lblTableTitle)
        self.tableTransaksi = QtWidgets.QTableWidget(self.tableFrame)
        self.tableTransaksi.setStyleSheet("\n"
"QTableWidget {\n"
"    border: none;\n"
"    background-color: white;\n"
"    gridline-color: #f0f0f0;\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #750003;\n"
"    color: white;\n"
"    padding: 12px;\n"
"    border: none;\n"
"    font-weight: bold;\n"
"    font-size: 13px;\n"
"}\n"
"QTableWidget::item {\n"
"    padding: 10px;\n"
"    border-bottom: 1px solid #f0f0f0;\n"
"}\n"
"QTableWidget::item:selected {\n"
"    background-color: #f5e6e6;\n"
"    color: #750003;\n"
"}\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: #f5f5f5;\n"
"    width: 10px;\n"
"    margin: 0px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background-color: #750003;\n"
"    border-radius: 5px;\n"
"    min-height: 20px;\n"
"}\n"
"QScrollBar::handle:vertical:hover {\n"
"    background-color: #8b0003;\n"
"}\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    height: 0px;\n"
"}\n"
"             ")
        self.tableTransaksi.setAlternatingRowColors(True)
        self.tableTransaksi.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableTransaksi.setObjectName("tableTransaksi")
        self.tableTransaksi.setColumnCount(8)
        self.tableTransaksi.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableTransaksi.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTransaksi.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTransaksi.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTransaksi.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTransaksi.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTransaksi.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTransaksi.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTransaksi.setHorizontalHeaderItem(7, item)
        self.verticalLayout_6.addWidget(self.tableTransaksi)
        self.verticalLayout_2.addWidget(self.tableFrame)
        self.verticalLayout.addWidget(self.transaksiPage)
        MainWindow.setCentralWidget(self.centralwidget)
        self.btnValidasi.clicked.connect(self.buka_validasi)
        self.btnLaporan.clicked.connect(self.buka_laporan)
        self.btnStok.clicked.connect(self.buka_stok)
        self.btnDashboard.clicked.connect(self.balik_dashboard)
        self.btnDonorMasuk.clicked.connect(self.load_darah_masuk)
        self.btnDonorKeluar.clicked.connect(self.load_darah_keluar)


        
        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
    def load_darah_masuk(self):
        data = darah_masuk_today()
        self.load_data(data)

    def load_darah_keluar(self):
        data = darah_keluar_today()
        self.load_data(data)

        
    def balik_dashboard(self):
        import dasboardpetugas
        self.dashboardwindow = QtWidgets.QMainWindow()
        self.ui = dasboardpetugas.Ui_MainWindow()
        self.ui.set_petugas(self.id_petugas)
        self.ui.setupUi(self.dashboardwindow)
        self.dashboardwindow.show()
        self.mainwindow.close()
        
    def buka_validasi(self):
        import validasi
        self.validasi_window = QtWidgets.QMainWindow()
        self.ui = validasi.Ui_MainWindow()
        self.ui.set_petugas(self.id_petugas)
        self.ui.setupUi(self.validasi_window)
        self.validasi_window.show()
        self.mainwindow.hide()
        
    def buka_laporan(self):
        import laporan
        self.laporan_window = QtWidgets.QMainWindow()
        self.ui = laporan.Ui_MainWindow()
        self.ui.set_petugas(self.id_petugas)
        self.ui.setupUi(self.laporan_window)
        self.laporan_window.show()
        self.mainwindow.hide()
        
    def buka_stok(self):
        import stokdarah
        self.stok_window = QtWidgets.QMainWindow()
        self.ui = stokdarah.Ui_MainWindow()
        self.ui.set_petugas(self.id_petugas)
        self.ui.setupUi(self.stok_window)
        self.stok_window.show()
        self.mainwindow.hide()
        
        
    def load_data(self, mode="ALL"):
          # LABEL STATISTIK
          self.valueMasuk.setText(f"{get_donor_masuk_hari_ini()} kantong")
          self.valueKeluar.setText(f"{get_darah_keluar_hari_ini()} kantong")
          self.valueTotal.setText(f"{get_total_transaksi_bulan_ini()} Kantong")

          # FILTER DATA TABEL
          if mode == "MASUK":
              rows = get_donor_masuk_hari_ini()
          elif mode == "KELUAR":
              rows = get_riwayat_transaksi_keluar()
          else:
              rows = get_riwayat_transaksi()

          self.tableTransaksi.setRowCount(0)

          for i, row in enumerate(rows):
              self.tableTransaksi.insertRow(i)
              for j, val in enumerate(row):
                  self.tableTransaksi.setItem(
                      i, j, QtWidgets.QTableWidgetItem(str(val))
                  )

                
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dashboard PMI - Donor Darah"))
        self.logoLabel.setText(_translate("MainWindow", "PMI DONOR DARAH"))
        self.btnDashboard.setText(_translate("MainWindow", "Dashboard"))
        self.btnTransaksi.setText(_translate("MainWindow", "Transaksi Darah"))
        self.btnStok.setText(_translate("MainWindow", "Stok Darah"))
        self.btnValidasi.setText(_translate("MainWindow", "Validasi Permintaan"))
        self.btnLaporan.setText(_translate("MainWindow", "Laporan"))
        self.titleLabel.setText(_translate("MainWindow", "Transaksi Darah"))
        self.btnDonorMasuk.setText(_translate("MainWindow", "+ Donor Masuk"))
        self.btnDonorKeluar.setText(_translate("MainWindow", "- Darah Keluar"))
        self.searchInput.setPlaceholderText(_translate("MainWindow", "🔍 Cari transaksi..."))
        self.iconMasuk.setText(_translate("MainWindow", "📥"))
        self.lblMasuk.setText(_translate("MainWindow", "Donor Masuk Hari Ini"))
        self.valueMasuk.setText(_translate("MainWindow", "47 kantong"))
        self.iconKeluar.setText(_translate("MainWindow", "📤"))
        self.lblKeluar.setText(_translate("MainWindow", "Darah Keluar Hari Ini"))
        self.valueKeluar.setText(_translate("MainWindow", "18 kantong"))
        self.iconTotal.setText(_translate("MainWindow", "📊"))
        self.lblTotal.setText(_translate("MainWindow", "Total Transaksi Bulan Ini"))
        self.valueTotal.setText(_translate("MainWindow", "1,245"))
        self.lblTableTitle.setText(_translate("MainWindow", "Riwayat Transaksi"))
        item = self.tableTransaksi.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID Transaksi"))
        item = self.tableTransaksi.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Tanggal"))
        item = self.tableTransaksi.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Tipe"))
        item = self.tableTransaksi.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Golongan Darah"))
        item = self.tableTransaksi.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Jumlah"))
        item = self.tableTransaksi.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Pendonor/Penerima"))
        item = self.tableTransaksi.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Status"))
        item = self.tableTransaksi.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Aksi"))
        self.load_data()
        



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
