# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'validasi.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        MainWindow.setStyleSheet("\n"
"QMainWindow {\n"
"    background-color: #f5f5f5;\n"
"}\n"
"QPushButton {\n"
"    border: none;\n"
"    padding: 10px 20px;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    opacity: 0.8;\n"
"}\n"
"QFrame {\n"
"    border-radius: 10px;\n"
"}\n"
"QLabel {\n"
"    color: #333333;\n"
"}\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.navbar = QtWidgets.QFrame(self.centralwidget)
        self.navbar.setMinimumSize(QtCore.QSize(0, 70))
        self.navbar.setMaximumSize(QtCore.QSize(16777215, 70))
        self.navbar.setStyleSheet("\n"
"QFrame#navbar {\n"
"    background-color: #750003;\n"
"}\n"
"QPushButton {\n"
"    color: white;\n"
"    background-color: transparent;\n"
"    text-align: left;\n"
"    padding: 15px 25px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.1);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 0.2);\n"
"}\n"
"       ")
        self.navbar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.navbar.setObjectName("navbar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.navbar)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logoLabel = QtWidgets.QLabel(self.navbar)
        self.logoLabel.setMinimumSize(QtCore.QSize(200, 0))
        self.logoLabel.setStyleSheet("color: white; font-size: 18px; font-weight: bold; padding-left: 20px;")
        self.logoLabel.setObjectName("logoLabel")
        self.horizontalLayout.addWidget(self.logoLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnDashboard = QtWidgets.QPushButton(self.navbar)
        self.btnDashboard.setMinimumSize(QtCore.QSize(120, 0))
        self.btnDashboard.setObjectName("btnDashboard")
        self.horizontalLayout.addWidget(self.btnDashboard)
        self.btnTransaksi = QtWidgets.QPushButton(self.navbar)
        self.btnTransaksi.setMinimumSize(QtCore.QSize(150, 0))
        self.btnTransaksi.setObjectName("btnTransaksi")
        self.horizontalLayout.addWidget(self.btnTransaksi)
        self.btnStok = QtWidgets.QPushButton(self.navbar)
        self.btnStok.setMinimumSize(QtCore.QSize(100, 0))
        self.btnStok.setObjectName("btnStok")
        self.horizontalLayout.addWidget(self.btnStok)
        self.btnValidasi = QtWidgets.QPushButton(self.navbar)
        self.btnValidasi.setMinimumSize(QtCore.QSize(180, 0))
        self.btnValidasi.setObjectName("btnValidasi")
        self.horizontalLayout.addWidget(self.btnValidasi)
        self.btnLaporan = QtWidgets.QPushButton(self.navbar)
        self.btnLaporan.setMinimumSize(QtCore.QSize(100, 0))
        self.btnLaporan.setObjectName("btnLaporan")
        self.horizontalLayout.addWidget(self.btnLaporan)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.navbar)
        self.validasiPermintaanPage = QtWidgets.QWidget(self.centralwidget)
        self.validasiPermintaanPage.setObjectName("validasiPermintaanPage")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.validasiPermintaanPage)
        self.verticalLayout_2.setContentsMargins(30, 30, 30, 30)
        self.verticalLayout_2.setSpacing(20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.titleLabel = QtWidgets.QLabel(self.validasiPermintaanPage)
        self.titleLabel.setStyleSheet("font-size: 24px; font-weight: bold; color: #750003;")
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout_2.addWidget(self.titleLabel)
        self.filterLayout = QtWidgets.QHBoxLayout()
        self.filterLayout.setSpacing(15)
        self.filterLayout.setObjectName("filterLayout")
        self.filterStatus = QtWidgets.QComboBox(self.validasiPermintaanPage)
        self.filterStatus.setMinimumSize(QtCore.QSize(150, 40))
        self.filterStatus.setStyleSheet("\n"
"QComboBox {\n"
"    background-color: white;\n"
"    border: 2px solid #750003;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"    font-size: 14px;\n"
"}\n"
"QComboBox:hover {\n"
"    border-color: #950005;\n"
"}\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"}\n"
"QComboBox::down-arrow {\n"
"    image: none;\n"
"    border-left: 5px solid transparent;\n"
"    border-right: 5px solid transparent;\n"
"    border-top: 5px solid #750003;\n"
"    margin-right: 10px;\n"
"}\n"
"            ")
        self.filterStatus.setObjectName("filterStatus")
        self.filterStatus.addItem("")
        self.filterStatus.addItem("")
        self.filterStatus.addItem("")
        self.filterStatus.addItem("")
        self.filterLayout.addWidget(self.filterStatus)
        self.filterPrioritas = QtWidgets.QComboBox(self.validasiPermintaanPage)
        self.filterPrioritas.setMinimumSize(QtCore.QSize(150, 40))
        self.filterPrioritas.setStyleSheet("\n"
"QComboBox {\n"
"    background-color: white;\n"
"    border: 2px solid #750003;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"    font-size: 14px;\n"
"}\n"
"QComboBox:hover {\n"
"    border-color: #950005;\n"
"}\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"}\n"
"QComboBox::down-arrow {\n"
"    image: none;\n"
"    border-left: 5px solid transparent;\n"
"    border-right: 5px solid transparent;\n"
"    border-top: 5px solid #750003;\n"
"    margin-right: 10px;\n"
"}\n"
"            ")
        self.filterPrioritas.setObjectName("filterPrioritas")
        self.filterPrioritas.addItem("")
        self.filterPrioritas.addItem("")
        self.filterPrioritas.addItem("")
        self.filterPrioritas.addItem("")
        self.filterLayout.addWidget(self.filterPrioritas)
        self.searchBox = QtWidgets.QLineEdit(self.validasiPermintaanPage)
        self.searchBox.setMinimumSize(QtCore.QSize(250, 40))
        self.searchBox.setStyleSheet("\n"
"QLineEdit {\n"
"    background-color: white;\n"
"    border: 2px solid #750003;\n"
"    border-radius: 5px;\n"
"    padding: 5px 15px;\n"
"    font-size: 14px;\n"
"}\n"
"QLineEdit:focus {\n"
"    border-color: #950005;\n"
"}\n"
"            ")
        self.searchBox.setObjectName("searchBox")
        self.filterLayout.addWidget(self.searchBox)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.filterLayout.addItem(spacerItem2)
        self.btnRefresh = QtWidgets.QPushButton(self.validasiPermintaanPage)
        self.btnRefresh.setMinimumSize(QtCore.QSize(120, 40))
        self.btnRefresh.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: #750003;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #950005;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #550002;\n"
"}\n"
"            ")
        self.btnRefresh.setObjectName("btnRefresh")
        self.filterLayout.addWidget(self.btnRefresh)
        self.verticalLayout_2.addLayout(self.filterLayout)
        self.summaryLayout = QtWidgets.QHBoxLayout()
        self.summaryLayout.setSpacing(15)
        self.summaryLayout.setObjectName("summaryLayout")
        self.cardPending = QtWidgets.QFrame(self.validasiPermintaanPage)
        self.cardPending.setStyleSheet("\n"
"QFrame#cardPending {\n"
"    background-color: white;\n"
"    border: 2px solid #750003;\n"
"}\n"
"            ")
        self.cardPending.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cardPending.setObjectName("cardPending")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.cardPending)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.iconPending = QtWidgets.QLabel(self.cardPending)
        self.iconPending.setStyleSheet("font-size: 36px; color: #f57c00;")
        self.iconPending.setObjectName("iconPending")
        self.horizontalLayout_2.addWidget(self.iconPending)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lblPending = QtWidgets.QLabel(self.cardPending)
        self.lblPending.setStyleSheet("font-size: 12px; color: #666;")
        self.lblPending.setObjectName("lblPending")
        self.verticalLayout_3.addWidget(self.lblPending)
        self.valuePending = QtWidgets.QLabel(self.cardPending)
        self.valuePending.setStyleSheet("font-size: 24px; font-weight: bold; color: #f57c00;")
        self.valuePending.setObjectName("valuePending")
        self.verticalLayout_3.addWidget(self.valuePending)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.summaryLayout.addWidget(self.cardPending)
        self.cardDisetujui = QtWidgets.QFrame(self.validasiPermintaanPage)
        self.cardDisetujui.setStyleSheet("\n"
"QFrame#cardDisetujui {\n"
"    background-color: white;\n"
"    border: 2px solid #750003;\n"
"}\n"
"            ")
        self.cardDisetujui.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cardDisetujui.setObjectName("cardDisetujui")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.cardDisetujui)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.iconDisetujui = QtWidgets.QLabel(self.cardDisetujui)
        self.iconDisetujui.setStyleSheet("font-size: 36px; color: #4caf50;")
        self.iconDisetujui.setObjectName("iconDisetujui")
        self.horizontalLayout_3.addWidget(self.iconDisetujui)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lblDisetujui = QtWidgets.QLabel(self.cardDisetujui)
        self.lblDisetujui.setStyleSheet("font-size: 12px; color: #666;")
        self.lblDisetujui.setObjectName("lblDisetujui")
        self.verticalLayout_4.addWidget(self.lblDisetujui)
        self.valueDisetujui = QtWidgets.QLabel(self.cardDisetujui)
        self.valueDisetujui.setStyleSheet("font-size: 24px; font-weight: bold; color: #4caf50;")
        self.valueDisetujui.setObjectName("valueDisetujui")
        self.verticalLayout_4.addWidget(self.valueDisetujui)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.summaryLayout.addWidget(self.cardDisetujui)
        self.cardDitolak = QtWidgets.QFrame(self.validasiPermintaanPage)
        self.cardDitolak.setStyleSheet("\n"
"QFrame#cardDitolak {\n"
"    background-color: white;\n"
"    border: 2px solid #750003;\n"
"}\n"
"            ")
        self.cardDitolak.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cardDitolak.setObjectName("cardDitolak")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.cardDitolak)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.iconDitolak = QtWidgets.QLabel(self.cardDitolak)
        self.iconDitolak.setStyleSheet("font-size: 36px; color: #d32f2f;")
        self.iconDitolak.setObjectName("iconDitolak")
        self.horizontalLayout_4.addWidget(self.iconDitolak)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lblDitolak = QtWidgets.QLabel(self.cardDitolak)
        self.lblDitolak.setStyleSheet("font-size: 12px; color: #666;")
        self.lblDitolak.setObjectName("lblDitolak")
        self.verticalLayout_5.addWidget(self.lblDitolak)
        self.valueDitolak = QtWidgets.QLabel(self.cardDitolak)
        self.valueDitolak.setStyleSheet("font-size: 24px; font-weight: bold; color: #d32f2f;")
        self.valueDitolak.setObjectName("valueDitolak")
        self.verticalLayout_5.addWidget(self.valueDitolak)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.summaryLayout.addWidget(self.cardDitolak)
        self.cardEmergency = QtWidgets.QFrame(self.validasiPermintaanPage)
        self.cardEmergency.setStyleSheet("\n"
"QFrame#cardEmergency {\n"
"    background-color: white;\n"
"    border: 2px solid #750003;\n"
"}\n"
"            ")
        self.cardEmergency.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cardEmergency.setObjectName("cardEmergency")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.cardEmergency)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.iconEmergency = QtWidgets.QLabel(self.cardEmergency)
        self.iconEmergency.setStyleSheet("font-size: 36px; color: #750003;")
        self.iconEmergency.setObjectName("iconEmergency")
        self.horizontalLayout_5.addWidget(self.iconEmergency)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lblEmergency = QtWidgets.QLabel(self.cardEmergency)
        self.lblEmergency.setStyleSheet("font-size: 12px; color: #666;")
        self.lblEmergency.setObjectName("lblEmergency")
        self.verticalLayout_6.addWidget(self.lblEmergency)
        self.valueEmergency = QtWidgets.QLabel(self.cardEmergency)
        self.valueEmergency.setStyleSheet("font-size: 24px; font-weight: bold; color: #750003;")
        self.valueEmergency.setObjectName("valueEmergency")
        self.verticalLayout_6.addWidget(self.valueEmergency)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.summaryLayout.addWidget(self.cardEmergency)
        self.verticalLayout_2.addLayout(self.summaryLayout)
        self.tableFrame = QtWidgets.QFrame(self.validasiPermintaanPage)
        self.tableFrame.setStyleSheet("\n"
"QFrame#tableFrame {\n"
"    background-color: white;\n"
"    border: 1px solid #ddd;\n"
"}\n"
"          ")
        self.tableFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableFrame.setObjectName("tableFrame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tableFrame)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.lblTableTitle = QtWidgets.QLabel(self.tableFrame)
        self.lblTableTitle.setStyleSheet("font-size: 18px; font-weight: bold; color: #750003; padding: 10px;")
        self.lblTableTitle.setObjectName("lblTableTitle")
        self.verticalLayout_7.addWidget(self.lblTableTitle)
        self.tablePermintaan = QtWidgets.QTableWidget(self.tableFrame)
        self.tablePermintaan.setStyleSheet("\n"
"QTableWidget {\n"
"    border: none;\n"
"    background-color: white;\n"
"    gridline-color: #f0f0f0;\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #750003;\n"
"    color: white;\n"
"    padding: 12px;\n"
"    border: none;\n"
"    font-weight: bold;\n"
"    font-size: 13px;\n"
"}\n"
"QTableWidget::item {\n"
"    padding: 10px;\n"
"    border-bottom: 1px solid #f0f0f0;\n"
"}\n"
"QTableWidget::item:selected {\n"
"    background-color: #ffeaea;\n"
"    color: #333333;\n"
"}\n"
"             ")
        self.tablePermintaan.setAlternatingRowColors(True)
        self.tablePermintaan.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tablePermintaan.setObjectName("tablePermintaan")
        self.tablePermintaan.setColumnCount(9)
        self.tablePermintaan.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablePermintaan.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePermintaan.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePermintaan.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePermintaan.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePermintaan.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePermintaan.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePermintaan.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePermintaan.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePermintaan.setHorizontalHeaderItem(8, item)
        self.verticalLayout_7.addWidget(self.tablePermintaan)
        self.verticalLayout_2.addWidget(self.tableFrame)
        self.verticalLayout.addWidget(self.validasiPermintaanPage)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dashboard PMI - Donor Darah"))
        self.logoLabel.setText(_translate("MainWindow", "PMI DONOR DARAH"))
        self.btnDashboard.setText(_translate("MainWindow", "Dashboard"))
        self.btnTransaksi.setText(_translate("MainWindow", "Transaksi Darah"))
        self.btnStok.setText(_translate("MainWindow", "Stok Darah"))
        self.btnValidasi.setText(_translate("MainWindow", "Validasi Permintaan"))
        self.btnLaporan.setText(_translate("MainWindow", "Laporan"))
        self.titleLabel.setText(_translate("MainWindow", "Validasi Permintaan Darah"))
        self.filterStatus.setItemText(0, _translate("MainWindow", "Semua Status"))
        self.filterStatus.setItemText(1, _translate("MainWindow", "Pending"))
        self.filterStatus.setItemText(2, _translate("MainWindow", "Disetujui"))
        self.filterStatus.setItemText(3, _translate("MainWindow", "Ditolak"))
        self.filterPrioritas.setItemText(0, _translate("MainWindow", "Semua Prioritas"))
        self.filterPrioritas.setItemText(1, _translate("MainWindow", "Emergency"))
        self.filterPrioritas.setItemText(2, _translate("MainWindow", "Urgent"))
        self.filterPrioritas.setItemText(3, _translate("MainWindow", "Normal"))
        self.searchBox.setPlaceholderText(_translate("MainWindow", "Cari rumah sakit atau nomor permintaan..."))
        self.btnRefresh.setText(_translate("MainWindow", "🔄 Refresh"))
        self.iconPending.setText(_translate("MainWindow", "⏳"))
        self.lblPending.setText(_translate("MainWindow", "Menunggu Validasi"))
        self.valuePending.setText(_translate("MainWindow", "12 Permintaan"))
        self.iconDisetujui.setText(_translate("MainWindow", "✅"))
        self.lblDisetujui.setText(_translate("MainWindow", "Disetujui Hari Ini"))
        self.valueDisetujui.setText(_translate("MainWindow", "8 Permintaan"))
        self.iconDitolak.setText(_translate("MainWindow", "❌"))
        self.lblDitolak.setText(_translate("MainWindow", "Ditolak Hari Ini"))
        self.valueDitolak.setText(_translate("MainWindow", "2 Permintaan"))
        self.iconEmergency.setText(_translate("MainWindow", "🚨"))
        self.lblEmergency.setText(_translate("MainWindow", "Emergency"))
        self.valueEmergency.setText(_translate("MainWindow", "3 Permintaan"))
        self.lblTableTitle.setText(_translate("MainWindow", "Daftar Permintaan Darah"))
        item = self.tablePermintaan.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "No. Permintaan"))
        item = self.tablePermintaan.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Rumah Sakit"))
        item = self.tablePermintaan.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Nama Pasien"))
        item = self.tablePermintaan.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Golongan Darah"))
        item = self.tablePermintaan.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Jumlah"))
        item = self.tablePermintaan.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Prioritas"))
        item = self.tablePermintaan.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Tgl Permintaan"))
        item = self.tablePermintaan.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Status"))
        item = self.tablePermintaan.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Aksi"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
